### ISSUE TITLE
Left analog stick Registers and also causes  D-PAD actions

### ISSUE THREAD

**Issue by gigglin1** [nefarius/ScpToolkit#1001]
While attempting to play Dark Souls 3 I have an issue in which any movement of the left analog stick registers movement in addition to the actions the D-Pad should handle.  The game is setup with default controls and the input tester does not register D-Pad presses from the analog stick. 

D Pad works as normal on its own.

Edit: This was the first game I had tried, Rocket League works as intended so does anyone know what the issue could be? I have checked all settings in DS3 controls and there doesn't seem to be any overlap.

**Comment by muffzu** [comment]
The same thing in the game Steep. Sometimes spontaneously the signals from the left analog stick hang and the movement continues even though I've already released the stick
