### ISSUE TITLE
new PID DS4 controller

### ISSUE THREAD

**Issue by knives49** [nefarius/ScpToolkit#1003]
I have a new DS4 controller but scptoolkit doesn't show the controller.
I change the scpcontrol.ini and add HardwareId = USB\VID_054C&PID_09CC 
and in DS4controller.inf 
I add %DeviceName% = USB_Install, USB\VID_054C&PID_09CC
in 
[libusbDevice_WinUSB.NTx86] 
[libusbDevice_WinUSB.NTamd64] 
[libusbDevice_WinUSB.NTia64]

but when I run ScpToolkit Driver Installer the controller doesn't show in Uninitialized DS

Windows 10 find a Wireless Controler in the device manager.

I need to add the new PID somewhere else ?

**Comment by RukeD** [comment]
i used the 1.6 version.  clean wipe. restart. installed with force driver clicked on. restart. at this point bluetooth connection would work but a none status would display under monitoring when controller was connected via usb. i noticed for me on my newer DS4 that i got on black Friday this year was (the only one with issues) was some times showing up in windows devices window as audio device. after several reconects and disconnects i got a the newer ds4  showed up as a speaker simple i right clicked went into properties and disabled now everything seems to be working fine. no white led on bluetooth connect and no none on monitor with ledf shutting off.  note my older ds4 did not have issues or my other 2 ds3
