### ISSUE TITLE
Error starting the service. Reinstall does not help.

### ISSUE THREAD

**Issue by justalemon** [nefarius/ScpToolkit#1008]
## Error on the driver installer:
![image](https://user-images.githubusercontent.com/11861253/34277425-66a258b8-e684-11e7-9098-fc056c7d26b8.png)
```
Couldn't start service:
System.InvalidOperationException: The service Ds3Service cannot be started on this computer
System.Component.Model.Win32Exception: The service or dependency group cannot be started
--- End of the procedure in the internal stack ---
  in
System.ServiceProcess.ServiceController.Start(String[] args)
  in
ScpDriverInstaller.MainWindow.StartService(String service)
```

## Error on services.msc:
![image](https://user-images.githubusercontent.com/11861253/34277448-810b3dc8-e684-11e7-8703-41d75d26ad69.png)
```
Windows was not able to start the service SCP DSx Service on the Local computer.

Error 1068: The service or dependency group cannot be started.
```

**Comment by KaneStaff** [comment]
I have the same issue. If I right click Ds3Service in Task Manager's Services tab and click Start, it says "The operation could not be completed. The dependency service or group failed to start." I installed the last stable one originally which worked for a long time. It probably stopped working with one of the recent Windows updates. I tried the latest beta version which also failed to work.

**Comment by justalemon** [comment]
Yep, both the [stable](https://github.com/nefarius/ScpToolkit/releases/tag/v1.6.238.16010) and [beta](https://github.com/nefarius/ScpToolkit/releases/tag/v1.7.277.16103-BETA) shows the same error.

But using [Scarlet.Crush's](https://forums.pcsx2.net/Thread-XInput-Wrapper-for-DS3-and-Play-com-USB-Dual-DS2-Controller) version don't have the same problem so can be used as a workaround.
