### ISSUE TITLE
not working at all after latest windows 10 update

### ISSUE THREAD

**Issue by isaacay** [nefarius/ScpToolkit#1009]
all i did was update windows and it no longer works I've tried updating even

**Comment by rad2000** [comment]
Just re-run the setup (or re-download if you don't have it anymore) and click on 'repair'.  That fixed it for me.

**Comment by isaacay** [comment]
its detecting the controller now but its nto sending any input or showing in set up usb game controllers like it used to

**Comment by jastermark** [comment]
Did you get any error messages on driver installation, or after?

**Comment by Venorcis** [comment]
Same here, it no longer works, maybe related to the Meltdown Windows patch?

**Comment by isaacay** [comment]
it wasnt Meltdown Windows patch it started before that with the fall creators update
