### ISSUE TITLE
Slot 1 detected but ingame i have a 2 controller

### ISSUE THREAD

**Issue by Jack74r** [nefarius/ScpToolkit#1013]
Hi,
 I'm using scp and work very well but I have a lot of problems with my ps3 controller. I plug it in, it detects it and selects port 1 but in rocket league (or other) I have as if I have two controllers and I control the second one. I am forced to uninstall, restart and reinstall each time. Or maybe I'm just hurting things. 
Can you help me ?

**Comment by jpsplinter66** [comment]
Yeah also having the same problem. Hope someone got the answer. When I go to control panel and test the pad everything is fine so...

**Comment by jpsplinter66** [comment]
Jack74r, Well I fix my problem by just reinstalling windows, must be something about the registry keys or drivers.
