### ISSUE TITLE
Left Analog of PS3 Dualshock randomly pulls left on Windows 8.1 x64

### ISSUE THREAD

**Issue by mikegonzalez2k** [nefarius/ScpToolkit#1019]
While playing the left analog stick of my Dual Shock 3 controller randomly pulls to the left.  It functions perfectly for about 5 minutes.  Then some sort of event trigger causes it to thing the analog stick wants to be in the left position.  I have tried the controller on other devices such as my PS3 and my Galaxy Tab S3 tablet.  The controller works perfectly on those two devices.  It only seems to happen on Windows.  You may want to check if the driver has some sort of cycling that it loops through and checks and accidentally initializes this incorrectly.  Maybe some sort of centering issue with the left analog when it's cycled.  

Currently my only work around is to unplug the wired USB cable to make the controller re-initialize when I plug it back in.  This is why I believe it is something that happens during the cycling of the driver.  The weird thing is that sometimes it goes for a long period of time and other times it right away.  There doesn't seem to be a pattern to when it happens or an action which causes it.  It even occurs when I leave the controller sitting with no motion whatsoever.

Did a few tests I will post the times of how long it took before the error occurred.  It might help if there is a log file that we can look at to see what's being triggered.

Error Times in mm:ss:ds
12:07.0

OS: Windows 8.1 64 bit
SCPToolkit version: 1.6.238.16010

**Comment by mikegonzalez2k** [comment]
Found a fix which I am testing.

I opened the SCPToolkit Settings Manager
In the Global Settings I set the Left Analog's Deadzone slider all the way to the right.
Since the issue was that it pulled left as it recentered, this seemed to instantly make the problem go away.  The controller seems to be perfectly centered.  I didn't even have to unplug the control to make it stop pulling.  I will post more if the problem persists.

**Comment by rkubes** [comment]
When you connect your DS3, does it show up something along the lines as "Fake Dualshock 3" or not genuine? I forgot the exact text.
I had a similar issue with my genuine DS3 that was being incorrectly detected as fake. Once I corrected the issue so it recognized it as genuine, I no longer had the random upper-left pull.

If the MAC address of your controller starts with 08:A9:5A, then it could be the same issue. The solution is about half-way down in #179. Just search that thread for "scpcontrol.ini" to see how you need to modify that file. You'll have to restart the service afterwards (or restart Windows if it's easier for you).

I'm not sure why it matters whether SCP Toolkit detects the controller as genuine or not - maybe something wrong with the "workaround" code.

**Comment by mikegonzalez2k** [comment]
Not sure what the MAC Address of the device is since I've never used it on my PC via bluetooth.  I always have connected via a mini USB charging cable to a USB port.  I can try to look at my DS3's MAC and see if it has the same address as the one you describe causes that problem.

**Comment by mikegonzalez2k** [comment]
Well this old PS3 controller seems to not hold charge any longer.  Can't use it unless plugged in.

**Comment by rkubes** [comment]
I haven't had a chance to play with this yet to determine actual steps, but you should be able to find the Mac address through USB. At worst I believe you can see it in the scp legacy monitor.

Regardless, it can't hurt just to follow those instructions to update the ScpControl.ini anyway. Best case it fixes it, worst case nothing changes.

**Comment by mikegonzalez2k** [comment]
It looks like my DS3 is one of the ones with the MAC mentioned above.  I added that line to the ini, then restarted my PC just to make sure the drivers loaded properly.  So far so good, it's been 10 minutes and no issues yet.  Nefarious may want to add that MAC to future versions of the ini so other users don't get this same issue.  I'll let him know on Twitter.

**Comment by mikegonzalez2k** [comment]
Well after letting it run for about 25 minute the problem came back :(
