### ISSUE TITLE
HOW THE F DO I CHANGE THE QUICK DISCONNECT COMBO

### ISSUE THREAD

**Issue by K9998f** [nefarius/ScpToolkit#1020]
Im tired of RESETTING my DS3 when actually just trying to turn it off. HAPPENS A LOT!
Thats because the Quick Dis Combo includes the PS BUTTON, which is making the controller turn right back on when it is turned off. I have to try REALLY hard to turn it off or else just let it disconnect by AFKing.
Its making me insane.

Where in the files do I find the option to change the combo? I want to change it to something else that does not include the PS button.

**Comment by nefarius** [comment]
It's hard-coded. Watch your language, this isn't kindergarten.
