### ISSUE TITLE
Finally got DS4 recognized - Not working in games?

### ISSUE THREAD

**Issue by NLmitchieNL** [nefarius/ScpToolkit#1034]
Hi guys. I finally got my DS4 to properly connect via bluetooth ,following ReaLx3m's comment in #190 .
But when I try it in Dark Souls III, it doesn't do anything. It is properly plugged into Virtual Bus 1 in the monitor. 

Is this a Dks3 issue, or do more people have issues with the DS4 in games?

Edit: Neither the Dualshock 4 OR Dualshock 3 are detected in-game. 
Should I re-install all drivers?

**Comment by w1r0x** [comment]
DS4 working well in all my games.

**Comment by NLmitchieNL** [comment]
I've tried it in Modern Warfare Remastered. Still nothing happening. 

And they should be connected properly.
Just used the DS3 succesfully in CoD.
![untitled-1](https://user-images.githubusercontent.com/35601603/35154655-52dbf40c-fd2b-11e7-9d72-1bc3091842d9.jpg)
