### ISSUE TITLE
Why are the joysticks so inaccurate

### ISSUE THREAD

**Issue by DarkDan7** [nefarius/ScpToolkit#1038]
The X,Y Axis just jump to an value 
Example : -1 to 12864 is pretty annoying and make some games impossible to play like full metal furries or the challenges from south park stick of truth

**Comment by yarick123** [comment]
@DarkDan7 have you original DS? On many fake DS controllers the potentiometers are crap.

I had the same situation. Just replaced the potentiometers with other from an old controller. The situation improved!

**Comment by DarkDan7** [comment]
@yarick123  i do have some potentiometers laying around but i don't know if the ones i have are original also i don't have an desoldering iron
