### ISSUE TITLE
Fake Controller dump ( Gasia )

### ISSUE THREAD

**Issue by antisparkles99** [nefarius/ScpToolkit#106]
[Controller (XBOX 360 For Windows)_hid-report.dump.txt](https://github.com/nefarius/ScpServer/files/72169/Controller.XBOX.360.For.Windows._hid-report.dump.txt)

For adding support of fake controllers? The dump file ... sorry i am not very good at computers.. Hope you will add bluetooth support?

**Comment by antisparkles99** [comment]
![screenshot_2015-12-27-09-38-20](https://cloud.githubusercontent.com/assets/16436168/12009163/100d9df6-ac7e-11e5-85a3-8d706d4a3de9.jpeg)

This and another Linux software have a very high compatibility with fake/knockoff controllers, is it possible to somehow port the wireless connectivity features from these apps to the latest ScpServer drivers?

**Comment by nefarius** [comment]
What other Linux software? Unfortunately most android apps are closed source; I have tried to contact the author of the "Sixaxis Controller" app but got no response so far. I'd love to see some code working with those knock-offs...

**Comment by antisparkles99** [comment]
https://github.com/mcherri/sixaxis-android

^ The source code and repository of SisAxis Controller

And the repository of the Ubuntu/Linux software is  https://github.com/supertypo/qtsixa

**Comment by nefarius** [comment]
Ah, didn't know these, will have a peek, thanks :)

**Comment by antisparkles99** [comment]
Thanks! :)

**Comment by antisparkles99** [comment]
@nefarius The latest update finally connects the gasia controller!! But it gets connected, only the plugged in port #1 virtual bus message appears, but the controller dosent work, it blinks fr some time, and turns off again, without any input working...Is there a fix?

**Comment by antisparkles99** [comment]
![image](https://cloud.githubusercontent.com/assets/16436168/12547332/d559935a-c360-11e5-99b8-ff750d19146d.png)

**Comment by antisparkles99** [comment]
And the scpmonitor shows these values shortly befor the controller turns off

**Comment by LobsterBuster** [comment]
The Doubleshock PS3 controller works straight up on windows 10.

Here is an image of the product :

![ps3doubleshock](https://cloud.githubusercontent.com/assets/20825788/17383674/35dc5c8c-59a5-11e6-80af-2721f08281d0.JPG)
