### ISSUE TITLE
BigBen BB4401 PS3PADRFLX works for a few seconds, after that it seems stuck (Win7 64).

### ISSUE THREAD

**Issue by Deltomane** [nefarius/ScpToolkit#110]
My fake controller (USB\VID_054C&PID_0268&REV_0100   BigBen BB4401 PS3PADRFLX) works for a few seconds, but immediately after all the controls seem stuck.
As soon as it gets stuck:
-The numbers on the SCP Monitor stop changing:
![immagine](https://cloud.githubusercontent.com/assets/16489880/12051698/143f7616-af07-11e5-9499-6a2ac7538020.png)
-Also the XInput Tester shows a stuck signal:
![immagine2](https://cloud.githubusercontent.com/assets/16489880/12051770/434863ae-af08-11e5-9017-1fd9ddb0231e.png)
This is my Log file:
[ScpToolkit_Log-Package_Alex_1451485111.zip](https://github.com/nefarius/ScpServer/files/74880/ScpToolkit_Log-Package_Alex_1451485111.zip)
Could anyone help me?
Thanks

**Comment by trigrab** [comment]
I have the same issue on the newest Version and could also solve it with the version Deltomane suggested. I will try different versions and controllers soon and then get back here, to report what I found out.

So far I tested every option on the newest Versions ScpSettings if it could help, but it didn't.

**Comment by Deltomane** [comment]
I tried again with the latest beta drivers.
Still same problem...
Could anyone help me?
Thanks
My Log file:
[ScpToolkit_Log-Package_Alex_1480464204.zip](https://github.com/nefarius/ScpToolkit/files/620601/ScpToolkit_Log-Package_Alex_1480464204.zip)
