### ISSUE TITLE
DS3 Controller No Wireless

### ISSUE THREAD

**Issue by dEEE805** [nefarius/ScpToolkit#111]
I installed the latest SCP-toolkit drivers and the output message was that the installation was successful  (it also restarted the SCP service). I installed the bluetooth PS3 and DS3 drivers. The controller works when plugged in to the USB but not via bluetooth. I have the Intel chipset, VID_8087&PID_07DA. The DS3 used to work on the old SCP service. Help please

**Comment by mirhl** [comment]
Check in device manager if the bluetooth adapter is indeed using the SCP driver.

**Comment by mirh** [comment]
@dEEE805 Does it work now?
