### ISSUE TITLE
Suggestion: Expand to controllers other than Playstation

### ISSUE THREAD

**Issue by Nerdy314159265** [nefarius/ScpToolkit#112]
I have to say that I love the work being done on this program. I think it'd be amazing if it was expanded to include other controllers like the Wii, and Wii U controllers.

I understand that may not be likely to happen or even possible but I wanted to put it out there. I think it'd be amazing to have one program that could handle all the unofficial support for getting controllers working on PC properly.

**Comment by Jan200101** [comment]
actually there might be some problems getting the Wii U gamepad to work. But you can already use Wii motes

**Comment by Nerdy314159265** [comment]
@Jan200101 You can't use Wii-motes through this program though, it would require finding a separate one that doesn't have any viruses hidden like some less reputable programs I know of.

I agree that it might be a challenge but I think it'd be awesome to have a single unified program for all console controllers.

**Comment by Jan200101** [comment]
actually i had one where you could write the code yourself e.g. wimote.uparrow = W etc.

**Comment by Nerdy314159265** [comment]
@Jan200101 Last I checked GlovePie was dead.

**Comment by Jan200101** [comment]
It is dead but still works with everything
