### ISSUE TITLE
Always Unplug Virtual Controller Not Working

### ISSUE THREAD

**Issue by KaiserCX** [nefarius/ScpToolkit#120]
I'm using a PS3 controller connected via USB and not bluetooth, I'm on Win10 and I do have the setting checked under the ScpSettings. I've been disabling the ScpService manually to get my arcade stick to take slot one, but I was hoping I wouldn't have to bother anymore with the new setting but sadly it's not working for me. 

I hold down L1+R1+Home to disconnect my controller, I then unplug my controller and it still shows the Xbox 360 controller in "Devices and Printers". Just to make sure I plugged in my arcade stick after disconnecting my PS3 controller and it shows up as player two.

**Comment by nefarius** [comment]
I was able to borrow a Microsoft Xbox 360 Wireless controller and receiver from a friend and as soon as I plug in the receiver the VBus ain't happy anymore =/ I'm on it.
