### ISSUE TITLE
Bluetooth: Host Address is shown but it won't connect.

### ISSUE THREAD

**Issue by Zhythe** [nefarius/ScpToolkit#127]
Hello. I'm currently using a laptop as where I connect my DS3. It looks like the bluetooth that I have is compatible with the SCPToolKit because the host address is shown. I tried using this software on another laptop and it works. Dunno why it won't work with mines (prolly it is not supported/compatible after all, unsure about this tho).

Feel free to ask if you guys have any questions regarding about the specs of my laptop or something else. Thanks in advance.
## LINKS & IMAGES

Log: [ScpToolkit_Log-Package_Zhythe_1452008011.zip](https://github.com/nefarius/ScpServer/files/78584/ScpToolkit_Log-Package_Zhythe_1452008011.zip)
Realtek Bluetooth 4.0 Properties: http://puu.sh/mkuhR/e00daa7e7e.png
Installation: http://puu.sh/mkter/afd6cf25b9.png
DS3 connected: http://puu.sh/mkthx/6c3445444c.png
DS3 disconnected: http://puu.sh/mktln/be8a636e6b.png

**Comment by Zhythe** [comment]
Bump.

**Comment by nefarius** [comment]
Thank you for your detailed reports. I need to review the logs before I can give an answer.
