### ISSUE TITLE
More than 4 controllers issue

### ISSUE THREAD

**Issue by Auburns** [nefarius/ScpToolkit#129]
If a 5th controller is connected it gets stuck in an invisible 5th slot, LEDs just flash continuously and the controller is unusable. It cannot be reassigned without restarting the service. Support for more than 4 controllers would be nice, I remember motion in joy had it back when I used that.

**Comment by mirhl** [comment]
Take into account XInput itself [doesn't](https://msdn.microsoft.com/en-us/library/windows/desktop/ee417001.aspx#multiple_controllers) support more than 4 controllers.
