### ISSUE TITLE
profile manager: swapping trigger/shoulder binds both to shoulder.

### ISSUE THREAD

**Issue by Zivnarb** [nefarius/ScpToolkit#134]
if you bind the buttons like this:
![pm](https://cloud.githubusercontent.com/assets/16584186/12158338/617b8ff0-b4d9-11e5-85fa-46b899947525.jpg)

both L1 and L2 are bound to shoulder, not swapped.

**Comment by nefarius** [comment]
Can confirm, working on a fix.

**Comment by Zivnarb** [comment]
short addendum: played shadow complex remastered with the profile active earlier today, even when the profile manager showed default key bindings (the profile was ticked active but after opening the profile manager showed the default layout - another bug maybe?), L2/R2 activated both L1 and L2 (and R1/R2 respectively), L1/R1 worked like normal; the game behaved as if I'd have bound L2/R2 to two buttons at once. after deleting the swap profile and restarting the service it worked like normal.

don't know if that's an issue with the game, unreal engine 4 for or the driver/profile manager acting weird (haven't tried it with another game yet). profile manager also didn't open the first time I installed the driver. after uninstall, clean wipe and deleting all files it worked after the second install - but then I managed to crash it twice. well, it's still unstable. ;)

**Comment by nefarius** [comment]
Well, the profile manager is still highly experimental...

**Comment by marcelodcs** [comment]
sooo...was this bug fixed yet?

**Comment by charlesmilette** [comment]
Funny. The picture has the same background color as the GitHub Dark UserStyles:  
![capture](https://cloud.githubusercontent.com/assets/6440374/14229894/ef2e2a26-f910-11e5-9dad-fde9b01dfb26.PNG)

Anyways, even if this bug gets fixed, some other errors may be encountered because it is highly experimental, as @nefarius said. Be careful when using it.

**Comment by nefarius** [comment]
@marcelodcs nope.
