### ISSUE TITLE
xinput not working

### ISSUE THREAD

**Issue by Teutorix** [nefarius/ScpToolkit#137]
[ScpToolkit_Log-Package_wolvo_1452300279.zip](https://github.com/nefarius/ScpServer/files/83459/ScpToolkit_Log-Package_wolvo_1452300279.zip)
i have the controller connecting to the software but its not working in any games as an xbox controler

**Comment by nefarius** [comment]
Try the latest release please; I fixed some nasty bugs there, might affect your behavior if we're lucky.
