### ISSUE TITLE
Rename repository from "ScpServer" to "ScpToolkit"?

### ISSUE THREAD

**Issue by kq01526** [nefarius/ScpToolkit#139]
Hi,

why is this repository called "ScpServer" when it is referred to as "ScpToolkit" pretty much everywhere else?

Why not just rename the repository from "ScpServer" to "ScpToolkit"?

Regards

**Comment by nefarius** [comment]
Because it would pretty much break all links circulating around?

**Comment by kq01526** [comment]
> @nefarius wrote:
> 
> Because it would pretty much break all links circulating around?

Not sure, but AFAICT you are wrong, see:

https://github.com/blog/1508-repository-redirects-are-here
https://help.github.com/articles/renaming-a-repository/

:wink:

**Comment by nefarius** [comment]
Uuuuhh, fancy! I'll be brave and try then =]

**Comment by nefarius** [comment]
Great Scott, it worked! Thanks for the suggestion and the links!
