### ISSUE TITLE
Emulated XBOX 360 controller GUIDs are per-slot, not per-original controller GUID

### ISSUE THREAD

**Issue by mirh** [nefarius/ScpToolkit#146]

**Comment by nefarius** [comment]
Uh sorry but what exactly do you mean by that?

**Comment by mirhl** [comment]
Every controller has a unique identifier, right?
If I had two real x360 controllers, program would see them every time with a code like 028e045e-0000-0000-0000-504944564944 or similar. And they would be able to remember per-controller preferences. 

With SCP I noticed in x360ce I always get the same one, no matter which of mine controllers I attach. 
Now, of course they are two identical DS3, so I'm not actually caring, but I see many people with "mixed vendors" compatible controllers would appreciate this.

**Comment by nefarius** [comment]
Is this the value you're talking about?

![12-03-_2016_15-43-46](https://cloud.githubusercontent.com/assets/286631/13723559/60d0d02e-e869-11e5-87c8-a24d6f538a29.png)

**Comment by charlesmilette** [comment]
I find it a bit akward to have like 4 entries in the device manager, while I plugged only 2 unique DS3 controllers in my computer. A virtual device for each real device seams more appropriate than a virtual device per player slot.

**Comment by nefarius** [comment]
@charlesmilette that's a bug.

**Comment by mirh** [comment]
Yes, those identifiers. They shouldn't be slot-fixed.

**Comment by nefarius** [comment]
I see, I'll look into it.

**Comment by nefarius** [comment]
I took a close look and it seems that the `IG` (Device instance GUID) that x360ce reports is composed of multiple sources. Once I figured out how it's composed I'm positive I can solve this. Will browse through x360ce`s sources...
