### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by aayushkapoor206** [nefarius/ScpToolkit#151]
I can't thank you enough for this software...

**Comment by Hoshiyuu** [comment]
Keep in mind that issue tracker isn't a forum, while I am very sure the appreciation is appreciated (lol), but it'll probably more suited to be posted at the discussion thread http://forums.pcsx2.net/Thread-ScpToolkit-XInput-Wrapper-aka-ScpServer-Reloaded
