### ISSUE TITLE
Annoying Notifications

### ISSUE THREAD

**Issue by RaTcHeT302** [nefarius/ScpToolkit#154]
Can these be disabled? They are seriously annoying.
http://i.imgur.com/bYANomp.png

Some of the sound effects are also kinda annoying, really wish they were optional, or at least use the default Windows sounds instead.

**Comment by Jan200101** [comment]
No and Yes.
You can change the sound of it but I dont know if you can hide it yet

**Comment by Hoshiyuu** [comment]
For now you can either untick SCPTrayApp or remove SCPTrayApp.exe from installation folder and it'll work just fine.

You can disable the sound individually or fully by going to the ScpToolkit Settings Manager.
![image](https://cloud.githubusercontent.com/assets/6470662/12306430/a456acf6-ba74-11e5-8308-794f442d1509.png)

**Comment by mirhl** [comment]
Delete ScpToolkit Tray Notifications shortcut from `%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Startup`

**Comment by nefarius** [comment]
I will add some more settings to allow more control over them in a future release.
