### ISSUE TITLE
Adaptor VID_0E8F&PID_0003 not working

### ISSUE THREAD

**Issue by guilegatan** [nefarius/ScpToolkit#155]
Hi!
I have an USB-adaptor for DualShock 2 pads, which is recognized as "PS(R) Gamepad Adaptor". It has the hardware-id USB\VID_0E8F&PID_0003. A Google-search says the same chip is used in multiple 3rd party wired PS3 pads.

It installs fine at first, and ScpToolkit identifies it as "Genuine Sony DualShock 3 detected".
![scptoolkit](https://cloud.githubusercontent.com/assets/16672201/12273262/2d0b328a-b965-11e5-8e2a-b83c8d4077da.jpg)

But it recognizes no button presses. Also the led-indicator on the adaptor is off. Pressing the "Analog"-Button does nothing. On real PS3, the "Analog"-Button is useable as Home-button. After pressing it, the led-indicator shows the assigned controller number.

Any chance that this adaptor will be supported anytime?

thanks,
keep up the great work!

**Comment by mirhl** [comment]
Attaching debug information like mentioned in the forum thread wouldn't hurt in the first place.

**Comment by guilegatan** [comment]
Sorry .. yes .. you are right.
Here is the debug info!
[ScpToolkit_Log-Package_Martin_1452951469.zip](https://github.com/nefarius/ScpToolkit/files/92899/ScpToolkit_Log-Package_Martin_1452951469.zip)

**Comment by Mugi4ok** [comment]
Mine DS2 adaptor (from DreamGEAR) has the same ID, behavior is same, recognized as "USB Joystick".

**Comment by mirh** [comment]
I guess #243 ?
