### ISSUE TITLE
I used to use the Scarlet.Crush version but deleted the installation folder

### ISSUE THREAD

**Issue by waxcola** [nefarius/ScpToolkit#157]
I used to have the old scpserver stuff by Scarlet.Crush and I had the installation folder on my desktop. It worked flawlessly as far as I could tell, but ater a while I didn't need to use my PS3 controller with my PC anymore and after a few months while looking for stuff I could delete off of my computer to save space I didn't recognize the SCP folder in my desktop so I deleted it and eventually emptied the recycle bin. This was a long time ago and ever since then I haven't been able to get it to work again. I even Refreshed windows and installed this new version afterwards but it still won't work. I'm at a loss about what I should do other than Resetting windows (reverting it to factory state without formatting the hard drive basically) which would be a huge time sink. Unfortunately I've got another issue too. I've already ran the debugger but when I try to attach the zip to the issue I get an error saying "Unfortunately, we don't support that file type". I've tried extracting the files and putting them in another zip but it still won't work. Is there any website I could upload it to?

**Comment by Hoshiyuu** [comment]
You can upload files by directly dragging and dropping into the comment box on this page - that said, if the new version arent working for you and you are in a hurry, the old version discontinued by Scarlet Crush is still available in this post: http://forums.pcsx2.net/Thread-XInput-Wrapper-for-DS3-and-Play-com-USB-Dual-DS2-Controller
