### ISSUE TITLE
BSOD after install the driver

### ISSUE THREAD

**Issue by nikhosagala** [nefarius/ScpToolkit#166]
I got blue screen after finish installing the driver. DRIVER_VERIFIER_IOMANAGER_VIOLATION. (ScpVBus.sys)

**Comment by Jan200101** [comment]
only @nefarius can help you there

**Comment by RegnarRF** [comment]
+, i have this problem too on Windows 10 x64

**Comment by war1ox** [comment]
Yeah my pc locks up every other install. I guess its just normal. Lol

**Comment by mirhl** [comment]
Duplicate of #29

**Comment by nikhosagala** [comment]
Try this, solved my problem

1. Uninstall the driver
2. Open cmd as admin
3. Type verifier.exe /reset
4. Reboot your PC
5. Reinstall the driver

**Comment by nefarius** [comment]
This issue is fixed in the upcoming release.
