### ISSUE TITLE
Crash with Pscx2 1.4

### ISSUE THREAD

**Issue by Tienosim** [nefarius/ScpToolkit#167]
Hello,
Today i install ScpToolkit for use my PS4 controler for Steam Games and it's works.
I install Pscx2 1.4 and i use the pscx2 setting for add customized Xinput 1.3 and Lilipad but when i launch Pscx2 it can't found Lilipad plugin and Pscx2 freeze and crashed. 

Edit : if i delete padPokopom it was work

**Comment by Jan200101** [comment]
It may just be that the 2 plugins overwrite each other

**Comment by mirhl** [comment]
Nefarious may want to take into account pcsx2/pcsx2#1040

**Comment by nefarius** [comment]
Yupp that's a bug. Will try to replicate ASAP.
