### ISSUE TITLE
Bluetooth not functional, says connected when it's not.

### ISSUE THREAD

**Issue by war1ox** [nefarius/ScpToolkit#175]
EDIT- I found a version that works good for me. It's v1.6.133.15324 https://github.com/nefarius/ScpToolkit/releases/tag/v1.6.133.15324

I have a DS3 USB\VID_054C&PID_0268 and a Trendnet Bluetooth dongle with EDR. When I do a fresh install, I am given no errors. The controller makes the connection sound when wired and powered on wirelessly, but when I go to test, it doesn't work in-game.

Here is the installation log:
![debag](https://cloud.githubusercontent.com/assets/16828340/12502834/6190a728-c082-11e5-8823-06b5cfbb9359.jpg)

Not sure if this is important, but when I disabled the scpservice and start the scpserver, I noticed it gives off an error. (Note that it says connected at the top of the screen via bluetooth):
![3b8dab8a-c081-11e5-8ecc-3e2bb09cbad4](https://cloud.githubusercontent.com/assets/16828340/12502889/0b494608-c083-11e5-8d30-c126fdbb65ae.jpg)

Here's my wired Log-Package:
http://www.filedropper.com/scptoolkitlog-packagemrfreez1453440633

Here's my Bluetooth adapter:
http://www.amazon.com/TRENDnet-Bluetooth-Distance-Compatible-Classic/dp/B003KU4DOG/ref=sr_1_1?s=pc&ie=UTF8&qid=1453454804&sr=1-1&keywords=trendnet+bluetooth+adapter

Does anyone have any idea why this tool is giving me such trouble if it was working before the last 3 or so updates? I haven't changed anything, just updated the utility. Thanks

EDIT- I found a version that works good for me. It's v1.6.133.15324 https://github.com/nefarius/ScpToolkit/releases/tag/v1.6.133.15324

**Comment by nefarius** [comment]
So is there still an issue with an up2date version?
