### ISSUE TITLE
PANHAI Controller - Rolling Connection Attempts On Bluetooth

### ISSUE THREAD

**Issue by Khevarash** [nefarius/ScpToolkit#176]
Hello all!

As in the description, it's a Dualshock 3 fake (PANHAI) that works fine on cable but bluetooth connection doesn't stay and will infinitely keep attempting to connect.

Here's a screenshot of what is coming up at the taskbar:
![Rolling Connection](http://puu.sh/mGfCd/485d962cfa.png)

The debug: http://puu.sh/mGg8Q/47c41057df.zip (ScpToolkit_Log-Package_MAGI_SYS_1453531115.zip)

Thank you for any support you may offer!

**Comment by nefarius** [comment]
Sadly this isn't fixable at the moment. If you experience this it means the controller is not supported.
