### ISSUE TITLE
Installer stuck

### ISSUE THREAD

**Issue by Keefaetana** [nefarius/ScpToolkit#177]
Yesterday I noticed there's a new version of ScpToolkit and decided to try and install it over the old version I already had installed. I downloaded the installer and ran it, but it got stuck at "Preparing...". I then tried running it as Administrator, but it still gets stuck at the same point. Then I tried uninstalling the old version and rebooting, then running the installer again. It's now been stuck at that point for at least half an hour with no sign of ever getting past the preparing phase. Anything I could do to try and get the installer to work?

I'm running Windows 10 x64 with the most recent updates. The last version before the end of the year installs and works fine, but neither of the versions released in 2016 seem to complete installing.

**Comment by nihaomeeow** [comment]
Same problem here. Just did a clean install of Win7 Pro. The toolkit installed some of the other things first like the Xbox driver but then it got stuck at the message saying it could take up to 5 minutes.

**Comment by nefarius** [comment]
This get's fixed in an upcoming version.

**Comment by boskio** [comment]
..was this ever fixed?.. still sat looking at the waiting screen :)

**Comment by mloo3** [comment]
I am still getting stuck as well
