### ISSUE TITLE
Bug: Logs Folder

### ISSUE THREAD

**Issue by Zhythe** [nefarius/ScpToolkit#186]
![ss 2016-01-27 at 02 25 58](https://cloud.githubusercontent.com/assets/16560383/12605687/2cb334a6-c502-11e5-8897-2f7a9d5afc99.png)

![ss 2016-01-27 at 02 34 03](https://cloud.githubusercontent.com/assets/16560383/12605800/23293a7e-c503-11e5-85ba-ee825a145ca6.png)

This problem really made me wanna reset my Windows until I found out that it is that folder who is messing with my hard disk space. Hopefully this will be fixed.

@nefarius: Please respond on my previous topic (https://github.com/nefarius/ScpToolkit/issues/127). I need your help. Thanks in advance.

**Comment by nefarius** [comment]
Holy sh*t! That's not supposed to happen, could you compress and post me at least parts oft the file so I can investigate?
