### ISSUE TITLE
Cant use bluetooth keyboard after install

### ISSUE THREAD

**Issue by DoeEensGek** [nefarius/ScpToolkit#188]
Is there any way to still use the bluetooth adapter also for my keyboard?
Also my fake controller wont connect while the real ds3 works fine, any idea?

**Comment by theczorn** [comment]
What fake controller are you using? Make/Model/Serial #?

**Comment by nefarius** [comment]
@your first question: nope.

**Comment by DoeEensGek** [comment]
ok, thx.
@theczorn a p3 controller, VID_054C&PID_0268, dont know where to get more information, It works with cable, only not the ?thumbs? and not with bleutooth at all.

**Comment by DoeEensGek** [comment]
Ok update; this version worked better:
https://github.com/nefarius/ScpToolkit/releases/tag/v1.6.133.15324

Only problem now is the joystick doesnt work for the fake controller. Bluetooth does work for both controllers.

**Comment by mirhl** [comment]
You might want to change title to just highlight the second problem.
