### ISSUE TITLE
Cannot open server GUI when service is running

### ISSUE THREAD

**Issue by Aureliaar** [nefarius/ScpToolkit#189]
There's currently no (intuitive) way to open the GUI when the service is running: the service isn't shown as a process, Trayapp \ Monitor cannot force a controller disconnect, and trying to open ScpServer.exe triggers a "Already open" error.

**Comment by nefarius** [comment]
That's expected behavior, the Server executable is a legacy component. The error message tells you the facts; you just not run both the service and the Server. Period. Forcing a controller disconnect isn't implemented in any of the tools yet.
