### ISSUE TITLE
DS3 Joysticks work, but no other input will work

### ISSUE THREAD

**Issue by nedm89** [nefarius/ScpToolkit#194]
[ScpToolkit_Log-Package_Bitchbox_1454224699.zip](https://github.com/nefarius/ScpToolkit/files/111162/ScpToolkit_Log-Package_Bitchbox_1454224699.zip)

**Comment by theczorn** [comment]
When you say "no other input will work" do you mean:
a.) Only the DS3 joysticks receive input. None of the other controller buttons work.
OR
b.) The DS3 controller works with bluetooth, but all other bluetooth devices (mice, keyboards, etc) become unresponsive.

Is this only occurring when using a USB connector, using bluetooth, or for both?

**Comment by nedm89** [comment]
I appreciate your reply, the joysticks wouldn't work but after reinstalling
everything it works fine. Thank you so much for the follow up email though
