### ISSUE TITLE
Mouse doen't work after install usb/BT

### ISSUE THREAD

**Issue by Hactarus** [nefarius/ScpToolkit#196]
I use logitech wireless keyboard + mouse and official CECHZC2E sony DS3 Controller on Windows 10.
I install drivers for BT and/or USB for this controller, I loss my mouse, and need to unistall drivers with keyboard to fix.
In usb mode crontoller is detect by win10, but with 00:00:00:00:00:00 MAC address (for host and pad1) and no input work.
Do you need more informations ?

http://up.edmund.ovh/file/kpBF5bmeNF7aiFaA/FHf9g3nB8O8n4O6q/ScpToolkit_Log1454364133.ZIP

**Comment by Hactarus** [comment]
No mouse after reboot clean and unistall.
Controller is now right usb detected (but no input yet).
http://up.edmund.ovh/file/igtkt2gbl5BcFn0h/OFMOCpOB3qtF6Irp/ScpToolkit_Log-Package_LanParty_1454366425.zip

**Comment by mirhl** [comment]
BT adapter needs dualshock compatible driver. 
It cannot be fixed.

**Comment by llakssz** [comment]
DS4Windows works with my DS4 and bluetooth devices still work (speakers etc) - but this is a problem with ScpToolkit? Why?

**Comment by mirh** [comment]
Because DS4 has a PC specific mode where it just work with bt own "controller" profile. 
DS3 hasn't this luxury afaik.

**Comment by llakssz** [comment]
Ah ok thanks, that makes sense :)

**Comment by SebBareyre** [comment]
I have the same problem.. Any help ?

**Comment by llakssz** [comment]
I assume you have uninstalled the driver, right?

**Comment by SebBareyre** [comment]
Yes but my computer didn't detect my bluetooth mouse

**Comment by mirh** [comment]
Open device manager and check?

**Comment by charlesmilette** [comment]
Try to restart your computer, for it to reinstall the original driver

**Comment by Jan200101** [comment]
Quick question does your mouse etc. connect over a bluetooth dongle or its own dongle ? This may explain somethings

**Comment by magevideogames** [comment]
In order to have a bluetooth mouse still work, you must disconnect the bluetooth dongle before installing the controller drivers. Then you can plug it back in after the installation finishes and it will work. That is what I have to do in order to not lose my mouse. You have to do the same thing before starting the service as well. This could easily be solved by allowing the drivers to be installed without bluetooth support. As of the latest version, the bluetooth driver is still installed even if you uncheck it.

**Comment by mirh** [comment]
Or you can just open device manager and revert back to default driver. 
Anyway, hopefully it will be fixed in next incoming version.
