### ISSUE TITLE
Spam disable

### ISSUE THREAD

**Issue by n1kolaa** [nefarius/ScpToolkit#198]
SPC make a lot spam. Are posibole to disable those report from it??

**Comment by nefarius** [comment]
What Spam?

**Comment by Hoshiyuu** [comment]
I am guessing he is referring to the tray app notification spam.

**Comment by mirhl** [comment]
Duplicate of #154 and

> Delete ScpToolkit Tray Notifications shortcut from %ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Startup

**Comment by nefarius** [comment]
You can either follow @mirh 's suggestion or run the setup and uninstall the `ScpToolkit Tray Notifications` component.
