### ISSUE TITLE
No device connected

### ISSUE THREAD

**Issue by vaindil** [nefarius/ScpToolkit#199]
When the service is running, the monitor says `Host Address: <Error>`, and says all pads are disconnected. When the service isn't running, the monitor detects my controller and says it's charging. The controller doesn't actually work in either situation. The program installed correctly, as did the driver. I left all defaults in the program installation, but installed only the DS3 driver, and I selected my DS3 when doing so. The legacy program works just fine (as in I uninstalled this continuation project and used the original version, no problems). I've attached my debug info. Additionally, the uninstall window looks like the attached image. Windows 10 Education x64
![capture](https://cloud.githubusercontent.com/assets/771134/12870094/9a2c44a2-cd02-11e5-9864-01eef78d8143.PNG)
[ScpToolkit_Log-Package_Steven_1454802242.zip](https://github.com/nefarius/ScpToolkit/files/120493/ScpToolkit_Log-Package_Steven_1454802242.zip)

**Comment by machstem** [comment]
I am having the same issues, basically.

Windows 10 Enterprise
