### ISSUE TITLE
BTH DS3 Device

### ISSUE THREAD

**Issue by Clixtons** [nefarius/ScpToolkit#200]
all my dongles are automatically converted to bth ds3 device, how can i remove so it wont do that.
i only want one dongle for my controller and other dongles for other devices(wireless headset for example)

**Comment by mirhl** [comment]
If you are sure you haven't ticked bluetooth devices to overwrite in the installer then I guess this could be considered a duplicare of #174 
Or better to wait for nefarious to know if selection of *every* bt dongle installed shouldn't on the other hand be the point here.

**Comment by theczorn** [comment]
What device(s) are you installing the Bluetooth drivers on in the Driver Installer? IIRC it's possible to target a USB Hub and overwrite all your dongles at once when you intend to target a specific USB dongle.

**Comment by mirh** [comment]
#218 seems to confirm my second guess.
