### ISSUE TITLE
Cannot connect DS3 via bluetooth

### ISSUE THREAD

**Issue by tovarishes** [nefarius/ScpToolkit#203]
I have a late 2015 retina imac running windows via bootcamp. It has a bluetooth adapter with ID VID_05AC&PID_8294. I cant seem to get this to connect to my DS3.
While my macbookpro has an older ID USB\VID_05AC&PID_8289 it can connect to the DS3 via bluetooth. How can I debug what goes wrong?

I must add that I can use the DS3 via bluetooth in OSX so the bluetooth adapter must support EDR.

[ScpToolkit_Log-Package_kundu_1454928296.zip](https://github.com/nefarius/ScpToolkit/files/121465/ScpToolkit_Log-Package_kundu_1454928296.zip)

**Comment by mirh** [comment]
#380
