### ISSUE TITLE
FATAL - Virtual bus driver pre-installation failed with Win32 error 3758096966

### ISSUE THREAD

**Issue by nicolaas100** [nefarius/ScpToolkit#204]
Couldn't install original SCP due to PnP file not installing, wanted to try with your SCP toolkit but i got the error: FATAL - Virtual bus driver pre-installation failed with Win32 error 3758096966

I have no idea what the problem is. I couldn't attach the log so i uploaded it to filedropper.. http://www.filedropper.com/scptoolkitlog-packagenick1454975782

Please help!

**Comment by nefarius** [comment]
Hopefully the next release will help!
