### ISSUE TITLE
BSOD when plugging in DS3/DS4

### ISSUE THREAD

**Issue by solofa** [nefarius/ScpToolkit#205]
As title- Getting a BSOD with no written minidump when I plug in controllers. The BSOD itself states the driver is to blame.

Debug info: http://puu.sh/n1kml/6524eb8945.zip

**Comment by mirhl** [comment]
I'm not sure how controller name and VID could help specifically.. 
Could you post the actual BSOD code?

**Comment by nefarius** [comment]
A tad more info on the BSOD itself would indeed be helpful...

**Comment by nefarius** [comment]
So no BSOD dump after a month, I think I'll close this one.
