### ISSUE TITLE
Can't see Bluetooth adapter on Dell XPS 9550

### ISSUE THREAD

**Issue by machstem** [nefarius/ScpToolkit#208]
I can't seem to get the BlueTooth component to work but the two PS3 controllers are picked up using USB cables.

From my own sleuthing, I believe it has something to do with the device not being recognized and properly converted to allow for it?  I dunno, but here is my device ID info

%DeviceName% = USB_Install, USB\VID_0A5C&PID_6410
%DeviceName% = USB_Install, USB\VID_0A5C&PID_6410&REV_0112

Any advice/help

Thanks

**Comment by nefarius** [comment]
Can't tell much about integrated Bluetooth chipsets since manufacturers drivers always do some weird magic not available to the public. [Try getting one of the compatible dongles.](../wiki/Compatible-Bluetooth-Devices)
