### ISSUE TITLE
need help bluetooh with ds3

### ISSUE THREAD

**Issue by promanxsuper** [nefarius/ScpToolkit#210]
help please , it's okay when i'm using cable , but not work with bluetooth dongle 4.0 , keep saying fake ds3 controller
https://cdn.fbsbx.com/hphotos-xap1/v/t59.2708-21/12678857_1051903601497475_1443224316_n.zip/ScpToolkit_Log-Package_bayu__1455288490.zip?oh=165efb9e68ed6e22fcb35058c8a4efab&oe=56C00EAE&dl=1

**Comment by FusionLord** [comment]
The link you provided cannot be accessed, drag and drop files in to the comment window.

**Comment by Jan200101** [comment]
ehm @promanxsuper are you still there ? When yes then again the link broke because it was on there for too long
