### ISSUE TITLE
Webcam recognized as bluetooth dongle

### ISSUE THREAD

**Issue by charlesmilette** [nefarius/ScpToolkit#212]
Look at the screen:  
![capture](https://cloud.githubusercontent.com/assets/6440374/13034680/2fa03b08-d30a-11e5-8e76-25cb6e35e270.PNG)

HP Truevision HD is my webcam...

BTW why is the PS3 controller listed here ? It isn't a bluetooth dongle

**Comment by nefarius** [comment]
There is no check **what** the listed devices are, that's why *you* - the user - have to tell the program what's a Bluetooth dongle. The list just shows all detected USB devices.

**Comment by charlesmilette** [comment]
Wow, that was fast.

**Comment by nefarius** [comment]
I'm currently online ;)

**Comment by charlesmilette** [comment]
If I install the bluetooth driver, will I be able to still use it for other things, because I only have the integrated bluetooth chip, and no dongle at disposition.

**Comment by nefarius** [comment]
**No** you won't, the Dongle becomes dedicated to SCP and all currently connected Bluetooth devices will immediately lose connection.

**Comment by charlesmilette** [comment]
Any whay to pair my DS3 with the computer without a special driver?

**Comment by nefarius** [comment]
Nope.

**Comment by charlesmilette** [comment]
;(

**Comment by charlesmilette** [comment]
Finally, i said "Screw this" and I overwrote my bluetooth driver. I never used it before. BTW, how can I disable bluetooth (like not active) when my laptop is on battery, I need the more battery life possible for school.

**Comment by nefarius** [comment]
Do you have a dedicated switch one one of your laptops side? Typically you can turn off Bluetooth and wireless networking with that. If not - sorry, no power savings implemented in the software.

**Comment by charlesmilette** [comment]
No I don't have a switch on it, but I have a airplane mode button on it (FN + F12) I think this button is implemented with software, not hardware, so it will not work. (When I resetted my PC, I had to install a driver this button to work)

**Comment by charlesmilette** [comment]
I just tried, it doesn't works. It just disables the Wi-Fi via Windows

**Comment by nefarius** [comment]
The software-turn-off typically only works with the original manufacturers drivers.

**Comment by charlesmilette** [comment]
If I stop and start the service, it then saids "Initializing Bluetooth host", does that means that stopping the service will stop the Bluetooth?

**Comment by nefarius** [comment]
Well, what's your expectation on "stop the Bluetooth"?

**Comment by charlesmilette** [comment]
Full disable, like when you turn the Bluetooth switch on or off on a cellphone.  
I can't just unplug the dongle, the card is inside my computer. Plus the same card also gaves me WiFi.
