### ISSUE TITLE
When installing, unchecking the tray app result in a false error message.

### ISSUE THREAD

**Issue by charlesmilette** [nefarius/ScpToolkit#216]
When I install with the tray app unchecked, I get the error "File ScpTrayNotifications.exe not marked for install." Or something like that, I don't recall correctly. It then says the setup failed, but everything is okay (The start menu links and program files are here, as is the uninstall entry.).

**Comment by Jan200101** [comment]
Uninstall it reinstall it and disable the tray app from autostart

**Comment by charlesmilette** [comment]
Actually, I just kept the install like that and I got nothing wrong. The error is just something to get rid of, because it is not true it failed. All succeded, except the tray aoo.

**Comment by Jan200101** [comment]
Then nothing is wrong everything is okay the error is just there because it isnt marked (like the error says) lets quickly put @nefarius in here so he knows
