### ISSUE TITLE
Input not recognized by games

### ISSUE THREAD

**Issue by yrro** [nefarius/ScpToolkit#220]
On a Windows 7 system with a DS3 controller, the input tester shows the controller buttons & axes working but when running Dirt 3 the controller inputs do nothing.

This is similar to issue #219, but I didn't want to hijack some else's bug.

Here's the output from the debug tool: [ScpToolkit_Log-Package_Pete_1455719562.zip](https://github.com/nefarius/ScpToolkit/files/134491/ScpToolkit_Log-Package_Pete_1455719562.zip)

**Comment by mirh** [comment]
> This is similar to issue #219, but I didn't want to hijack some else's bug.

You don't seem to grasp the idea of bug report. This isn't a "forum". You *are* expected to "hijack" bugs (which aren't "owned" by reporters btw ;))

**Comment by Jan200101** [comment]
Do you have something like Vjoy installed ? It breaks some games e.g. The Binding of Isaac and others
