### ISSUE TITLE
Null Reference error

### ISSUE THREAD

**Issue by Faane** [nefarius/ScpToolkit#226]
So, I recently started using this toollkit, and it worked wonderfully. And then my computer abruptly turned off(unrelated reason to toolkit ) and it stopped working and started throwing a null Reference error. The only way I've managed to get it working is by running the server.

**Comment by Faane** [comment]
Fixed it by going into Driver Manager and forcibly removing both the xbox 360 controller(virutal controller?) and the ps3 libusbk driver.

**Comment by Iceby** [comment]
YOU ARE A GOD OMG THANKS, FINALLY I CAN PLAY MY DAMN DRAGON QUEST VIII ON PCSX2 MAN YOU ARE A GOD
