### ISSUE TITLE
Genuine PS3 controller only works with cable

### ISSUE THREAD

**Issue by KlausConrado** [nefarius/ScpToolkit#227]
Hi.
The controller works fine with the USB cable, but when i disconnect it, the lights of the controller just flash for a while and then nothing happens. Tried to push the hard reset button of the controller, but no luck.
Here is a screenshot of the server log.

Thanks.

![server](https://cloud.githubusercontent.com/assets/12648070/13381848/e0b28c76-de44-11e5-9f3c-68bbdbe2a19a.png)

**Comment by bdefore** [comment]
I'm getting the same behavior. It never seems to pair with my Rocketfish Bluetooth adapter, which is listed as supported. Happy to have it working while cabled though, so thanks!

**Comment by bdefore** [comment]
Disregard, Rocketfish worked correctly for me when I scrolled down to select it as the Bluetooth adapter during install.

**Comment by Jan200101** [comment]
#224 Download my Service Checker from there and if it says its off do the steps on my last post.
If you dont get what i mean reply

**Comment by KlausConrado** [comment]
Actually i prefer to use the standalone server (ScpServer.exe) instead of the service, this way the service is always stopped.
But i have good news, i tested again today and "magically " the controller is working on bluetooth. Don't know what happens, cause i restarted the computer several times before posting this issue.
The Windows 10 updated itself yesterday, that's the only thing i can imagina that could affect something.

Thanks anyway!

**Comment by KlausConrado** [comment]
Just had the same issue with another controller. If you connect a new controller through USB and use only the standalone server (not the service), it will not work on bluetooth if you disconnect the USB. 
However, i figured out how to fix it. Just stop the server, connect the controlller through USB and start the service. Then, the controller will start to work on bluetooth and you can stop the service and open the server again.

**So i guess the problem still exists in the standalone server, cause you have to use the service in the first time for new controllers.**

Oh, and a hard reset (hidden button in the back of the controller) may be needed before this process to make them work on bluetooth.

Thanks.

**Comment by mirh** [comment]
Which standalone server are we talking about? I thought service was a required component.

**Comment by KlausConrado** [comment]
@mirh It's a executable called "ScpServer.exe". Actually you can't run this server if the service is already running. It's very useful if you don't use the controllers too often and don't want the service running all the time.

**Comment by mirh** [comment]
I'm not sure that's expect to work.. 
If I had to judge from the icon, I'd say it's a original scarlett.crush driver leftover.
