### ISSUE TITLE
DS3 notworking

### ISSUE THREAD

**Issue by Hunlight** [nefarius/ScpToolkit#229]
[ScpToolkit_Log-Package_viesk_1457115554.zip](https://github.com/nefarius/ScpToolkit/files/159174/ScpToolkit_Log-Package_viesk_1457115554.zip)
So I used to use MotioninJoy but peopel suggest  scpToolkit isntead I installed it then installed drivers.Now I went to Game controllers and it shows xbox 360 for windows I click test and its not working buttons/sticks etc. nothing. I read few thread the solution can be to run scpserver ,but when I run it ir always stopped working

**Comment by Jan200101** [comment]
1.MotionJoy is not a good program and can harm your system.
2.scpserver is no the right thing you want it just shows if you controller is working based on what you said it should work correct
3.Try uninstalling the controller drivers and reinstall them (Uninstall the XBOX controller and reinstall this tool)

**Comment by Hunlight** [comment]
I installed scptoolkit and then it start showing xbox360 before it said smth like game controller etc.

**Comment by beavermml** [comment]
i think u should uninstall MotionInJoy first before attempting to install SCPToolkit

**Comment by Hunlight** [comment]
I have uninstalled it before done scptoolkit

**Comment by Jan200101** [comment]
It can be that your controller is set to the value 0 and that it doesnt update that value sadly I dont know if this glitch can be / has been fixed
