### ISSUE TITLE
"The root hub is already running"

### ISSUE THREAD

**Issue by umidoo** [nefarius/ScpToolkit#230]
Where can I stop the root hub?
 sorry I'm not a native english speaker and this is a little bit confusing for me. I'm trying to connect my controller via bluetooth but it's not working properly so I went to open the Server and try it but this message shows up. What should I do?

**Comment by umidoo** [comment]
dongle id is USB\VID_054C&PID_0268\5&15C311E1&0&8 if it's needed

**Comment by Jan200101** [comment]
Im going to explain it with a picture here 
![i](https://cloud.githubusercontent.com/assets/15076013/13609685/5ad41922-e55a-11e5-87a4-395cacfb5fd8.png)

**Comment by nefarius** [comment]
Since I can't see this being an actual bug repprt I'll close.
