### ISSUE TITLE
Option : Auto set Controller 1

### ISSUE THREAD

**Issue by beavermml** [nefarius/ScpToolkit#231]
Auto set connected controller to slot 1 if slot 1 controller is plugged out etc.. This will be helpful when switching controller due to battery issues etc

**Comment by Jan200101** [comment]
Try giving Issues that just are some ideas a flare in the title like [IDEA] or something like that it makes it easier

**Comment by mirh** [comment]
`Always unplug virtual controller` is what you are looking for
