### ISSUE TITLE
PS Move Controller is outside the scope of this application

### ISSUE THREAD

**Issue by gjveron** [nefarius/ScpToolkit#234]
I just want to make sure that it is documented that the PS Move Controller is outside the scope of this application and it will never work (the one with the color led ball at the top)

The PS Navigation Controller instead, works perfectly (the one with the analog stick)

can anyone confirm this?

**Comment by charlesmilette** [comment]
This driver is only for  
![this](http://www.ultimateplaystationcontroller.com/wp-content/uploads/2013/09/black1.jpg) and ![this](http://technabob.com/blog/wp-content/uploads/2013/11/playstation-4-dualshock-4-controller.jpg)

Their unofficial alternatives may be supported.

**Comment by Jan200101** [comment]
It may be added some time please close this Issue
