### ISSUE TITLE
Locked out of laptop after install

### ISSUE THREAD

**Issue by willtron3000** [nefarius/ScpToolkit#242]
Upon restarting after installing my laptop I'm totally locked out; usb slots are all disabled, keyboard and touchpad don't work. The driver is overwriting them. I can use the touchpad and keyboard in the bios, as soon as it gets to login in Windows 10 - nothing works.

**Comment by willtron3000** [comment]
Edit: safe mode doesn't get around this.

**Comment by nefarius** [comment]
I guess you just ticked every check box you could find in the driver installer and overwrote drivers for your keyboard and such... Well, plug in an external USB keyboard and undo your damage manually using Windows Device Manager.

**Comment by charlesmilette** [comment]
Try to boot into WinRE and run the clean wipe tool from here.
