### ISSUE TITLE
can't use my controller wirelessly

### ISSUE THREAD

**Issue by MWeWe** [nefarius/ScpToolkit#246]
they works with Scarlet.Crush old version
[ScpToolkit_Log-Package_WeWe_1459072471.zip](https://github.com/nefarius/ScpToolkit/files/190850/ScpToolkit_Log-Package_WeWe_1459072471.zip)

**Comment by LOSSLOSS** [comment]
Check this: https://github.com/nefarius/ScpToolkit/issues/241
We'll have to wait for a fix.

On which version did it work?

**Comment by MWeWe** [comment]
V1.2.2.175

**Comment by Jan200101** [comment]
There wont be a fix for this one problem.
Its a problem with the service not starting right most at the startup on most systems so set it to late start

**Comment by charlesmilette** [comment]
Or start it manually when needed.  
Anyways. Related to #48

**Comment by MWeWe** [comment]
thank you guys,
can anyone tell me what should i do step by step

**Comment by charlesmilette** [comment]
In a elevated command prompt, type `sc config Ds3Service start= delayed-auto`

**Comment by Jan200101** [comment]
Or if you dont know how to do that i made a little Batch compiled into a Exe that does that and even tries to troubleshoot when its failed.

https://onedrive.live.com/redir?resid=531AF8D5D12A8FC8!2727&authkey=!AIKadP-HA816bn8&ithint=file%2cexe

by the way i was too lazy to make a name if you cant tell

**Comment by MWeWe** [comment]
still having the same problem here my new files
![scp server](https://cloud.githubusercontent.com/assets/18098415/14403656/e4cdfcd2-fe60-11e5-94a1-ce57b3bcc6aa.jpg)
[ScpToolkit_Log-Package_WeWe_1460203395.zip](https://github.com/nefarius/ScpToolkit/files/211242/ScpToolkit_Log-Package_WeWe_1460203395.zip)

now after reverting back to ScpServer V1.2.2.175
service not starting but when i open ScpServer.exe it works
