### ISSUE TITLE
My Bluetooth adapter is not showing up.

### ISSUE THREAD

**Issue by vinnegsh** [nefarius/ScpToolkit#248]
Hey there. I own a Asus K46CA with a Qualcomm Atheros AR3012 Bluetooth adapter and it's not showing up in the list to install the drivers. What can I do?

Here's a pic: http://i.imgur.com/BJXzGXv.png and http://i.imgur.com/y2EB1mr.png

Thanks :0

**Comment by nefarius** [comment]
Aaaaaaand what about that `Bluetooth USB Host Controller` in the first pic?

**Comment by vinnegsh** [comment]
That's the one I've been trying without success :(
