### ISSUE TITLE
Not working at All

### ISSUE THREAD

**Issue by HelpMe1234** [nefarius/ScpToolkit#250]
I recently upgraded to Windows 10 and uninstalled Motionjoy and I cannot figure out why the SCPToolKit program isn't working for me. I am using a DS3 (PS3) controller connected via USB. It is recognized as a PS3 controller by my PC. Here's a screenshot of the program when I try to install it.
![image](https://cloud.githubusercontent.com/assets/18147142/14114563/643ed672-f5a5-11e5-9546-278c9801c46c.png)
There is no XBOX 360 controller listed under devices and hardware.

**Comment by charlesmilette** [comment]
You need to have the driver installed before seeing any virtual controller

**Comment by HelpMe1234** [comment]
The XBOX360 driver? That already comes with Windows 10 I thought.

**Comment by charlesmilette** [comment]
The driver for the PS3 Controller.  
Check PS3 Controller on the driver installer and press "Install"

**Comment by HelpMe1234** [comment]
Like in the picture above...?

**Comment by charlesmilette** [comment]
Yes.

**Comment by HelpMe1234** [comment]
I did... and the log is from after I did that. Still no XBOX360 controller in devices.

**Comment by charlesmilette** [comment]
Have you checked in the control panel?  
![2016-03-29_12-17-43](https://cloud.githubusercontent.com/assets/6440374/14115278/5235c08c-f5a8-11e5-9fac-dbd41801cfe9.png)

**Comment by HelpMe1234** [comment]
Yup Control Panel > Devices and Printers only shows PS3 controller no xbox controller.

**Comment by charlesmilette** [comment]
Try unplugging and repluging your controller to see.  

If it won't work then try this:
- Unplug the PS3 Controller
- Delete the libusbK driver and remove it from the DriverStore
- Then plug your PS3 Controller and reinstall the driver

**Comment by HelpMe1234** [comment]
So delete C:\Program Files\Nefarius Software Solutions\ScpToolkit\libusbK\amd64\libusbK.dll ?

**Comment by charlesmilette** [comment]
No. Not a good idea.
Use [DriverStore Explorer](https://driverstoreexplorer.codeplex.com/). Find "libusbK" in the list, check it and press "Delete package"  

But before doing that, you'll need to delete the device
With the controller unplugged, go in the Devices Manager:
![2016-03-29_12-39-21](https://cloud.githubusercontent.com/assets/6440374/14115932/504f44d4-f5ab-11e5-8ff6-6ac01d0e845f.png)
Then show hidden devices:
![egsg](http://thewindowsclub.thewindowsclubco.netdna-cdn.com/wp-content/uploads/2015/03/show-hidden-devices-windows-600x402.jpg)
A category named "libusbK devices" should appear. Expand it, and "PLAYSTATION (R) 3 CONTROLLER" should appear (or something equivalent). Right-click on it and press "Uninstall". Accept the prompt and __leave "Delete driver package" unchecked__. Then proceed with DriverStore Explorer

**Comment by HelpMe1234** [comment]
I have 3 different libusbK listed in Driverstore explorer, delete them all?

**Comment by charlesmilette** [comment]
Can I have a screenshot?

**Comment by HelpMe1234** [comment]
![image](https://cloud.githubusercontent.com/assets/18147142/14116602/8ad1569e-f5ae-11e5-9c9c-3dcbb5ba091a.png)

**Comment by charlesmilette** [comment]
Yes. Delete them all. Also think to remove the MotionInJoy driver (at the bottom). Can cause some conflicts

**Comment by HelpMe1234** [comment]
Ah I tried to delete everything from MotionJoy but it looked like I missed that. And now that I deleted all the libusbK drivers it no longer says "already using libusbk, installation aborted." in the log. But it still doesn't show any XBOX controllers. Also the log looks different. 
![image](https://cloud.githubusercontent.com/assets/18147142/14116878/02cfe0d8-f5b0-11e5-8a03-2106e5383659.png)

**Comment by HelpMe1234** [comment]
Just uninstalled and installed again and this is what I got 
![image](https://cloud.githubusercontent.com/assets/18147142/14116960/5ec94a8c-f5b0-11e5-8257-a8eed1bc4493.png)

**Comment by charlesmilette** [comment]
Now try to unplug and replug the controller.  

If it won't work, try to uninstall "PLAYSTATION (R) 3 Controller" from the HID devices in the Devices Manager (with the controller unplugged and hidden devices shown). This is the stock driver, that ... don't works. When you replug your controller, should recognize libusbK in the DriverStore and install it instead of the stock one.  

Will be offline for ~15 minutes. Don't expect an answer in this time lapse.

**Comment by charlesmilette** [comment]
The controller is under Human Interface Devices.
Try reinstalling only the driver with "Force Driver Installation" checked

**Comment by HelpMe1234** [comment]
Still nothing... 
![image](https://cloud.githubusercontent.com/assets/18147142/14120930/1181b7ec-f5c3-11e5-9d98-1a16bebfdfa5.png)

**Comment by charlesmilette** [comment]
I'm out of idea. What do you suggest, @nefarius ?

**Comment by nefarius** [comment]
*Composing ideas*

**Comment by HelpMe1234** [comment]
So in the log it said "Reboot Required". So, I restarted my computer and lo and behold... 
![image](https://cloud.githubusercontent.com/assets/18147142/14121305/da9afd2c-f5c4-11e5-8604-ecb9b75c5599.png)

Thanks so much for the help charlesmilette! Very much appreciated.

**Comment by nefarius** [comment]
*Aborting composing ideas* =D

**Comment by charlesmilette** [comment]
Don't forget to close the issue.
