### ISSUE TITLE
ScpToolkit Profile Manager not working on windows 10

### ISSUE THREAD

**Issue by sycoforbidden** [nefarius/ScpToolkit#252]
I was trying to get my controller to work with instant trigger (which i need help configuring, if someone could help as well), but the profile manager (ScpToolkit Profile Manager) keeps crashing when i execute it. The program says there's a log file but the logs folder is empty anyway.

Here is the debug tool's zip:

[ScpToolkit_Log-Package_CLIENTE_1459446673.zip](https://github.com/nefarius/ScpToolkit/files/198269/ScpToolkit_Log-Package_CLIENTE_1459446673.zip)

![scp toolkit](https://cloud.githubusercontent.com/assets/18195463/14185793/44c3456a-f773-11e5-81f4-18761b9ed8e4.gif)

**Comment by Wolf1030** [comment]
Same thing here.

**Comment by devondale16** [comment]
Same here, is there any fix to it yet?

**Comment by nefarius** [comment]
Thanks for the visual content, the profile manager currently isn't even alpha stage so no fix available yet.
