### ISSUE TITLE
Controller doesn't show in installer.

### ISSUE THREAD

**Issue by Devilicius** [nefarius/ScpToolkit#253]
On the little drop down to select the controllers to install; the controllers are non existent. Please help.
![untitled](https://cloud.githubusercontent.com/assets/18199823/14193502/5aac0a38-f773-11e5-87f9-6737f401aa5a.jpg)

**Comment by charlesmilette** [comment]
Have you tried to scroll?

**Comment by Devilicius** [comment]
Here's the debug report.
[ScpToolkit_Log-Package_Devilicius_1459486145.zip](https://github.com/nefarius/ScpToolkit/files/199009/ScpToolkit_Log-Package_Devilicius_1459486145.zip)

**Comment by charlesmilette** [comment]
The PID and VID given by your screenshot says you installed the Bluetooth driver on a Xbox 360 Controller.

**Comment by charlesmilette** [comment]
Do the controller works by USB, at least

**Comment by nefarius** [comment]
![](http://memesvault.com/wp-content/uploads/Lol-Meme-01.jpg)

You better start all over...

**Comment by Devilicius** [comment]
yea, had to restore and use previous working version of the installer. everything works now.

**Comment by nefarius** [comment]
Soooo, issue can be closed then?

**Comment by Devilicius** [comment]
yes

**Comment by nefarius** [comment]
Then do it please to keep things tidy here... I did it for you.
