### ISSUE TITLE
Directory Creation Error on Setup

### ISSUE THREAD

**Issue by npars** [nefarius/ScpToolkit#256]
I'm getting an error when trying to install on Windows 10 with all of the default settings. It appears to be attempting to create a directory that already exists, see image below. I did verify that the directory does exist.

![scp_error](https://cloud.githubusercontent.com/assets/1280422/14227021/41e5d98c-f8c9-11e5-983a-7ad6dbaf5309.PNG)

**Comment by Jan200101** [comment]
Try running it as a admin and tell if there is another error

**Comment by nefarius** [comment]
The setup should prompt for elevation automatically if needed. Do you have UAC disabled/on the lowest setting? This cause problems I'm aware of.

**Comment by npars** [comment]
This was due to a bad Windows 10 install
