### ISSUE TITLE
Wireless Not Working?

### ISSUE THREAD

**Issue by MuffinPirateX** [nefarius/ScpToolkit#257]
I selected all my controllers and my Bluetooth dongle at install, installed the drivers, but both my PS3 and PS4 controllers won't connect wirelessly and will still try to connect to the consoles.  Also this site is being dumb and won't let me send my zip file stating that it has to be a zip file... because logic.

**Comment by gergesh** [comment]
Joining on this issue here. Installed everything, have a genuine DS3 and an ASUS BT400, and installed the drivers for both. When I start up the server it says the dongle supports both DS3 and DS4, and that a genuine DS3 was detected.  Wired works just dandy, but as soon as I plug out the controller the status in ScpMonitor changes to 'Reserved', while The LEDs on the controller are still working. Pressing buttons doesn't work.

**Comment by Jan200101** [comment]
Its a problem with the service most of the time try running this tool made by me 
[Download](http://bit.ly/1N8ZtSC)

and in case you wanna be save I put the source code up on pastebin and put it in a antivirus search

[http://pastebin.com/raw/zR2CbsBM](Sourcecode)

**Comment by charlesmilette** [comment]
Maybe also #51

**Comment by Jan200101** [comment]
@charlesmilette my tools tries to fix it because its a simple error if the service not starting like it should

**Comment by charlesmilette** [comment]
#51 is something completely separated. The services detects the Bluetooth card, but can't handle it correctly, so any wireless communication is totally not working. Happens on the latest stable.

**Comment by gergesh** [comment]
@charlesmilette does it happen on the stable before that aswell? Can I just install that instead to fix the issue?

**Comment by Jan200101** [comment]
@charlesmilette 

> It's definitely an issue with the software as the the Bluetooth card is still picked up by the computer but the software no longer recognizes it appropriately. 

In the driver installer you have to pick what Bluetooth card / dongle you want to use so its either a faulty bluetooth card or someone who doesnt know how to work with computers

**Comment by charlesmilette** [comment]
@Jan200101 
Steps to reproduce #51:
1. Install the Bluetooth driver
2. Test the Bluetooth -- works
3. Restart
4. Test the Bluetooth --not working  


So,
> It's definitely an issue with the software as the the Bluetooth card is still picked up by the computer but the software no longer recognizes it appropriately.   

@gergesh I don't know. This issue seems more related to Windows 10 not doing stuff the same as 8 or 7.

**Comment by gergesh** [comment]
@charlesmilette not error #51 for me. It doesn't work even straight after the installation of the drivers. Guess it's a W10 thing. Probably not the best place to ask, but are there any good alternatives to this software? I have four controllers waiting to be paired.

**Comment by hermitmaster** [comment]
I'm having the same problem now... Bluetooth won't work at all. I get a code 10 on whatever Bluetooth device (dongle or built-in card) after installing drivers. I had a hell of a time getting the normal driver reinstalled and functioning afterwards. For the record, I originally installed in November and it worked fine until late February. One of the updates broke my setup.

**Comment by gergesh** [comment]
Well, I'm (as usual) dumb. My PS3 was apparently on in the living room, and it was interfering with the connection between the PC and the controller. As soon as I shut it down the controller managed to connect to the PC.

**Comment by Jan200101** [comment]
@charlesmilette there we go I am back from smashing my head against the table now back to you
It is not connecting to the controller because the service (the thing that the dongle needs to connect to the controller) is not starting like it should

**Comment by charlesmilette** [comment]
#48 
Simply start it from the service manager, or type `sc start Ds3Service` in a elevated command prompt. You could also make a shortcut to `sc start Ds3Service` and check "Run as administrator"
![capture](https://cloud.githubusercontent.com/assets/6440374/14717074/c5a0d2ce-07bd-11e6-9c0e-6e2e94aef45e.PNG)
PS: Best drawing skills ever

**Comment by Jan200101** [comment]
@charlesmilette good that you now know that it wasnt the guys bluetooth card

**Comment by mirh** [comment]
Try to put SCP service on "Late" start.
