### ISSUE TITLE
Setting up XInput wrapper for PS3 controller?

### ISSUE THREAD

**Issue by girlsim** [nefarius/ScpToolkit#259]
I'm sorry if this isn't the right place to ask this, but I couldn't find any instructions on it.
I am using a PS3 controller with MiJ drivers and Better DS3. I'm running Windows 7.
I'm trying to play a game which requires L2+R2 as an input, but this doesn't work with my setup since L2 and R2 are treated as opposite ends of the Z axis. Googling told me I need an XInput wrapper, and pointed me to this project.
I installed everything okay, but my controller still treats L2 and R2 as the Z axis. How do I fix this? If there are already instructions for this, can someone point me to them?
Thank you.

**Comment by nefarius** [comment]
First of all; are you a 100% sure you wiped all traces of MiJ before you migrated over? Since MiJ drivers spoof **a lot** of hardware IDs it may still interfere on your system.
