### ISSUE TITLE
PC Remote Play compatibility

### ISSUE THREAD

**Issue by julianxhokaxhiu** [nefarius/ScpToolkit#260]
Now that this layer is finally available directly from Sony, do you think your driver will conflict with this package? Should I uninstall it in order to get the Remote Play working, or can I just install it straightforward?

Thanks in advance for any reply :)

**Comment by Jan200101** [comment]
Remoteplay is like a game it sees your controller and uses it there will be no problems if the guys at sony arent dicks but I dont think they are since the presentation with the PCMR in it

**Comment by charlesmilette** [comment]
Probably won't work if RemotePlay takes only PS4 controller, since the libusbK driver does not expose the control outputs. But if it supports Xinput, it will work out of the box.

**Comment by nefarius** [comment]
I don't have the slightest idea how PC Remote Play will work but if it expects the DS4 to be connected via standard hidusb.sys, then no, they won't happily co-exist I'm afraid.

**Comment by Jan200101** [comment]
It worked back on the PS3 it just had no use because it was just a feature forgotten

**Comment by julianxhokaxhiu** [comment]
Thank you for the replies guys! I didn't though I would get so many honestly ahah

Unfortunately I didn't had the chance to try it yesterday, but I'll keep you posted maybe today evening/tomorrow maximum about it.

Anyway I was asking this question honestly because I'm using this driver for emulation purposes and it's working awesome, and I don't really like to switch between the two continuously...I hope that maybe one day @nefarius you'll find a way to workaround it in case it's conflicting. In case it's not better this way and this issue could be closed straightforward :D Thanks in advance to anyone!

**Comment by mirh** [comment]
Considering it doesn't even support [W7](http://www.kotaku.com.au/2016/04/ps4s-remote-play-doesnt-support-windows-7/), I'm guessing they decided to go full MS-Vision with APIs and all.

**Comment by secondfry** [comment]
It doesn't work with PS4 Remote Play as it's using different driver than expected by Remote Play app.

**Comment by mirh** [comment]
Perhaps it's just a simple name check. 
I'd try to change that with x360ce.

**Comment by Jan200101** [comment]
by the way @mirh it can work on every OS [_*Cough*_](http://www.tech-recipes.com/rx/7225/playstation-3-use-remote-play-on-any-non-sony-vaio-windows-7-pc-ps3-firmware-3-30/)

**Comment by mirh** [comment]
I didn't know there was an official remote play program for PS3 too, thanks. 
We were talking of ps4 one here though.

**Comment by charlesmilette** [comment]
Remote Play for PS3 doesn't support controllers.

**Comment by Jan200101** [comment]
@mirh sadly the PS4 one only supports

- Windows 8.1
-Windows 10 or later
-OS X 10.10
-OS X 10.11

@charlesmilette 
It has no use anyway

**Comment by Mahir007** [comment]
Remote play doesn't install or use any custom drivers as far as I know, at least it didn't install one, it simply said plug in DS4, I did and it worked just like that, but if you install SCP driver the DS4 doesn't work in remote play, even if you stop the service.

**Comment by charlesmilette** [comment]
The thing that may make it work would be using the virtual bus to recreate a normal PS4 controller, and then install the regular Windows driver on it.

**Comment by mirh** [comment]
I don't think you need anything that fancy. 
Though, I wonder if you couldn't have the DirectInput device (because that's what vanilla DS4 uses) expose the real thing. 
Ideally it shouldn't compromise XInput and 360 emulation.

**Comment by nefarius** [comment]
**Update:** when [ViGEm](../../ViGEm) is finished this will be possible!

**Comment by julianxhokaxhiu** [comment]
What's the current status? :D

**Comment by julianxhokaxhiu** [comment]
@nefarius any update on this?

**Comment by nefarius** [comment]
@julianxhokaxhiu It's already working perfectly with ViGEm & VDX.

**Comment by julianxhokaxhiu** [comment]
Thank you very much :)
