### ISSUE TITLE
Issues using controller wirelessly?

### ISSUE THREAD

**Issue by squack** [nefarius/ScpToolkit#262]
I have a genuine DS4 and it works fine (to an extent) when wired. The second i disconnect it to try and use it wirelessly SCP monitor shows it as "reserved" and the backlight turns into a bright grey color. At that point it stops working completely until I reconnect the controller. I also get a notification saying that SCP found a wireless controller but doesn't do anything about it?

**Comment by Jan200101** [comment]
Its a problem many users have and its easy to fix (if you now a how to get into the deep stuff) but I kept you from that trouble and made this pile of code yay.
hope it fixes your problem (which it did in most other cases)

[My Fix](https://onedrive.live.com/redir?resid=531AF8D5D12A8FC8!2755&authkey=!AEphx3qq60WTNHs&ithint=file%2czip)

**Comment by remivamp** [comment]
@Jan200101 All that is in that .zip file is a README.txt

**Comment by konsumer** [comment]
Yeh, love to have a look at your solution.

**Comment by Jan200101** [comment]
Just  noticed my mistake sorry for not responding I forgot my password I am working on a system that tries to check if it running at startup so I am going to make a new one and compile it
