### ISSUE TITLE
Fake PS3 Controllers don't work wirelessly

### ISSUE THREAD

**Issue by lilyesx6** [nefarius/ScpToolkit#268]

**Comment by Jan200101** [comment]
Yeah we cant really do much if you just give us that info

**Comment by lilyesx6** [comment]
Well , I bought a fake PS3 controller to use in PC gaming Till now I got to work but only using the wire and the SCPtoolkit recognise it as fake and I couldn't get to work wirelessly, thanks

**Comment by nefarius** [comment]
Fake controllers currently not supported on a stable basis.

**Comment by lilyesx6** [comment]
Thank you sir for your support, I hope you find a stable solution for it.
