### ISSUE TITLE
Massive FPS Drops When Using PS3 Controller

### ISSUE THREAD

**Issue by killa4000** [nefarius/ScpToolkit#271]
Even having the PS3 controller plugged in without the service running causes lag. 
When I rotate the analog stick, it lags my entire computer but only when I'm in a game.
I have no idea what caused this.
It also slows down to the point where the computer starts beeping.
[ScpToolkit_Log-Package_phant_1460829780.zip](https://github.com/nefarius/ScpToolkit/files/222478/ScpToolkit_Log-Package_phant_1460829780.zip)
PS3 controller also maxes out Hard Disk usage for some reason.

**Comment by psyke83** [comment]
It's a bug in recent preview builds of Windows 10 related to the Xbox 360 driver, not ScpToolkit. Until it's fixed properly, you can workaround the problem:

* Plug in the controller
* Open Device Manager and click on "Xbox 360 Controller Driver for Windows"
* Click Driver tab -> Update driver -> Browse my computer for driver software -> Let me pick from a list of device drivers on this computer -> Show all devices, and install driver version 2.1.0.1349 [13/08/2009].

**Comment by killa4000** [comment]
Yep that fixed it. Thanks!

**Comment by psyke83** [comment]
There should be a "Close issue" or "Close and comment" right below the box where you type your reply (that I'm typing in right now).

**Comment by killa4000** [comment]
Thanks!
