### ISSUE TITLE
Mouse becomes disabled when installing Dualshock 3 

### ISSUE THREAD

**Issue by MisterJer** [nefarius/ScpToolkit#278]
Luckily I can type this on my phone. I installed the driver only for the Dualshock 3 on my PlayStation 3 controller and it seems the controller works fine but it disables my mouse even after restarting the computer,  so what do I do now?

**Comment by charlesmilette** [comment]
Did your mouse used Bluetooth?

**Comment by MisterJer** [comment]
It has capability but is also a wired mouse which is how I always use it (Logitech G700)

**Comment by nefarius** [comment]
What version are you using?
