### ISSUE TITLE
Software causes in game lag spikes on Windows 10

### ISSUE THREAD

**Issue by eWasteman** [nefarius/ScpToolkit#279]
Have an issue whereby whenever my DS3 controller is paired with the software I get brief but frequent network lag spikes while in any game. I can see my ping shoots up in the scoreboard menu at the time of the lag spike.

As soon as I unpair the controller, the lag spikes stop. I'm on a ~40mb wireless connection. I know that being cabled would be better but it's not an option.

Windows 10 64 bit / i5 / ati 7950 / 8GB ram / GA-Z77X-UD5H-WB WIFI.

Happy to donate a few £'s to the cause if this gets resolved/working. Please don't make me go back to Motioninjoy :(

**Comment by psyke83** [comment]
Are you on a preview build of Windows 10? If yes, it could be this:

https://github.com/nefarius/ScpToolkit/issues/271

The latest Fast ring build (14328) has the issue fixed, otherwise you can apply the workaround I listed.
