### ISSUE TITLE
SCP DSx Servive Could not be installed

### ISSUE THREAD

**Issue by Setiadii** [nefarius/ScpToolkit#280]
Why when im install this aplication, showed massage like this?
What happen with this aplication?
Can you help me?
Thank you.

![snap2](https://cloud.githubusercontent.com/assets/18630536/14761889/d472d9f2-0996-11e6-8b9e-dc16f39a3a05.png)

**Comment by nefarius** [comment]
UAC is enabled? Still happening after reboot?

**Comment by Setiadii** [comment]
Yes. It still happening after im reboot my notebook.
And it happened after im re-download this app to.
What happen about this app?
Please help me.
Because im very love this app.
Thankyou

**Comment by Setiadii** [comment]
Can you fix this problem?

**Comment by nefarius** [comment]
Have you tried to explicitly run the setup as Administrator?

**Comment by Setiadii** [comment]
Yes.
I have do that.
But it still not work.

![snap3](https://cloud.githubusercontent.com/assets/18630536/14772226/ee41fb9e-0ac5-11e6-9abb-2607ac7c1736.png)

![snap4](https://cloud.githubusercontent.com/assets/18630536/14772228/f6fee580-0ac5-11e6-85c8-4286ef3502c5.png)

What should I do?
