### ISSUE TITLE
USB extension cord not allowing controller to be recognized

### ISSUE THREAD

**Issue by zj44** [nefarius/ScpToolkit#281]
Hi,

I used an older version (pre-Nefarius) of the DS3 tool and it would work fine when I had my PS3 controller connected through my USB extension cord. I reinstalled my computer recently and while it does appear in my device manager when I have my PS3 controller connected with the extension cable, ScpToolkit doesn't acknowledge it. I could use it by plugging it directly into my computer but I'd like to use the controller across the room and the extension cable is the right length for it.

Thanks

UPDATE: I was able to fix it by plugging the extension cord into a non-3.0 port. It's awfully inconvenient to reach, though

**Comment by Techman-** [comment]
If your issue is solved, go ahead and mark it as closed.

**Comment by zj44** [comment]
I wanted to leave it open in case extension cords with PS3 controllers not working in USB 3.0 ports are something that need to be looked into

**Comment by nefarius** [comment]
Nothing I could change about this since propper connectivity has to be assured by the operating system.
