### ISSUE TITLE
Can't use DS4 with PC Remote Play.

### ISSUE THREAD

**Issue by Mahir007** [nefarius/ScpToolkit#282]
Recently I installed the latest stable build of SCP Toolkit (the one released in January), did the default install options, installed just the DS4 driver and the windows service (didn't install the bluetooth driver), worked perfectly with no problems whatsoever, that was until recently when I installed the Remote Play client that Sony released, it just doesn't work with remote play, even if I completely stop the SCP DSx Service with the command prompt that doesn't make a difference.
Is there any way that I can keep the SCP driver installed and use remote play at the same time, so that when I'm playing PC games I can use the DS4 as normal and when I want to use Remote play I can do that as well without having to uninstall the driver.

**Comment by charlesmilette** [comment]
#260

**Comment by nefarius** [comment]
There is no way around manually changing the device driver if you want to accomplish this.
