### ISSUE TITLE
add support for Dual PSX-USB Adaptor

### ISSUE THREAD

**Issue by eadmaster** [nefarius/ScpToolkit#283]
This USB adapter [is not compatible with the generic Windows 7 driver, while it was working fine with Windows XP](http://www.sevenforums.com/drivers/164080-dual-psx-usb-adaptor-not-properly-recognised.html).
I attach the ScpToolkitDebugger-generated files:

[HID-Devices.txt](https://github.com/nefarius/ScpToolkit/files/233711/HID-Devices.txt)
[system.txt](https://github.com/nefarius/ScpToolkit/files/233712/system.txt)
[USB-Devices.txt](https://github.com/nefarius/ScpToolkit/files/233713/USB-Devices.txt)

**Comment by charlesmilette** [comment]
Take the driver from WinXP and try it on 7, maybe.
