### ISSUE TITLE
Dell Built-in Bluetooth

### ISSUE THREAD

**Issue by remivamp** [nefarius/ScpToolkit#284]
This is the first time ive ever had bluetooth on a computer that the company actually PUT THE BLUETOOTH IN! (looking at you asus) Anyway I'm trying to connect my Genuine PS3 controller to my computer via bluetooth since usb is really finicky. Anyway the controller works fine over usb on my windows 10 Dell Inspiron 14-3452 in order to play minecraft properly. But the bluetooth Dell Wireless 1801 Bluetooth 4.0 LE when I override the drivers shows up as Bluetooth Radio and under usb devices yet I can still see its mac address on scp monitor

EDIT: USB\VID_0BDA&PID_B739&REV_0200
is my hardware ID

**Comment by nefarius** [comment]
Which software version are you running?

**Comment by remivamp** [comment]
first tried latest stable. Wiped then tried lated prerelease. Then tried the one from scarlet crush. BT works fine on everything except scptoolkit.

**Comment by remivamp** [comment]
By works fine i mean when its using oem drivers

**Comment by charlesmilette** [comment]
Normal. They were _conceived_ for that. The Scp Bluetooth driver is generic. Thus, it cannot take in account all existing hardware only like `*poof*`. Some changes in the code is probably required.

**Comment by mirh** [comment]
#380
