### ISSUE TITLE
Can't get Bluetooth to work (USB works just fine)

### ISSUE THREAD

**Issue by redeven** [nefarius/ScpToolkit#285]
Hey! I've been unable to get my PS3 controller to work wirelessly so far.
According to the original XInput Wrapper thread, my Bluetooth dongle should be compatible (USB\VID_0A12&PID_0001) and according to the github page, my controller is compatible too (USB\VID_054C&PID_0268) but the program says it's a fake DS3 controller.
I was able to make it work while USB-connected, but I can't use it with Bluetooth. 
Whenever I attempt to connect wirelessly, it'll just show these notifications https://imgur.com/NwTRR4r

**Comment by machstem** [comment]
Did you end up getting it to work?  I have a similar issue where it detects it as compatible but only works by USB

**Comment by redeven** [comment]
Not at all. There was an unofficial ScpControl.dll that someone made, for a beta version that I couldn't get it to work, and I got no other answers, so... that.

**Comment by mirh** [comment]
Similar symptoms as #299?
