### ISSUE TITLE
DS3 controller is being picked up but..

### ISSUE THREAD

**Issue by dragoicath** [nefarius/ScpToolkit#286]
while the input tester picks everything up it isnt being treated as an xbox 360 controller and wont work on any games
![screenshot 2](https://cloud.githubusercontent.com/assets/18334226/14836493/294c2fb4-0bd6-11e6-8fc9-543c1f960656.png)

**Comment by acme420** [comment]
same issue as me, the xbox drivers (scpvirtual bus)didn't install. the temporary fix is to reboot, press F8, and boot without driver signing then reinstall the drivers. you'll have to do this every reboot.

**Comment by charlesmilette** [comment]
Or in admin cmd:
`bcdedit /set loadoptions DDISABLE_INTEGRITY_CHECKS`
DDISABLE is not a typo.

**Comment by dragoicath** [comment]
@charlesmilette do i need to try to reinstall the drivers after doing that?

**Comment by charlesmilette** [comment]
That's the best part of it: Nope! Just reboot.  
It will only work if the solution proposed by @acme420 worked. It is just a permanent way to apply it, instead than having to do his solution at each reboot. So I suggest you try @acme420's solution before, and if it worked, proceed with the command.  
If not, I can't assist you any furter than: try reinstalling the driver after a [manual removal](https://github.com/nefarius/ScpToolkit/wiki/Manual-driver-removal)

**Comment by dragoicath** [comment]
welp ive completely removed everything and tried to reinstall, no change if anyone else has any ideas theyd be appriciated

**Comment by acme420** [comment]
try installing this update and reboot. if you don't already have it installed. it worked for my issues of drivers not being recognized as signed. https://www.microsoft.com/en-us/download/details.aspx?id=46148
