### ISSUE TITLE
"Genuine DualShock 3 found" but wouldn't connect

### ISSUE THREAD

**Issue by firezz1** [nefarius/ScpToolkit#287]
hi guys!
I'm having some issues regarding the bluetooth connection for dualshock 3.
I've installed the SCPtoolkit and the drivers for dualshock 3, xbox, and bluetooth. Everything is working perfectly fine, but then everytime i restart or wake up a computer from sleep the bluetooth wont work anymore, when i press the ps button there's a notification saying "Genuine Dualshock 3 found" and the light just keep blinking.. I need to reinstall the bluetooth driver for it to work again.
What might be causing this problem?

**Comment by acme420** [comment]
open the settings manager and see if under service settings you have always unplug virtual controller checked. if so uncheck it and unplug/plug your controller on usb again. then try and unplug it and see if it works. if not try turning off the controller first. hold l1+r1 and ps button till it goes off then unplug/plug it back in and unplug it again to see if it works on bluetooth now.

also might want to try reserving the slot in the service settings last option.

**Comment by firezz1** [comment]
i've checked the setting and the "always virtual controller" is unticked, for the reserving slot i already tried that and the result is still the same..
but!
yesterday i found something interesting, when i press the ps button just after it turned off because idle i found this

![unntitled](https://cloud.githubusercontent.com/assets/18704768/14874962/d804c6ce-0d2f-11e6-8a07-62fe1ae1adbc.png)

did you know what that means?
