### ISSUE TITLE
BSOD when driver verify is enabled

### ISSUE THREAD

**Issue by mirh** [nefarius/ScpToolkit#29]
Tell [verifier](https://support.microsoft.com/en-us/kb/244617) to monitor the driver and you won't be able to boot again in Windows (or at least in my 7x64). 

Page heap may [[?](http://gtaforums.com/topic/562765-ginput/page-44#entry1068166338)] be involved.

**Comment by aLagoG** [comment]
I've been having the same problem.
This is the message that I get after memory dump analizis.

    DRIVER_VERIFIER_IOMANAGER_VIOLATION (c9)
    The IO manager has caught a misbehaving driver.
    Arguments:
    Arg1: 000000000000021f, A driver has not filled out a dispatch routine for a required IRP major function.
    Arg2: fffff800e247b174, The address in the driver's code where the error was detected.
    Arg3: ffffcf8147d54dc0, IRP address.
    Arg4: 0000000000000000

With faulting ip: `ScpVBus+b174`

Hope this helps you find the problem

**Comment by nefarius** [comment]
Well, don't run the verifier then :P I don't have a fix for this yet.

**Comment by nefarius** [comment]
Ok somehow my run of the verifier doesn't create a dump file >_<

**Comment by mirh** [comment]
[?](https://www.sophos.com/en-us/support/knowledgebase/111474.aspx)

**Comment by nefarius** [comment]
@mirh yeah, I know right =P But no matter what switch I flip; none of my virtual machines (Win7/8/10) create a f***in' memory dump! I sincerely don't know what I'm doing wrong...

**Comment by nefarius** [comment]
Trying one more time with `Complete memory dump` enabled...

**Comment by mirh** [comment]
**[?](http://support.kaspersky.com/3054)**

**Comment by nefarius** [comment]
**I. FIXED. IT.** !

![image](https://cloud.githubusercontent.com/assets/286631/13927310/935b32a8-ef91-11e5-9033-565b61603e86.png)

**Comment by charlesmilette** [comment]
![chuck norris approves](http://i.memeful.com/media/post/Wdnj5Vd_700wa_0.gif)
