### ISSUE TITLE
Unable to select and edit different sections in the Profiler

### ISSUE THREAD

**Issue by Encryption767** [nefarius/ScpToolkit#292]
The different sections in the Profiler can not be opened for me. 
Everything in "Button mappings" works fine and the profile works for my controller if I leave the profiler window open but none of the other sections can be viewed and so I am unable to map my axis to WASD.

Windows 10 x64.

**Comment by RitzyBusiness** [comment]
Same here~ nothing in the profiler seems to be working.  Running the latest beta software~

**Comment by AppleJewsy** [comment]
I can't get the profiler to work at all. Changing the mapping doesn't actually do anything, tested with MGSV and the input tester. Also swapping doesn't work inside of the profiler (switching the mapping for buttons x and y assigns y to act as x while x refers to y in a way that makes it still act as x, so I guess it doesn't refer to the actual button but rather its function)
