### ISSUE TITLE
New BT Dongle support?

### ISSUE THREAD

**Issue by Sorlic** [nefarius/ScpToolkit#296]
I was wondering if you could add support for a different dongle, in a next patch? Specifically Accel Bluetooth device USB\VID_1CAA&PID_0001 (also known as BlueSoleil Generic Bluetooth Device).

If you need anything else, please let me know. I'm kinda new to this too, by the way, but I'll try to find and provide any additional data you might require.

Kind regards,
--Sven

**Comment by mirh** [comment]
#380
