### ISSUE TITLE
Controller not being recognized by bluetooth on Windows Insider build 14332

### ISSUE THREAD

**Issue by farebord** [nefarius/ScpToolkit#301]
As the title said, so after I applied to Windows Insider, DS3 just stopped being recognized and the 4 lights go on and off forever. If I connect them via USB, they are recognized.

**Comment by charlesmilette** [comment]
Are you sure the ScpToolkit driver is installed? Maybe the Insider build update reinstalled the original one.

**Comment by farebord** [comment]
I didn't reinstall the drivers after the Insider build update. I'll try that and tell you. Thanks for the reply.

**Comment by farebord** [comment]
@charlesmilette answer works! Thanks!
