### ISSUE TITLE
Controller remains "Reserved" and takes over a real x360 controller.

### ISSUE THREAD

**Issue by Gamartto** [nefarius/ScpToolkit#303]
Hi,

I used to use the old version but now I have updated to this one... The issue I´m having is that after installing the new version and setting up a BT dongle and a PS3 controller, the original wired X360 controller I had gets recognized as a secondary controller and the PS3 controller as the main controller even after issuing the L1+R1+PS button to disconnect the ps3 controller (the scp monitor legacy shows the ps3 controller as reserved).

Is there a way to make the X360 controller the main controller at all times and the extra ps3 controllers secondary controllers? How can I disconnect a ps3 controller for good?

Thanks.

Edit: I'm using Win8.1x64

**Comment by sheldon25** [comment]
Open up the scp monitor.  Next to the pad one, pad two option there is a little arrow. click on that and it will move the reserved option around to rearrange the controllers.
