### ISSUE TITLE
Error causing SCPtoolkit to not recognize controller

### ISSUE THREAD

**Issue by gotmilk0112** [nefarius/ScpToolkit#304]
SCPToolkit has worked fine with my DS3 for the longest time now, but for some reason, it has stopped detecting the controller when I plug it in, and I have to run the "server" program in order for it to detect.

When I run the server program, the tray notifications properly pop up, but one of them is an error:

"Couldn't plug in virtual device 1: System.ComponentModel.Win32Exception (0x80004005): The parameter is incorrect"

The controller works, but it only works when the server program is running. As soon as I close it, the controller stops working.

What's going on?

**Comment by johnmatricks** [comment]
Having this exact issue. Anyone know a fix?

**Comment by gotmilk0112** [comment]
I just ran the "Driver Installer" and reinstalled the drivers. That seemed to fix it.

**Comment by johnmatricks** [comment]
tried that as well as restarting and doing that again. Did not fix it.

**Comment by johnmatricks** [comment]
actually, it did. Had to restart while it was still installed, thanks
