### ISSUE TITLE
Driver toolkit with C++

### ISSUE THREAD

**Issue by fqlx** [nefarius/ScpToolkit#305]
Could someone point me in the right direction on how to build an application in C++ with the driver toolkit?  Any code snippets on interfacing and sending emulated X360 control inputs?

**Comment by Jan200101** [comment]
Isnt this the wrong place to ask for this ?

**Comment by juryben** [comment]
@Jan200101 Yes, but there's no documentation.  I want to emulate Xinput or DirectInput using this API.

**Comment by nefarius** [comment]
@fqlx if you "just" need XInput support you'd rather want to check out the [actual emulation driver](../../ScpVBus) or even better its [successor](../../ViGEm).
