### ISSUE TITLE
Controller not reacting, but pairing works

### ISSUE THREAD

**Issue by MisterFab1an** [nefarius/ScpToolkit#310]
I have a [3rd party controller](http://www.gioteck.com/controllers/sc-1/) and it connects when I install the drivers for DS4.
It will work for like 5 seconds and then freezes.
Debug is in the attachements!

[USB Controller_hid-report.dump.txt](https://github.com/nefarius/ScpToolkit/files/275632/USB.Controller_hid-report.dump.txt)
[ScpToolkit_Log-Package_MisterFab1an_1463792324.zip](https://github.com/nefarius/ScpToolkit/files/275633/ScpToolkit_Log-Package_MisterFab1an_1463792324.zip)

**Comment by Jan200101** [comment]
> when I install the drivers for DS4.


Your controller  ( look at the [website](http://www.gioteck.com/controllers/sc-1/) you linked)
>  COMPATIBILITY
>Playstation 3

**Comment by MisterFab1an** [comment]
I tried to install them for DS3 but they don't work with my controller. The toolkit will crash.
So I tried with DS4 and it works for so said 5 seconds but then freezes.
