### ISSUE TITLE
An Unhandled exception occurred: System.NullReferenceException...

### ISSUE THREAD

**Issue by mannylouey2013** [nefarius/ScpToolkit#316]
Hi there. Firstly, I want to say thanks for writing and developing this new SCP toolkit. When it works (which is most the time) it is amazing. It feels great to just pick up my DS4, hit the PS button and instantly have it connect and be able to play. So thank you.

Here is my error message. I am unable to use my DS3 or DS4. I always  get an error like this.
The controller itself physically lights up, but has no response. SCP Monitor's "check input" option is greyed out, and the monitor itself shows the controller address as 0::0 lol.

I've attached both the debug tool output and the screenshot my error messages. Any help would be greatly appreciated. 

(Sweets is my computer's account name, DigitalBuddy is my PC name).
I'm running 64bit Windows 7. Let me know if there's anyhting else you need to know.
![error](https://cloud.githubusercontent.com/assets/19567955/15539221/8b4ab9ec-22c4-11e6-8dbd-da64e2606725.png)
[ScpToolkit_Log-Package_Sweets_1464164540.zip](https://github.com/nefarius/ScpToolkit/files/281882/ScpToolkit_Log-Package_Sweets_1464164540.zip)

**Comment by johnmatricks** [comment]
Ive had the issue on the right, not the issue on the left, would appreciate any info as well

**Comment by johnmatricks** [comment]
nevermind, just restarted and it fixed

**Comment by mannylouey2013** [comment]
To anyone else with this issue, I solved it by completely uninstalling and reinstalling SCP toolkit. I deleted everything that was left in the SCP toolkit installation folder too.

Not sure what happened, but it works now. Good luck to anyone else with a problem and remember, if your controller keeps blinking without connecting, you can use a pin to press a reset button on the bottom of it. it's there for both DS3 and DS4.
