### ISSUE TITLE
Doesn't work with standard sixaxis controller

### ISSUE THREAD

**Issue by ph0rn** [nefarius/ScpToolkit#317]
I have 2 DS3's that work great, but it doesn't detect the sixaxis controller at all. Does this only support DualShocks?

edit: I see that only DS3/4 is listed in the compatibility list. Can sixaxis controllers be supported?

**Comment by charlesmilette** [comment]
I have 2 SixAxis controllers, and they work fine.

**Comment by ph0rn** [comment]
Strange. Did you only need to install the DS3 driver for the sixaxis to work? Or did you need to select a device that wasn't showing up as DualShock or anything?

**Comment by ph0rn** [comment]
Ugh ok.. it's suddenly working now
