### ISSUE TITLE
Xbox emulation support bug

### ISSUE THREAD

**Issue by ELAD3356P** [nefarius/ScpToolkit#320]
There are some games that doesn't support the xinput emulation:batman arkham knight, life is strange, fifa 15,etc  but does support the xbox one controller .

I'm using windows 10 version 1511 latest updates and a ds4 controller wired.
 Any fix?

**Comment by charlesmilette** [comment]
Have you tried with a Xbox 360 controller? Because Scp emulates Xbox 360, not Xbox One.

**Comment by ELAD3356P** [comment]
Xbox one and 360 works almost the same on xinput in windows 10

But it's not the problem, i said that the ds4 controller is doing problems

The xone works great in those games.

But those games don't  recognize the 'fake' xbox 360 controller . 

You with so far?

**Comment by giorgosp** [comment]
Any news about this? Controller is not recognized by Fifa for example but it is recognized by Far Cry 4

**Comment by giorgosp** [comment]
I guess Fifa and similar games don't "want" xinput but directinput? I don't know about drivers, however I installed x360ce as well and now Fifa is fine :)
