### ISSUE TITLE
Keyboard driver forced

### ISSUE THREAD

**Issue by jskylar** [nefarius/ScpToolkit#322]
When I install the Dualshock 3 driver for my PS3 controller, the keyboard driver is installed against my own doing. I'm sure I haven't accidentally checked it, and I'm not installing Bluetooth/DS4/Force Drivers. I'm using a laptop with an internal keyboard and trackpad and while the keyboard becomes disabled, the trackpad continues working even though they appear to be tied together in the Device Manager. I tried rolling back the drivers and after resetting the PC, it continues to not work. I've used the clean wipe utility and both the keyboard and trackpad work. And when I try it again the keyboard again disables. I don't know what I could be doing wrong or why the installer recognizes my keyboard as part of the PS3 controller driver.

EDIT: And after resetting, the installer began installing a driver that override use of the trackpad nulling both the trackpad and keyboard.

EDIT #2: I just tested SCP on my Windows 10 desktop (which uses a wireless keyboard + mouse) and it works perfectly. I don't know why my laptop would have an issue, if it makes a difference it's a Macbook Air running Windows 8.1 Pro on bootcamp.

**Comment by PoopnButts** [comment]
I have a similar issue, except it's overriding my USB wireless mouse on my Win 8.1 desktop (wireless mouse + wired keyboard).  Even less helpfully, when it claims to be done installing my DualShock 3 still doesn't work :\
