### ISSUE TITLE
Make it act like an mouse ?

### ISSUE THREAD

**Issue by d3xt3r01** [nefarius/ScpToolkit#323]
1st things first, Awesome piece of work !!!!
Now to the funny business:

Is there a way to make it act like a mouse ? Not in the traditional sense ! I'd imagine trying to use it on slither.io ( online game ).
I don't think it would require much... Having a circle with the center of the joysting being the center of the screen and the mouse would be in whichever position the joystick is in ( given the radius of the circle can be defined .. no need for it to go crazy all over the place ).

While at this question .. even if using it completely as a mouse .. I'd imagine mapping buttons to various keys would be doable ..

Thanks in advance.

**Comment by charlesmilette** [comment]
[JoyToKey](http://joytokey.net/en/) can bind controller buttons to keyboard buttons or mouse movements.

**Comment by d3xt3r01** [comment]
Yeah, I guess that would work .. Thanks.
