### ISSUE TITLE
Installer throws NullReferenceException

### ISSUE THREAD

**Issue by WZ-Task** [nefarius/ScpToolkit#339]
PS3 controller isn't working, and I've seen issues on driver install so I'm assuming that's the problem.
Windows 10, skipping the Bluetooth.

Sometimes the installer hangs indefinitely on the "Installing drivers, this could take a couple minutes" step, the rest of the time it throws a null reference exception.

I've attached both a screenshot of the specific issue, as well as a generated debug log.

[ScpToolkit_Log-Package_Task_1466431176.zip](https://github.com/nefarius/ScpToolkit/files/323574/ScpToolkit_Log-Package_Task_1466431176.zip)
![scp-nullref](https://cloud.githubusercontent.com/assets/12087894/16197198/200bffdc-36cf-11e6-9fb7-4c97643e6e42.jpg)

Hope that helps!
J

**Comment by ASB2** [comment]
I have the same problem. Im running windowns 10 as well.

**Comment by LoneEch** [comment]
I get the same notification when I'm installing the DS3 drivers in Windows 7, too.
