### ISSUE TITLE
BT Drivers issues in Win10

### ISSUE THREAD

**Issue by hige-agusd** [nefarius/ScpToolkit#342]
I can connect via USB with no problem.
When I install BT drivers for my Intel(R) Wireless Bluetooth(R) (VID:8087, PID:0A2A), nothing happens.
One I reboot, my controller connects via BT, but I can't use the BT device to connect to anything else (and won't appear under my Devices and printers, as if I didn't have Bluetooth)

Do you need any more info?

**Comment by charlesmilette** [comment]
That behavior is normal. That is why it is recommended to have a dedicated Bluetooth dongle for the controllers.

**Comment by zelmon64** [comment]
@hige-agusd Which controller are you using? If it's a DS4 I was happily surprised to find that it works natively (more or less) meaning that you don't have to slave a BT adapter to it.

**Comment by hige-agusd** [comment]
Unfortunately, I have a DS3
It seems I'll have to get a dongle
Thanks for the replies, guys!

**Comment by pacoesni** [comment]
I'm maving the same problem, even if I use two Bluetooth devices. My bluetooth-in devices take the driver from scp and use it, even if I select just install drivers for the external dongle.
