### ISSUE TITLE
Xinput Wrapper not working(?)

### ISSUE THREAD

**Issue by dragonicath** [nefarius/ScpToolkit#344]
ok so i have connected to controller, the inputs are being picked up i have installed all the necessary stuff and it picks up the controller and the inputs, but it will not change them into Xinputs also will not let me upload the debug info archive for some reason,saying its not a .zip
EDIT: heres a mediafire link to the debug info it wont let me post http://www.mediafire.com/download/9vl7wdc3b1x7wws/Debug+info.zip

**Comment by nefarius** [comment]
Have you tried the latest beta too?
