### ISSUE TITLE
XBOX 360 controller driver failed to install

### ISSUE THREAD

**Issue by Madeiner** [nefarius/ScpToolkit#345]
Hi there.
I used this program to great effect a few months ago on my PC.
Now i'm trying using it on a different pc, but it doesn't work as expected.

As soon as i install the "XBOX 360 controller driver" from this software, windows tries to reach for windows update and update the driver. It fails (even if i cancel) and i'm left with a PS3 controller in device manager, and a nonfunctioning XBOX 360 controller with a yellow mark. Nothing shows up in usb game controllers window.

I've tried installing and reinstalling, even with forced installation. Also tried SCP wipe utility, enabling support for unsigned drivers, or manually installing drivers as other posts indicated. I even disabled windows automatic driver installation. Still no luck.
Any help?

These are the logs file. Can't upload here for some reason.
https://mega.nz/#!NRRz0RKR!CEqR_BXqq91gxWCqOsi-UaQ-UckiZZoNo1TnIxoZ66Y

The controller is working and i can see input in the tester.
Device management shows a yellow-marked X360 controller under (roughly translated into english) "Common microsoft class controllers"

Device details says these are the drivers it's using:
..\system32\drivers\xusb21.sys
..\system32\WdfCoInstaller01009.dll

Edit: Finally managed to solve it. Windows was considered not genuine due to a bug, and wasn't able to succesfully download the x360 driver from windows update

**Comment by Dienfive** [comment]
Hello Madeiner,

Do you know how to fix this issue? as i have same issue but dont know how to fix it:(

**Comment by Madeiner** [comment]
Hello,

it's been a while but i can try to help you.

If you have any software related to the joystick, try to uninstall it and
run a driver cleaner.
Then download this one:

http://forums.pcsx2.net/Thread-ScpToolkit-XInput-Wrapper-aka-ScpServer-Reloaded

It's different from the one i was using at the time (even if very similar),
and worked flawlessy multiple times on different computers.

2017-07-22 11:03 GMT+02:00 Dienfive <notifications@github.com>:
