### ISSUE TITLE
I cant pair using Bluetooth in my pc

### ISSUE THREAD

**Issue by GiaN7** [nefarius/ScpToolkit#347]
I cant pair my DS3 with bluetooth in my pc 
with usb its worked perfectly
this is log of debug https://www.dropbox.com/s/vaxjier8h61ztb5/ScpToolkit_Log-Package_Wahyu%20Ivdal%20Saputra_1466906399.zip?dl=0
i cant upload in here bcoz always said cant support this file type

**Comment by Jan200101** [comment]
First #356 

Second #51
