### ISSUE TITLE
SCP needs to be reinstalled after each computer restart

### ISSUE THREAD

**Issue by Iking47** [nefarius/ScpToolkit#349]
SCP works fine but it doesn't work each time after I boot up my PC (Windows 10)  and thus needs to be reinstalled. It doesn't take long to reinstall it but isn't it supposed to run from Windows boot?

The SCP DSx Service is still checked in msconfig under services and SCP Toolkit Tray Notifications are enabled in the startup list.

**Comment by keithomalley** [comment]
I get this error as well, using a bluetooth dongle and a PS3 controller, I tried checking "Force Install" and the installation just hangs, but if I install normally every time I boot then it works again. It doesn't always happen but has been the last few times.

Possibly of note - I've been leaving my controller plugged in by USB cable while I boot, though I haven't tested this

**Comment by charlesmilette** [comment]
If you're using Bluetooth, it may be related to #51

**Comment by mirh** [comment]
Did you try to put SCP service to "Late" start as suggested [here](https://github.com/nefarius/ScpToolkit/issues/224#issuecomment-192291387)?

**Comment by keithomalley** [comment]
@mirh That's fixed it for me! thank you :)

**Comment by mirh** [comment]
Ugh. 
I'd try to bump all threads, let's see.

**Comment by ikwtif** [comment]
I seem to be having the same issue. I have to reinstall everything on a restart. Setting the scp service on delayed start hasn't helped

**Comment by Artuvazro** [comment]
I have this problem too. When the service is stopped and then restarted, the controller won't pair via Bluetooth unless I reinstall the whole thing.

**Comment by charlesmilette** [comment]
@Artuvazro does it works via cable?

**Comment by Artuvazro** [comment]
@charlesmilette Yes, with the cable it works without any need to reinstall the driver. But when I disconnect the cable it doesn't pair via Bluetooth unless I reinstall the drivers again.

**Comment by charlesmilette** [comment]
Then #51 is your issue

**Comment by Artuvazro** [comment]
@charlesmilette  Oh, thank you ;)
