### ISSUE TITLE
Bluetooth connection to controllers isn´t working after reboot.

### ISSUE THREAD

**Issue by voqelfrei** [nefarius/ScpToolkit#353]
I recently updated the version v1.7.277.16103-BETA, because the previous versions had the constant error, that the service "Ds3Service" couldn't launch after a reboot, so the entire program wasn't responding correctly. 

Now the program seems to hate me:
1. Usually, the service starts properly, but about every third time, it just doesn´t work, like shown here:
   ![unbenannt](https://cloud.githubusercontent.com/assets/20207070/16456360/edc8760e-3e17-11e6-9371-5ad11850d2a1.PNG)
2. The Bluetooth connection to my controllers doesn´t work all the time, even if it seems to be launched properly and the service is running flawlessly:
   ![noerror](https://cloud.githubusercontent.com/assets/20207070/16456523/66a22908-3e18-11e6-97c0-7256b4ba1dc4.PNG)
   (My main controller is connected via USB, but my second one couldn´t connect at all.)

The Bluetooth driver should be installed correctly too, I think:
(I have an integrated Bluetooth card. The Hardware-ID is "USB\VID_04CA&PID_300B".)

![devicemanager](https://cloud.githubusercontent.com/assets/20207070/16456632/d7bc6c7a-3e18-11e6-956f-302036b8e486.PNG)

The Virtual Bus Driver is also installed correctly.

I hope, someone could help me because I don´t know what to do next, in order to get this working.

Best regards,
EnderCraftDE

Btw, I hope my English isn´t too bad.

**Comment by charlesmilette** [comment]
See #51

**Comment by mirh** [comment]
Not that I'd like to trigger any anti-spam filter.. 
But try to put SCP service on "Late" start.

**Comment by Jan200101** [comment]
Set SCP service to late start as mentioned above and set it to restart if it crashes.

I can give you a tool if you cant do it yourself

**Comment by EnderCraftDE** [comment]
Putting the service on Late start, just fixed the problwm twice, later it was like before.
