### ISSUE TITLE
Tray app interrupts game while updating

### ISSUE THREAD

**Issue by Alkaris** [nefarius/ScpToolkit#362]
The Scp Toolkit updater tray app is very annoying when it interrupts games while updating. Could this perhaps be changed so that it updates silently in the background so it doesn't do this? It's very annoying when playing a game and then all a sudden game stops just to show me the updater has completed.

If tray app is active, do not make it pop-up a window dialogue that interrupts everything else. An OSD notification will suffice enough to let person know it updated.

**Comment by CREEATION** [comment]
Is there any option to disable auto-updating? I don't even want auto-updates and yes, it's more than annoying.

**Comment by Alkaris** [comment]
@CREEATION - I don't think there even is option for that, except for perhaps removing it from Start-Up Applications folder. But I don't think that would even stop it.

**Comment by RobinQuetin** [comment]
The SCP Toolkit Updater is started by a scheduled task named 'updater' ([where to find?](https://technet.microsoft.com/en-us/library/cc721931(v=ws.11).aspx)). You can customize the update frequency and other things (I think there is even an option which can hide the task, but I don't know if it still updates the application using this option), or even disable it completely.

**Comment by Alkaris** [comment]
@RobinQuetin - just changing the scheduled task isn't enough, it should be made to silently update in the background and given the user a OSD Notification instead of dialogue box popping up on the screen.

**Comment by nefarius** [comment]
The updater behavior is tamed down since 1.7
