### ISSUE TITLE
Classic ABXY layout

### ISSUE THREAD

**Issue by Jop-V** [nefarius/ScpToolkit#366]
This is how the buttons are mapped:

```
○  →  B
×  →  A
□  →  X
▲  →  Y
```

Makes sense for a default because it matches the Xbox ABXY locations.

![Xbox ABXY](https://byungsuk.files.wordpress.com/2013/09/xbox-one-abxy.jpg?w=328&h=328)

But I'd like to use the classic ABXY layout instead of the Xbox layout. Like this:

![Classic ABXY](http://www.consolewerks.co.uk/images/ndsi%20xl%20repair%20thumbs/dsi-xl-buttons-not-working.jpg)

```
○  →  A
×  →  B
□  →  Y
▲  →  X
```

Could you add this as an option to the settings manager?

**Comment by mirh** [comment]
If you want to switch button mapping, use x360ce.

**Comment by Jan200101** [comment]
SCPToolkit is just translating your DS3 controller to a XBOX controller

**Comment by nefarius** [comment]
@Jop-V this would be achieved by the new profile manager which is stuck in development hell since months =3 So sadly currently not possible without 3rd party tools.

**Comment by mirh** [comment]
I'd see the sense if SCPtoolkit wanted to really go universal (#243 and 85cc28dd30ff9489da047b82f4b8cd7c743c307c) but tbh, until it isn't that far I think efforts would be better spent elsewhere.

**Comment by nefarius** [comment]
@mirh [I guess you will love this](../../ViGEm) once it's finished ;)

**Comment by mirh** [comment]
I'm dreaming of your tool to be like: 

																				↗ DirectInput
    HID → Raw Input API (or whatever standard needed to make #82 great again)
																				↘ XInput

**Comment by nefarius** [comment]
With more and more knowledge of the wonders of the [KMDF](https://msdn.microsoft.com/en-us/library/windows/hardware/ff557565(v=vs.85).aspx) I also grow more and more powerful!

![](https://upload.wikimedia.org/wikipedia/en/1/16/Drevil_million_dollars.jpg)

**Comment by mirh** [comment]
Thinking to the aforementioned evil scheme, #290 last comment and #243.. I wonder if the whole thing couldn't become.. like modular?
There's a toy that converts standard Raw Input to DirectInput, one to XInput, then every supported controller would have one of those USB<->HID driver you mention.. And then I guess a pretty bare "profile" could be made that maps HID signals to RI ?

**Comment by nefarius** [comment]
What I've learned from tinkering with device driver development is, that whenever you can you should incorporate with the existing Microsoft drivers so errors and development overhead is minimized. I like the modular approach; [in my rewrite](../../ViGEm) of the `ScpVBus` I already designed it with driver-to-driver communication in mind. This would allow to easily (with a few lines of code) add XInput support to [HID-Wiimote](../../../jloehr/HID-Wiimote) and other projects.

**Comment by nefarius** [comment]
@mirh [Your wish is beeing implemented](https://www.youtube.com/watch?v=lALPkzTA-5Q) :smiley:

**Comment by mirh** [comment]
\**Unzips*\*

**Comment by nefarius** [comment]
![](http://www.relatably.com/m/img/blushing-memes/tumblr_lwsazawxa51qht847.png)

**Comment by mirh** [comment]
![](http://memesvault.com/wp-content/uploads/Fap-Meme-11.jpg)

**Comment by charlesmilette** [comment]
![Too late](http://memeblender.com/wp-content/uploads/2012/12/fap-fap-fap.jpg)
