### ISSUE TITLE
Host address :  disconnected

### ISSUE THREAD

**Issue by mavalois** [nefarius/ScpToolkit#372]
Getting a problem here. Host address keeps showing as disconnected in SCP Monitor. SCP Bus Driver is running is the device manager. 

Needless to say, I'm unable to connect a PS3 controller

Logs attached, 

Anyone have a clue ?

[Logs.zip](https://github.com/nefarius/ScpToolkit/files/355199/Logs.zip)

**Comment by awesomeness872** [comment]
do you have a bluetooth adapter? is it supported?

**Comment by mavalois** [comment]
I do have a bluetooth adapter. I have not yet checked if it is supported. 

At the moment, I'm trying connect through USB before moving forward with anything else.

**Comment by awesomeness872** [comment]
do the controllers work at all? I'm pretty sure that the host address is a bluetooth thing and shouldnt matter if you're using USB

**Comment by mavalois** [comment]
Controllers are not working

**Comment by maverick340** [comment]
I seem to have the same issue. Here are the steps I followed. 
1. Plugged in the DS3 controller (original)
2. Downloaded and installed SCPToolkit (no forced install)
3. Windows asked me if i trust these drivers source blah blah, I said Yes.
4. It shows all drivers installed fine.
5. SCP monitor still shows Host : Disconnected

Anything I am doing wrong here? It used to work with Windows 7 fine.

**Comment by maverick340** [comment]
@mavalois  : Try the beta drivers : https://github.com/nefarius/ScpToolkit/releases/tag/v1.7.277.16103-BETA
Worked for me.

**Comment by mavalois** [comment]
Beta drivers suggested by maverick340 solved the problem.

**Comment by rinkodijks** [comment]
Had the same problem. Beta drivers have solved the problem for me as well.

**Comment by bucho2398** [comment]
Have the same problem, beta drivers solved nothing.

**Comment by craazydude** [comment]
Have the same problem, beta drivers solved nothing.

**Comment by lilcheo** [comment]
help drivers didnt work plz help

**Comment by goldenmane** [comment]
Have the same problem, the controller connects through usb but there is no host adress in scp monitor, it says host adress disconnected even though I could connect my controller without any problems before the Windows 10 update.
