### ISSUE TITLE
other apps cant use PS button

### ISSUE THREAD

**Issue by awesomeness872** [nefarius/ScpToolkit#373]
theres not really much else, used with genuine ps3 and ps4 controllers. everything else works.

**Comment by awesomeness872** [comment]
i have done some testing with the input tester and it shows up when i press it and when i press other buttons it says im pressing that button and the PS button

**Comment by charlesmilette** [comment]
That's maybe because on Windows 10 the PS (or Xbox) button is used for the Xbox game overlay. To restore normal fonctionnality, I think you can disable it in the settings of the overlay itself (Win + G) or via the Xbox app.

**Comment by nefarius** [comment]
[That's a Windows-thingy](https://steamcommunity.com/discussions/forum/1/530645961936632430/) and nothing I can fix.
