### ISSUE TITLE
Fatal Error Occurring When Profile Manager Opened

### ISSUE THREAD

**Issue by devondale16** [nefarius/ScpToolkit#379]
Everytime the profile manager is opened, a dialog box comes up and says a 'Fatal Error Has Occured'. The whole toolkit works perfectly everywhere else and I really enjoy using it. I'm using a genuine DS3 controller on Windows 10 with the latest stable build. 
Thanks

**Comment by nefarius** [comment]
The profile manager in its current form is way below alpha stage, that's why it's not included in the default setup. I'll announce it when it's usable.
