### ISSUE TITLE
Make driver compatible again with arbitrary PIDs

### ISSUE THREAD

**Issue by mirh** [nefarius/ScpToolkit#380]
I see how funnily I was one of those [praying](https://github.com/nefarius/ScpToolkit/issues/116) for WinUSB to come back.. 
But now I have this laptop with built-in BT which has an unsupported PID (it's still 100% an Atheros AR3012.. just with Asus's VID instead of Qualcomm's) and the 1.7 beta didn't work. 

Is "complain to dev and wait newer strings to be included" the only approach, could #290 improve this, or what else?

**Comment by nefarius** [comment]
Holy sh*** you are the master of GitHub, I can't read this fast, gimme a few minutes =D

**Comment by mirh** [comment]
Oh, I'm just underlining the existing problem d:
And, if not #290 (would be interested to know about) at least it's going to be a kind of  [META] for every bug regarded to missing PIDs.

**Comment by nefarius** [comment]
I'm slowly catching up; my mail server died the day I went on vacation so I currently can't get interrupted by anyone xD

**Comment by DragonWolf5589** [comment]
does anyone know if this is resolved yet?

bluetooth worked fine in the latest release, but cpu usage was 60-80%! 

the lastest beta works perfect but shows I do not have a bluetooth connection (I reinstalled the orginal driver) I dont use a dongle its built in, and ive NEVER used it except for the ps3 controller anyway .

how do I install it as the button wont "light up" for me on the installer

(and some reason my ps3 controller behaves badly when wired for some reason, it only works correctly with bluetooth)

up to now its either random spasmic behaviour, or 90-100% total cpu usage of with over 60% is from SCPServer!

**Comment by mirh** [comment]
> does anyone know if this is resolved yet?

_[We are getting there](https://twitter.com/CNefarius/status/763447847337484288)_.
