### ISSUE TITLE
Motherboard bluetooth not compatible

### ISSUE THREAD

**Issue by CheesyKek** [nefarius/ScpToolkit#388]
Been using your toolkit for days, it works wonderfully, except it works on cable only.
After days of researching somewhere else, turns out I found out in here that my onboard bluetooth's not compatible.
Tried manually adding the hardware ID, my bluetooth ended up unusable instead.
Maybe you can add these hardware IDs on the next version?
USB\VID_13D3&PID_3423&REV_0001
USB\VID_13D3&PID_3423
I'd be grateful if you do, or if any of you guys have any other methods to recommend please do tell me.

**Comment by mirh** [comment]
#380
