### ISSUE TITLE
Installing on USB\VID_148F&PID_3298 causes BSOD & CMOS corruption

### ISSUE THREAD

**Issue by akeean** [nefarius/ScpToolkit#389]
On a HP ENVY 17-j199ez with win 10 home x64 build 10586

Installed SCP v1.6.238.16010

Original DS3 / Sixaxis controller model CECHZC2M was connected via USB.

In Driver Installer I selected to installed the Bluetooth driver to the Ralink Bluetooth device.

Service installed. then went to a BSOD THREAD_EXCEPTION_NOT_HANDLED on wf01000.sys

After this my Laptop stayed almost dead. Black screen, caps lock led blinked 2x every few seconds indicating a corrupted bios. Had to open it and disconnect the bios battery for a minute to get it to start again. It then reverted the bios and booted normally.

Details: Bluetooth a BT4.0 / Wifi bgn mPCIE combo card from Mediatek that came with the laptop). 

Driver is the latest availiable from the HP website, v2.3.1.0 (USB\VID_148F&PID_3298&REV_0000\5&3986B207&0&01, Bluetooth radio HCI version 06 & LMP supported features: FF FF 8F FE DB FF 5B 83),

[Logs.zip](https://github.com/nefarius/ScpToolkit/files/382929/Logs.zip)

**Comment by mirh** [comment]
Corrupted bios seems like a bug in system firmware.
