### ISSUE TITLE
Rumble is causing the controller to freeze for ~10 seconds

### ISSUE THREAD

**Issue by 7yphoid** [nefarius/ScpToolkit#39]
I have installed ScpServer on Windows 10 64-bit. I am using a wired DS3 controller.

It seems to be working fine except for the fact that whenever the controller rumbles (let's say I get hit in the game I'm playing), the controller freezes and the input "sticks" for ~10 seconds. So, if I was walking right when it happened, I'll continue walking right until it unfreezes.

Interestingly, while disabling rumble in ScpSettings does make the controller not rumble, it does not prevent the controller from freezing after rumble events.

Any clue what the cause of this might be and what I can do to remedy this problem?

**Comment by CookiePLMonster** [comment]
Come to think of it, my issue might be similar - rumble seems to send some random data on analog sticks, effectively locking them.

Do note this is for wired. Would still like to debug it and try to come up with a solution, though for the second time I don't remember where the input gets processed. Meh.

**Comment by 7yphoid** [comment]
For me, the rumble actually causes the whole controller to lock up. I can't even pause the game until the ~10 seconds is up. Also, IIRC, if I hit the pause button on the controller, it does pause after it's done locking up, which means that the buffer is still active but not being processed.

How should I go about gathering additional debugging information? What should I be looking at?

I'm using MotionInJoy until I can get SCP to work. At least I'll be getting a Steam Controller in a week.

**Comment by felixthecat1970** [comment]
same here windows 10 pro TH2, rumble stop control funtions, test release ScpToolkit v1.6.133.15324 and ScpToolkit v1.6.126.15319; but release ScpServer v1.5.5756.37820 works ok with rumble.

**Comment by 1st8** [comment]
Experiencing the same, will try v1.5.

**Comment by RyanTH98** [comment]
Confirmed on the latest version. Tried playing Rocket League, experience lockups, and weird rumbling.

**Comment by skite2001** [comment]
got the same problem. worked the whole time, after updating to latest drivers the problem happens. for example: pressing shoot button -> whole mag gets fired, after that the rumble kicks in. after the rumble is over i can move my guy again.

http://forums.pcsx2.net/attachment.php?aid=58290
ScpToolkit_Log-Package_skite2001_1449181443.zip

**Comment by nekogami** [comment]
Just had the same problem, installing ScpToolkit v1.6.186.15342-BETA fixed it.

**Comment by skite2001** [comment]
can confirm: latest beta fixes the rumble issue

**Comment by nekogami** [comment]
Had a little problem last night with v1.6.186.15342-BETA .
On Rocket league, some buttons were pushed while playing without any action which made me jump/loose the ball cam randomly.
Had to rollback to https://github.com/nefarius/ScpServer/releases/tag/v1.5.5787.40106

**Comment by ChaoticTabris** [comment]
Can confirm this problem or a similar one is still happening to me on v1.6.229.15365. It freezes for a moment and i hear the sound as if a USB device had been unplugged. At times i also had the control controller completely stop working and being "stuck" vibrating until i unplugged it (i don't have a device to use it with Bluetooth, so i only play with the USB cable).
