### ISSUE TITLE
fake PlayStation 3 controller vibration  via bluetooth fix

### ISSUE THREAD

**Issue by 7710101** [nefarius/ScpToolkit#390]
https://drive.google.com/file/d/0B02BQcVF2DX9ajc1NTdfRnRpNkU/view?usp=sharing

**Comment by merklaw** [comment]
Please add more details.

**Comment by cesc007** [comment]
it works with windows 10, thanks a lot!

**Comment by n00bC0d3** [comment]
not work with mine ...
using 
intel bluetooth 4.0  VID 8087 PID 07DC

with ScpToolkit v1.6.238.16010 

unable to pair

**Comment by 7710101** [comment]
You must use USB dongle 2.0 to 4.0 built-in Bluetooth will reinstall the driver's on restart

**Comment by 7710101** [comment]
I have a HP envy laptop and i have the same problem. When i got my Bluetooth dongle it works with the (fake ps3) controller and my Bluetooth headphone works great with the intel Bluetooth 4.0

**Comment by n00bC0d3** [comment]
my bluetooth is internal bluetooth in lenovo y50-70 touch. 
it is bluetooth 4.0 , so it should be compatible right ?

**Comment by 7710101** [comment]
Built-in bluetooth will not work. U must get a usb dongle for this to work

**Comment by n00bC0d3** [comment]
![win10 ps3-2016-08-05-19-09-13](https://cloud.githubusercontent.com/assets/12411061/17436339/785a381c-5b40-11e6-9518-0cc8cfd3e54d.png)

what i done : 
1. stop replaced the SCP DSx service 
2. replace scpcontroll.dll with fakeFix 
3. start the service back ..

it's the same whether i use version 1.6 or 1.7

**Comment by 7710101** [comment]
did u get the usb bluetooth dongle  its the only whey it will work
internal bluetooth will not work windows is built to reinstall removed dirvers

**Comment by n00bC0d3** [comment]
no, i still trying to figure how the trick to use built in bluetooth. 
although i didn't restart windows after updating all driver to SCPTool driver, still can't pair . 
Bluetooth status always NONE. 

wonder if anyone can give me clue about "bluetooth pairing status NONE "

**Comment by Freeedo** [comment]
Download the file and then what?  "first intall scpserver then move and replace scpcontrol.dll in bin folder". I get "fatal error" when I try to start up scp again.  Can you at least give us a step by step instead of just throwing a file up and saying "restart hope for the best...".

**Comment by 7710101** [comment]
[Scarlet.Crush Productions.zip](https://github.com/nefarius/ScpToolkit/files/1584468/Scarlet.Crush.Productions.zip)
extract the file directly to the (C drive) and then install if it doesn't work try force install or (disable driver signification) restart and hope for the best.
