### ISSUE TITLE
Usage of internal Bluetooth

### ISSUE THREAD

**Issue by acocalypso** [nefarius/ScpToolkit#391]
Is it possible to add the usage of a build in Bluetoothmodule?

F.e im using my Dell venue 8 Pro with Windows 10 and I do only own 1 micro USB Port... thats mostly used for charging.

So it would be great if I could instead convert my internal bluetooth to make it work with my controller.

**Comment by merklaw** [comment]
You can find your Hardware ID of the Bluetooth adapter in Windows Device Manager if you right click on the device (found under "Bluetooth Radios") and click Properties, and then go to the Details tab and find "Hardware IDs". Please note if there are other entries that have something with "ID" in them, and post them here as well.

**Comment by mirh** [comment]
#380
