### ISSUE TITLE
ERROR: The process cannot access the file 'C:\Program Files\Nefarius Software Solutions\ScpToolkit\Logs\ScpDsxMonitor_butch.log.xml' because it is being used by another process.

### ISSUE THREAD

**Issue by americanidiot445** [nefarius/ScpToolkit#393]
Ran the debugger, information provided by debugger is as follows: 
ERROR: The process cannot access the file 'C:\Program Files\Nefarius Software Solutions\ScpToolkit\Logs\ScpDsxMonitor_butch.log.xml' because it is being used by another process.

**Comment by charlesmilette** [comment]
Seems you left the monitor open.

Or maybe it could have been the Windows service/the stand-alone server
