### ISSUE TITLE
Bluetooth Pairing

### ISSUE THREAD

**Issue by protectivedad** [nefarius/ScpToolkit#396]
My Bluetooth ID is:
USB\VID_413C&PID_8160&REV_0173
USB\VID_413C&PID_8160

The libusbK device driver is loaded. 

This SCP Monitor Legacy shows:
![image](https://cloud.githubusercontent.com/assets/1096963/17347559/f1f75b7a-58e6-11e6-9d0c-bfb3e9bffe60.png)
when the controller is plugged into the USB. When I unplug the USB and try the controller from the BT I get a message from the tray app saying Geniune Sony DualShock 3 found. But it won't pair. It worked once but when I restarted the pc it stopped pairing. 

I've included the debug zip also.
[ScpToolkit_Log-Package_antho_1470176303.zip](https://github.com/nefarius/ScpToolkit/files/398293/ScpToolkit_Log-Package_antho_1470176303.zip)

**Comment by s0me-1** [comment]
Did you tried to force the pairing using the old legace pair utility ? 

![screenshot_1](https://cloud.githubusercontent.com/assets/7307512/17437179/860a4746-5b1c-11e6-9479-385542e3a346.png)

( the address to be setted must be the host adress )

**Comment by mirh** [comment]
#380

**Comment by mirh** [comment]
Your adapter isn't included in driver .inf. 
You can wait for newer GLORIOUS version to come out, or either downgrade to 1.6 or old SCP release.

**Comment by protectivedad** [comment]
I'm using version 1.6 I tried as low as 1.6.2, but I get the same problem. I could never get the old SCP release to work. Only SCPToolkit and only until I did a reboot.

**Comment by mirh** [comment]
Uhh, then your problem is [this](https://github.com/nefarius/ScpToolkit/issues/224#issuecomment-192291387).

**Comment by OverWorldD** [comment]
I have this problem with one of my controllers. Both are clones, One is a bit better and works as it should even over BT, the other one works only over USB, and gets detected as a genuine DS3 controller (It's most certainly not), but does not seem to pair okay. Attachment shows what my server does, it goes as far as this when I start the controller, and then the controller shuts down after a while.
![server](https://cloud.githubusercontent.com/assets/12225528/24678115/ff78a1de-1991-11e7-9f85-5ed4b9b6a691.png)
It works fine with sixaxis controller to my android tablet over bluetooth so I don't know why SCP doesn't like it :(
