### ISSUE TITLE
Bluetooth host adress is corrupted after reboot

### ISSUE THREAD

**Issue by s0me-1** [nefarius/ScpToolkit#398]
I had the case with the old 1.2.2 SCP aswell, When I do a clean install, all the drivers are correctily installed and everything is working great. But if I reboot my computer, i have this : "Host adress : <Error>"

Here's the attached log created by your bug report tool :)

[ScpToolkit_Log-Package_arnau_1470400140.zip](https://github.com/nefarius/ScpToolkit/files/403733/ScpToolkit_Log-Package_arnau_1470400140.zip)

**Comment by charlesmilette** [comment]
That could be related to issue #51

**Comment by s0me-1** [comment]
Indeed, I have an Internal bluetooth chipset too, regarding the answer from Nefarius, it seems the old Uninstall/Reinstall is the only workaround to get it working :p

**Comment by mirh** [comment]
https://github.com/nefarius/ScpToolkit/issues/224#issuecomment-192291387
