### ISSUE TITLE
"Name Not Available" application in Sound Mixer

### ISSUE THREAD

**Issue by Miqunator** [nefarius/ScpToolkit#402]
Sounds from the toolkit seem to fall under a "Name Not Available" application in the Sounds Mixer, restarting the SCP DSx Service creates more entries.

Disabling Notification sounds in ScpToolkit Settings Manager stops the suspicious application from showing up.

Using latest Win10 version, never tried the ScpToolkit in earlier builds.

**Comment by nefarius** [comment]
It's not suspicious at all; since the sounds come from a Windows service that's running with high privileges the mixer can't get access to the process name or window title so it shows that the name is not available.
