### ISSUE TITLE
Windows 10 Anniversary Update - SCP driver signature not recognized

### ISSUE THREAD

**Issue by Keefaetana** [nefarius/ScpToolkit#408]
I recently made a fresh install of Windows 10 with the Anniversary Update included and then attempted to install ScpToolkit v1.7.277.16103-BETA. At first it wouldn't even install properly because Microsoft changed the rules on signing drivers (http://www.thewindowsclub.com/driver-signing-changes-windows-10). I then disabled the driver signature verification, after which installing and using the driver worked perfectly. Now, after rebooting, the driver no longer works. I checked Device Manager and this is what it says:

"Windows cannot verify the digital signature for the drivers required for this device. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source. (Code 52)"

Is there any way to permanently disable the driver signature verification?

Thanks a lot!

**Comment by charlesmilette** [comment]
As mentionned in #266, you have two choices:

- Disable secure boot
- Run `bcdedit /set loadoptions DDISABLE_INTEGRITY_CHECKS` in a admin command prompt. Please note that DDISABLE is not a typo.

**Comment by Keefaetana** [comment]
Ah, I hadn't noticed that. Thanks for the help, charlesmilette!

**Comment by rougetimelord** [comment]
That's a bandaid fix, many users want to keep secure boot on (me)

**Comment by nefarius** [comment]
@rougetimelord I'm in the middle of the process of getting a compatible certificate.

**Comment by rougetimelord** [comment]
@nefarius 👍 I just don't want to fiddle with it and don't have issues (yet) 😜

**Comment by TheWingedCherryPie** [comment]
I tried the bcdedit command, nothing changed.
