### ISSUE TITLE
Lilypad modification broken in lastest version of pcsx2?

### ISSUE THREAD

**Issue by DankWeed** [nefarius/ScpToolkit#409]
if you have lilypad modification enabled in scptoolkit global config it causes to make my controller not able to respond in pcsx2 or even change buttons in lilypad settings.
it does however respond if lilypad modification is disabled. 
edit: i forgot to tell that it happens on the latest dev version of pcsx2.

**Comment by mirh** [comment]
https://twitter.com/CNefarius/status/768860350884241408
