### ISSUE TITLE
Low Battery OSD

### ISSUE THREAD

**Issue by Blackbird88** [nefarius/ScpToolkit#41]
Something like this would be very useful!
![image](https://cloud.githubusercontent.com/assets/4414625/10865715/7f384360-8015-11e5-9558-784dcdaaf05c.png)

**Comment by nefarius** [comment]
Right, I have some prototypes in the works, stay tuned!

**Comment by Blackbird88** [comment]
Cool!

**Comment by nefarius** [comment]
What do you think?

![Castlevania: Lords of Shadow - Ultimate Edition](http://nefarius.at/wp-content/uploads/2013/12/13-12-_2015_05-15-51.png)

**Comment by Blackbird88** [comment]
Very good. You should make it configurable so you can set the threshold when it shows up (and maybe even change colors to yellow and then red when it's low?). Kinda like battery LED on phones.
Optional one-time blinking would be perfect!

**Comment by teeedubb** [comment]
It is great that to see that this feature has interest.

Any chance that a low battery notification sound be added too?

**Comment by Jan200101** [comment]
hmmm.... maybe adding a sound to it like a few silent beep

**Comment by FuzzyFoxe** [comment]
It's been a couple years, any progress on this? o:

**Comment by nefarius** [comment]
[Well, more or less](https://github.com/nefarius/Indicium-Supra) 😄
