### ISSUE TITLE
Unable to switch input language by using ctrl + shift when open ScpToolkit Profile Manager in Windows 10

### ISSUE THREAD

**Issue by zeroarst** [nefarius/ScpToolkit#414]
I configured my input languages by using combined key ctrl+shift.
However, when I open ScpToolkit Profile Manager, I found it not working at all, unless I close it.

![2016-08-21 11_09_38-text services and input languages](https://cloud.githubusercontent.com/assets/1834837/17834707/04d70ee0-6790-11e6-9f9d-4bb6a3404f25.png)

It this a conflict?

**Comment by nefarius** [comment]
Yep.
