### ISSUE TITLE
After a few minutes one controller have lag.

### ISSUE THREAD

**Issue by jbiribi** [nefarius/ScpToolkit#415]
When I'm playing with 4 controllers (1 xbox 360, 2 ps4 and 1 ps3) the PS4 controllers become to have a lag in their comands, and sometimes their comands don't work. At last plays one of the controller is shutting down.  I reinstalled the driver but the problem doesn't fixed.

**Comment by lgfrbcsgo** [comment]
I have a similar problem. I turned out, that the game I was playing is pretty CPU demanding and even maxed out my CPU sometimes (AC: Syndicate). Setting the priority of the ScpService.exe process to anything higher than "normal" fixed all the input lag.
