### ISSUE TITLE
DS3 goes UP randomly while wired.

### ISSUE THREAD

**Issue by Z3phyr** [nefarius/ScpToolkit#416]
Hi! As the title says, my controller, **ONLY** when wired, tends to go UP at random times. Is really annoying.

I've tried different cables and even another controller (mine could be faulty) but the problem persists. I'm on Windows 10 x64 Anniversary Update. This happens in both the beta release and the stable release.

While using bluetooth the controller works perfectly.

I've made a little video that shows the issue: https://gfycat.com/BossyCourteousEmeraldtreeskink

**Comment by ShayBox** [comment]
Seems like a controller issue, may be sending two pins or something in the controller sending a wrong signal, but it may be a software issue, have you tried it on any other pc's or softwares (ds3/4, motionjoy)?

**Comment by nefarius** [comment]
Smells like a hardware problem; the USB port on your controller might have become loose and randomly causes issues on the PCB. The software just translates so randomness most of the time emerges from the controller itself.

**Comment by Z3phyr** [comment]
As I said, it happens with two different controllers. (tried another cable and another usb port too)
