### ISSUE TITLE
Installed SCP Toolkit, mouse doesn't work.

### ISSUE THREAD

**Issue by gangamopen** [nefarius/ScpToolkit#423]
I recently installed SCP Toolkit on my laptop on windows 10 for my DualShock 4, and me being the not so smart one, I checked every box. After installation I've found that my mouse doesn't work. I understand there are these problems everywhere, but I'm not that smart tech-wise and I don't understand what to do. Could you please explain how to, if there is one, fix this problem?

**Comment by nefarius** [comment]
Get a different brand mouse/keyboard loaned by a friend/school/workplace and [follow this guide](../wiki/Manual-driver-removal).

**Comment by gangamopen** [comment]
thank you
