### ISSUE TITLE
Fake DualShock 3 found. Trying Workarounds..

### ISSUE THREAD

**Issue by gobit-ua** [nefarius/ScpToolkit#425]
I have 2 joystick (http://www.gearbest.com/game-controllers/pp_279646.html)
![afjcyw65r5a](https://cloud.githubusercontent.com/assets/12720986/18086591/560dee0c-6eb9-11e6-8f3a-39d8ee4272fa.jpg)

By USB - all ok!
But by Bluetooth worked only black joystick.

In notifications i see next, by USB
![cbb790d0aea245f1992bfa4cd0f589aa](https://cloud.githubusercontent.com/assets/12720986/18086626/8c38c7e0-6eb9-11e6-9239-e46304aff373.png)
and by BT
![9a586fba229a4951a44e889ca1a0994e](https://cloud.githubusercontent.com/assets/12720986/18086636/97059e8c-6eb9-11e6-8049-54442cc3e73f.png)

Thanks!

**Comment by gobit-ua** [comment]
Helped decision https://github.com/nefarius/ScpToolkit/issues/241
Substitution ScpControll.dll http://forums.pcsx2.net/attachment.php?aid=59733 in the release version
https://github.com/nefarius/ScpToolkit/releases/download/v1.6.238.16010/ScpToolkit_Setup.exe

Thanks for j0shg

**Comment by lovetheories** [comment]
Did you change your Vid? Because when I install mine fake drivers, it doesn't change...

**Comment by gobit-ua** [comment]
No, I didn't. Only changed dll.

**Comment by lucastcp1** [comment]
@gobit-ua 
May the gods bless you bro.
After 1 weak with same problem your info worked to me.
I instaled ver 1.6.238 with the dll substitution and now is working. Thank you very much.

Aditional info,  my setup is:
- Windows 10
- fake ps3 controler. device id: vid_045e&pid_028e
- Bluecore csr8510 a10 dongle
