### ISSUE TITLE
Couldn't plug in virtual device; parameter is incorrect. Games don't detect input.

### ISSUE THREAD

**Issue by ScTiger1311** [nefarius/ScpToolkit#426]
I have been getting these 2 errors after using a DS4 controller once after a year or so of normal use with a DS3 connected via USB. Errors still occur after rebooting multiple times, reinstalling the program multiple times, resetting my genuine DS3, using the clean wipe utility that comes with the program, and using my other DS3. Nothing I try seems to be able to fix it.

The controller still lights up like it is connected normally, with the first light being on and solid, but none of my game detect my input. I am using the latest version (1.6.238.16010 according to the download page) but I have also tried older versions.

Any help would be greatly appreciated. Thanks!

![image](https://cloud.githubusercontent.com/assets/19415204/18110078/731815f2-6eca-11e6-9a21-bbfd6b9f039c.png)

**Comment by lost-RD** [comment]
https://github.com/nefarius/ScpToolkit/issues/304
