### ISSUE TITLE
update checker

### ISSUE THREAD

**Issue by sarf2k4** [nefarius/ScpToolkit#427]
Hi, I kind of didn't like to have the scp's auto update checker kept running every time I start my pc and when there's no internet it would give me error. Furthermore, it's not like scptoolkit will be having updates every day or every hour. 

There should be an option to disable, check for update button for manual checking, or scheduled auto update checker (can be set by users).

The auto update prompt gets annoying

**Comment by charlesmilette** [comment]
That behavior has been fixed in the beta.
