### ISSUE TITLE
ScpToolkit Profile Manager: Almost no interaction seems to work

### ISSUE THREAD

**Issue by TheZnayx** [nefarius/ScpToolkit#429]
1. All menus other than Button Mapping do NOT open/expand at all. The menus below Button Mapping in the profile manager do not expand, do not highlight when mousing over.

2. When I adjust mapped buttons in the only menu that does work, they do not affect the PS3 controller whatsoever. The PS button causes the Xbox Game Menu thingy to pop up whether I'm attached by USB or (Gasp!) onboard bluetooth, but no other buttons cause any reaction. I've assigned directional keys to the d-pad, and left-click to the X button. No reactions. However, I don't have my Steam games (or any other controller-compatible PC games) to test it with, so maybe it NEEDS a game in order to work. 

Anyway, these appear to be important issues. What might be wrong with it? I checked the forced driver box when installing, and I see that the drivers (both DS3 and BT) show up in my Device Manager. Also, in the Scp Profile Manager, the button indicators light up and react when I press buttons on the controller. It just doesn't do anything that I map it to.

**Comment by nefarius** [comment]
That's because it's alpha and marked unstable.
