### ISSUE TITLE
Dualshock 3 - bluetooth keeps Disconnecting

### ISSUE THREAD

**Issue by ivanelias** [nefarius/ScpToolkit#43]
Hi, I love the drivers, theywork really well but I'm having trouble with my ds3, it works perfect over usb, but when I use it with bluetooth it disconnects, I hear the hardware disconnect sound from windows and the controller shuts off, if I turn it on again it pairs again and works normally until in happens again.
This seems random, sometimes it hapens over and over, sometimes it works for hours without any problems.

Windows 7 Sp1 64bits
Using version 1.5.5785.22024 (it also happened on v1.5.5756.37820)

The ids:
USB Dongle
USB\VID_0A12&PID_0001&REV_0100
USB\VID_0A12&PID_0001

DS3
USB\VID_054C&PID_0268&REV_0100
USB\VID_054C&PID_0268

Installer and Service logs:
https://drive.google.com/file/d/0BzwxolJ6wHu8ZVBYcWFMTEphV0E/view?usp=sharing
https://drive.google.com/file/d/0BzwxolJ6wHu8QlBaWDd6UlB1X0k/view?usp=sharing

It happened near the end of the log, I hope you can help me, thanks.

PD: It may be another issue but vibration doesn't work over bluetooth, i have it disabled, it works alright on usb.

**Comment by Nicodemusss** [comment]
I think I have the same problem.
