### ISSUE TITLE
BSOD on win 10 x64 and ralink rt3290 bt(4.0 +LE)

### ISSUE THREAD

**Issue by 2909luboy** [nefarius/ScpToolkit#437]
well this is simple I tried to install the driver for my ps3 control (original) in vercion v1.6.238.16010 and I've led a pretty bsod driver saying something ....

is a ralink rt3290LE with 4.0 bt build in combo (mPcie) if you need more information we will gladly I can provide

**Comment by HASJ** [comment]
Same thing here.
