### ISSUE TITLE
High CPU usage introduces severe input lag

### ISSUE THREAD

**Issue by felixschorer** [nefarius/ScpToolkit#443]
When the CPU usage approaches the 90% mark in CPU-demanding games (like in AC: Syndicate, which process priority is set to "high" by default), the input starts lagging serverly. Setting the ScpService.exe process to "high" priority in task manager fixed the input lag. Is it possible to set the process priority at start up? I am using Windows 10 and never had problems like this under Windows 7.

**Comment by k0enf0rNL** [comment]
@lgfrbcsgo No its not possible to do this at startup unfortunately. You will have to do this everytime you start scp.

**Comment by lgfrbcsgo** [comment]
This might be helpful https://msdn.microsoft.com/de-de/library/windows/desktop/ms686219(v=vs.85).aspx
