### ISSUE TITLE
Reverted to v1.6.238.16010, a much better version than the most recent one

### ISSUE THREAD

**Issue by YNagato** [nefarius/ScpToolkit#445]
The ScpToolkit v1.7.277.16103-BETA is a huge regression.

1. It doesn't work with various built-in Bluetooth cards.
2. The game stops responding to the controller if I switch from wired to wireless connection or vice versa. Every time I have to quit and restart the game.
3. You have to manually uninstall the controller and dongle drivers.

I decided to revert to v1.6.238.16010 after getting no feedback to my reported Bluetooth issue. And all the three problems solved!
1. It works perfectly with my built-in Bluetooth.
2. The controller works seamlessly with the game even if I switch back and forth between wired and wireless connection.
3. Controller and dongle drivers can be uninstalled with one single click in the old ScpToolkit Driver Installer.

**Comment by nefarius** [comment]
Could it possibly mean that BETA indicates it's not stable, I wonder...
