### ISSUE TITLE
It works but kills embedded bluetooth

### ISSUE THREAD

**Issue by Zibri** [nefarius/ScpToolkit#446]
I don't know if it is a issue of this program or of libusb... but if I install the bluetooth driver, the DS3 works perfectly but bluetooth disappears from my system.. meaning I can only use it for the controller and not for other things.

**Comment by charlesmilette** [comment]
This is expected behavior

**Comment by Zibri** [comment]
so it's not possible to have also the normal functionality?

**Comment by charlesmilette** [comment]
No

**Comment by BananaAcid** [comment]
Yes. With a second USB dongle.
