### ISSUE TITLE
Change Controller slot

### ISSUE THREAD

**Issue by sueds** [nefarius/ScpToolkit#45]
Hi, 

On my computer I'm already using a xbox gamepad and I wish to add a ps3  gamepad but just for the second player. I guess I have to change the scp monitor project but I don't find any clue on how to do it. If could point me in the right direction that would be cool.

**Comment by nefarius** [comment]
This is currently not possible.

**Comment by mirhl** [comment]
You can adjust controllers order [with x360ce](http://pcgamingwiki.com/wiki/Xbox_360_Controller_Emulator#Unset_controller_from_first_player). 
And I'm not sure this is something better to be done on the driver level.

**Comment by nefarius** [comment]
This will be possible in the next release.

**Comment by mirh** [comment]
[XOutput](https://github.com/nefarius/ScpToolkit/commit/85cc28dd30ff9489da047b82f4b8cd7c743c307c) magic right?
Though, I still wonder: isn't controller slot something "system"-wide rather than "controllers"-specific?
Why changing this should be *conceptually* in the driver?

**Comment by nefarius** [comment]
It isn't and won't be possible to inflience which XInput slot the controller gets assigned because that's dictated by Microsofts `xusb.sys` driver alone. The bugyness with mixed controller environments will be solved though, that's why I commented on this issue.

**Comment by mirh** [comment]
Oh cool. 
Could that even help with #145 and #146 ?

**Comment by nefarius** [comment]
@mirh #145 is affected and fixed in the upcoming release, I'm still not sure what i can do about #146 though.

**Comment by nefarius** [comment]
Finally making use of those milestones :D

**Comment by charlesmilette** [comment]
Do you have an estimate for the release date of 1.7.x?

**Comment by nefarius** [comment]
@charlesmilette since this weekend got pretty much occupied with other stuff, I can release a beta hopefully within the following week or the upcoming weekend.

**Comment by nileplumb** [comment]
@nefarius Looking forward to it, have been checking the github commits for vbus and toolkit daily haha getting close it seems! Will be able to report issues in a 4 player environment on occasion too :)

**Comment by pnutus** [comment]
This issue is closed, but I can't find any info on how to change controller slots. Am I missing something?

**Comment by mirh** [comment]
As I said. Use x360ce.

**Comment by Zikasuo** [comment]
So My issue is kind of similar i have one controller and one keyboard and mouse. i want to use my keyboard and mouse for the player 1 slot and the controller as player 2. My controller is a ps3 dual shock 3 controller, and i only have one controller available. i have emulated it through x360ce and using SCP... but i'm only able to achieve the ability to control both on the controller. if i'm doing something wrong or there's an easier way to do this please let me know. thanks!

**Comment by mirh** [comment]
http://pcgamingwiki.com/wiki/Xbox_360_Controller_Emulator#Change_controller_slot

**Comment by Zikasuo** [comment]
I did that but since x360ce doesn't run my PS3 controller by itself I need SCP to detect it and then x360ce to map the controller

**Comment by mirh** [comment]
> I need SCP to detect it and then x360ce to map the controller

Exactly, so please stop commenting the driver.

**Comment by Zikasuo** [comment]
? Am I doin something wrong
