### ISSUE TITLE
After driver install touchpad is completely gone

### ISSUE THREAD

**Issue by JohnP80** [nefarius/ScpToolkit#450]
I was using the driver utility and when I hit install, the program did its thing and then it never finished. It said it would take up to five minutes, so I let it sit for ten or so. When I closed the program my touchpad just didn't work anymore. When I mean "didn't work" I mean that my mouse disappeared off of the screen and it just didn't exist anymore in the device manager. A quick response would be great, as I use this computer for college.

Hi, sorry. I just did some more digging and found a fix. Here's the link for anyone who has the same problem. [Link](https://github.com/nefarius/ScpToolkit/wiki/Manual-driver-removal)

**Comment by charlesmilette** [comment]
Have you checked every box when choosing the device to install?

**Comment by Sonickyle27** [comment]
Make sure when installing the drivers that you only select your controllers and your external bluetooth dongle. Selecting anything else will cause the device to no longer work. Don't tick everything.

**Comment by nefarius** [comment]
*Sigh*
