### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rojasmaia** [nefarius/ScpToolkit#458]
Hi! I've been trying to get this to work. I also can't check the Device's properties because nothing is listed. Any help would be appreciated! Thank you.

[ScpToolkit_Log-Package_ASUS PC_1474852953.zip](https://github.com/nefarius/ScpToolkit/files/492053/ScpToolkit_Log-Package_ASUS.PC_1474852953.zip)
![image](https://cloud.githubusercontent.com/assets/22436895/18819953/916705ac-83cb-11e6-811d-a14d77e93d5d.png)

**Comment by charlesmilette** [comment]
After installing the app, there's a driver installer to run. You'll find it under "ScpToolkit" in the start menu

**Comment by rojasmaia** [comment]
Yes, I did that the first time I tried to install. I already tried uninstalling and reinstalling. "Force Driver Install" takes ages (took 20 minutes and still nothing)
