### ISSUE TITLE
Not working (Update from Older version)

### ISSUE THREAD

**Issue by Reny900** [nefarius/ScpToolkit#459]
Trying to update from the 1.2.0.160 to the current one but it didn't quite well owrked out.
So there is this zip file created from your Info collecto, and i don't know why i can't post it here.
When i run the SCP driver installation (after the original.exe file installed in it's deafault directory) this is what it came up: [Using a PS3 controller and BT doongle BOTH plugged in when opening the program]
![ps3 bug](https://cloud.githubusercontent.com/assets/19189602/18824437/7c67912a-83c2-11e6-88e7-6491801e416d.JPG)

What should i do?

![pds3 bug 2](https://cloud.githubusercontent.com/assets/19189602/18824514/fbd0eb0a-83c2-11e6-8056-0d678525902f.JPG)

This is what happens when i plug it off and in again:
![plugin error](https://cloud.githubusercontent.com/assets/19189602/18824586/83bbf4b0-83c3-11e6-9483-3bc407ac598c.JPG)

**Comment by T-K-Martin** [comment]
If there was a Windows update for your system, roll it back and try again. I just had an issue after a Windows 10 build update and I got exactly the same error.

**Comment by Reny900** [comment]
No. I'm still using windows 7 and i'm still with the build. The only upgrade i did was from the 1.2 to the 1.6 of the SCPtoolkit
