### ISSUE TITLE
Bluetooth host uninitialization

### ISSUE THREAD

**Issue by mineiro** [nefarius/ScpToolkit#462]
Hi guys!

I have installed the toolkit, initialized the bluetooth host, installed the driver and the service.

Needing to remove the toolkit so I can use the bluetooth dongle again, I have wiped the installation (using the Wipe tool). But it didn't work.

I have tried uninstalling, installing again, uninstalling once more, but without success.

Can you provide me some guidance so I can uninitialize the host?

Keep up the good work!

Thanks!

**Comment by Percephere** [comment]
Go back into the driver installer, skip to the bluetooth section and hold it open there. Then go to the Device Manager and scroll down. Probably in one of the Universal Serial Bus sections should be a device labeled after the host in the driver installer. Right-click and hit uninstall. Then remove your bluetooth dongle and plug it back after a few seconds. The device should reinstall and return to default usability.
