### ISSUE TITLE
Sony Wireless adaptor

### ISSUE THREAD

**Issue by Silent1990** [nefarius/ScpToolkit#468]
Can you do a Driver for DS4 Sony Wireless adaptor?
I plugged in and it uses the default windows driver, when i checked in joy.cpl it shows as DualShock@4 USB Wireless Adaptor test is the aix and buttons work...all is good...but when i opened a game such as Fallout 4, Dying Light or No Man's Sky i don't get any input. The Games is supporting DS4 light bar and button prompts.
I was trying all:
-inputmapper(without x360 emulator and exclusive mode)
-DS4Windows(same as above)
-with  scp driver for bluetooth latest 
And nothing changed then i remove all of the app and driver and still nothing...

Can you do a emulator as the x360? i mean from DS4 wireless adaptor to DS4 wired mode that the Games supporting DS4 light bar and button prompts?
Here are some screenshots
![20161003_165629](https://cloud.githubusercontent.com/assets/22598595/19046918/ecc9199c-899f-11e6-9624-eb376d016f37.jpg)
[DS4 Adaptor.zip](https://github.com/nefarius/ScpToolkit/files/506791/DS4.Adaptor.zip)
[wired DS4.zip](https://github.com/nefarius/ScpToolkit/files/506793/wired.DS4.zip)

**Comment by nefarius** [comment]
[You could gift me one](https://www.amazon.de/gp/registry/wishlist/7B1BMHKGWI7X/) and I make a driver 😉

**Comment by Silent1990** [comment]
I don`t know how to do that because im from europe/germany.

**Comment by nefarius** [comment]
I'm from Europe, Austria 😆

**Comment by Silent1990** [comment]
Vom wo von Österreich kommst du denn?

**Comment by nefarius** [comment]
Oberösterreich 😄

**Comment by Silent1990** [comment]
Linz?

**Comment by nefarius** [comment]
Yepp

**Comment by Silent1990** [comment]
was brauchst du denn das ein treiber machst?(ich meine info von datei, oder)

**Comment by nefarius** [comment]
Ich brauch' entweder die Hardware selbst oder einen PC mit dem Ding angestöpselt auf dem ich meine Analyse-Tools starten kann.

**Comment by Silent1990** [comment]
duch den teamviewer ist das möglich?

**Comment by nefarius** [comment]
z.B. ja

**Comment by Silent1990** [comment]
ist ok windows 8.1 oder besser windows 10?

**Comment by nefarius** [comment]
Egal

**Comment by Silent1990** [comment]
668159453   Kennwort 7980

**Comment by nefarius** [comment]
Bist du Irre, poste sowas doch nicht öffentlich 😥 außerdem hab' ich den 10er lizenziert, 11er geht nicht.

**Comment by Silent1990** [comment]
wie soll ich dann senden den kennwort

**Comment by nefarius** [comment]
z.B. [hier](https://gitter.im/nefarius/ScpToolkit)
