### ISSUE TITLE
Can't seem to get the drivers to load

### ISSUE THREAD

**Issue by Kyujaku** [nefarius/ScpToolkit#469]
Currently using up to date version of Windows 10, and I get this in my log:

[ScpToolkit_Log-Package_Colin_1475560903.zip](https://github.com/nefarius/ScpToolkit/files/508741/ScpToolkit_Log-Package_Colin_1475560903.zip)

Trying to connect a Sony SIXAXIS PS3 remote to my computer through a USB cable, no BT dongle.
Anything someone can do to help would be greatly appreciated!
(My knowledge of coding and programming is very limited so I apologize if this is a simple fix)

**Comment by evildog1** [comment]
Have you selected your controller in Driver Installer?

![image](https://cloud.githubusercontent.com/assets/8687585/19315631/b9fe33ac-909e-11e6-9d69-b5a2da9eda8c.png)

**Comment by Kyujaku** [comment]
Yes I did, even tried to Force Driver install but it didn't help either.
