### ISSUE TITLE
Incompatible with other Xinput wrappers, like Touchmote

### ISSUE THREAD

**Issue by spinningacorn** [nefarius/ScpToolkit#471]
I'm not sure if this is an issue with ScpToolKit or with Touchmote, but since I've read the "skip occupied slot" function of the ScpToolKit still has issues, I decided to report this just in case.

I depend on ScpToolKit to use my DualShock3 as my main controller for most uses. Recently I tried to hook up a Wiimote through Touchmote, but the input mapping both use the same slot.

DS3 works normally if I close Touchmote (and turn the Wiimote off), and the Wiimote through Touchmote works normally if I turn my DS3 off, but together, they send input to the same Xbox Controller slot.
The inputs in the DS3 become intermittent (as if all buttons were turbo) when Touchmote is working, and the axis start to wiggle on the Xbox emulation of Touchmote when the DS3 is present.

As I mentioned, I tried enabling the "skip occupied slot" option, but it didn't work. Multiple ghost Xbox Controllers appear on my device list (four at the moment, but I only have 1 DS3 and 1 Wiimote connected. Something's buggy here). And yet, both devices still input to the same first slot. These ghost Xbox Controller do not appear con ScpMonitor either.

**Comment by rougetimelord** [comment]
Why do you need both connected at the same time?
