### ISSUE TITLE
fuck this

### ISSUE THREAD

**Issue by jasonh57** [nefarius/ScpToolkit#474]
I've been trying to install the driver many time but it always install my keyboard with my controller and when I try the controller don't work. I can say that Im a little mad after 3 time that I turn off my computer and I even reinstalled scp toolkit but no it doesn't work

**Comment by JoshWobbles** [comment]
You actually think thats how you should approach a developer? With a temper tantrum?

**Comment by nefarius** [comment]
Thank you for your message. Currently all lines are busy, your input is redirected to our complaint department. Have a safe and productive day.

**Comment by charlesmilette** [comment]
Brutal.
