### ISSUE TITLE
Issue when I restart my computer (Windows 10)

### ISSUE THREAD

**Issue by Alexander9515** [nefarius/ScpToolkit#475]
When I installed the controller and the bluetooth dongle it all worked, but everytime I restart my computer I have to uninstall and reinstall the controller and the dongle to make them work. How can I fix it?
[ScpToolkit_Log-Package_Alexander9515_1476616726.zip](https://github.com/nefarius/ScpToolkit/files/531801/ScpToolkit_Log-Package_Alexander9515_1476616726.zip)

**Comment by jang-u** [comment]
same problem
windows 7 64bit
ScpToolkit v1.6.238.16010
