### ISSUE TITLE
"B" (O) Button Not Working

### ISSUE THREAD

**Issue by domlee590** [nefarius/ScpToolkit#477]
For a while, the drivers worked flawlessly and without any problems, but after about a month, the "B" button on all 3 of my PS3 controllers stopped being recognized. I have used multiple USB cables, controllers, and driver installations. I have opened and examined all of my controllers, and all of them seem to have no issues (except for a joystick problem with one), and the "B" (O) button works fine on my PS3. Any suggestions?

Relevant Specs-
- MSI  Z97 Gaming 7 Motherboard (Using both USB 2.0 and 3.0 motherboard ports and case headers)
- Standard USB 2.0 Mini cables
- Windows 10 Latest
- Latest Xbox 360 Controller Drivers
- Newest Version of SCP Drivers
- Bluetooth not used, one controller with no master

**Comment by AppleNorris** [comment]
I have same issue, but with X (cross) button - windows 10 is not recognizing it on any of my controllers.
