### ISSUE TITLE
Stop ScpToolkit from running automatically on startup

### ISSUE THREAD

**Issue by figaw** [nefarius/ScpToolkit#478]
"ScpTrayApp.exe" runs on startup, and it seems there's no setting for this, in the settings.

**Comment by charlesmilette** [comment]
You can delete the startup shortcut, disable it in the Task Manager or just
uncheck tge tray app when you install Scp

**Comment by Jan200101** [comment]
As stated above you can disable it in the taskmanager on windows 10 and in the microsoft settings on windows 7 and below

**Comment by figaw** [comment]
Thanks, that was a really useful suggestion!
