### ISSUE TITLE
ScpToolkit is killing steam.

### ISSUE THREAD

**Issue by chris94oha** [nefarius/ScpToolkit#479]
Hey ho, 
I'm using a ds4 controller, which is connected via a USB cable to my PC. As soon as I connect my controller while steam is running, it just shuts down steam. If I have my controller connected before I start steam, steam just won't start at all. When I remove all ScpToolkit drivers and files it works perfectly fine. I even reinstalled windows today and it still happens (fresh install with a fresh ISO on a fresh 3.0 stick). I tried USB 3.0 and USB 2.0 ports, same results on both. I tried using an older version and I also tried to use the newest version, in total I tried like 6 versions of ScpToolkit, always ending the same way.

I'm Running Windows 10 build 1607

If system specs would be helpful:
i5 6600k
gtx 1060
16gb ddr4
Asrock Fatal1ty K4
120GB SSD for windows (i install ScpToolkit here)
1TB Drive for steam and other stuff.

**Comment by Jan200101** [comment]
no problem for me and judging on you closing the issue its fixed itself
