### ISSUE TITLE
Computer crashes after driver instalation

### ISSUE THREAD

**Issue by Sniperfyer** [nefarius/ScpToolkit#484]
I've used SCP for half a year or so to use my two PS3 controllers but now when I link them to the computer the entire system crashes and tells me there is a lack in IRQL. Please help[
[ScpToolkit_Log-Package_Jordan_1477101016.zip](https://github.com/nefarius/ScpToolkit/files/545542/ScpToolkit_Log-Package_Jordan_1477101016.zip)
](url)

**Comment by SouthShoreMedia** [comment]
I too have wondered about this.  I'm getting a similar windows 10 crash - it ends in a bsod or freezing. i just reinstalled my win10 system last night after months of issues.  i will be holding off installing this app to see if i experience the same issues.  last time i reinstalled windows and put all my apps back on, including this, the issues continued.  if i keep from putting scptoolkit in, i'm hoping i can narrow down the problem.
