### ISSUE TITLE
Disabling ds4 driver

### ISSUE THREAD

**Issue by EpicGamingVideos** [nefarius/ScpToolkit#485]
I use ds3 and also ds4 controllers at the same time, and i want to use ds4windows for the ds4 controller so that i cant use the touchpad. But if scptoolkit is installed ds4windows cant find my ds4 controller, only scp can. How can you disable scp toolkit for ds4 controllers?

**Comment by deadair3210** [comment]
Just don't install the ds4 driver when in the installer....

**Comment by EpicGamingVideos** [comment]
There is no such option in the new installer. Which is the last one where you can select it?

**Comment by EpicGamingVideos** [comment]
So i figured out a way. If the DS4 is not plugged in during driver installation, it wont install the drivers for it, and then DS4Windows works fine.
