### ISSUE TITLE
How to undo the changes to a controller?

### ISSUE THREAD

**Issue by Meksikietis** [nefarius/ScpToolkit#489]
I used ScpToolkit to change my wireless ps3 controller to a xinput controller whit a cable conection. It does work as a xinput controller but now if I want to use it as a ps3 controller it turns on the ps3 whit the home button but it only works whit the cable connected it doesn't work wireless anymore. How can i undo what the ScpToolkit did to the controller? I searched all the things that ScpToolkit came whit but was unable to find anything that would allow me to do it.

**Comment by Jan200101** [comment]
the changes where made to your pc just put the controller into the console over cable to make it work with it again.
