### ISSUE TITLE
Problem after controller disconnected

### ISSUE THREAD

**Issue by weihan1102** [nefarius/ScpToolkit#49]
The controller device (Xbox 360 Controller for Windows) is still attached to PC even my controller is disconnected.
This caused some problem in games like Fallout 4, the game thinks the controller is still connected and won't let me use the mouse and keyboard.

**Comment by Dodgexander** [comment]
This also becomes a problem if you use multiple controllers with ScpServer. For example if you plug in an xbox controller it is always player 2. What if you want the xbox controller to be player 1?

**Comment by nefarius** [comment]
This will be fixed in the next release.
