### ISSUE TITLE
I can't pair via Bluetooth

### ISSUE THREAD

**Issue by sylveon** [nefarius/ScpToolkit#497]
So I've got a new Intel Bluetooth chip (AC 3160) and installed ScpToolkit (the latest beta) on it.

Altough the controller (Genuine DS3) works via wire, it can't pair to the Bluetooth chip automatically. The pair button is also grayed out on the standalone server:

![image](https://cloud.githubusercontent.com/assets/6440374/19838363/0166400a-9ea4-11e6-9008-aa207f909a77.png)

**Comment by charlesmilette** [comment]
I just checked. It did got paired automatically, but it can't connect via Bluetooth.

**Comment by Box-Of-Hats** [comment]
Im also having this same issue

**Comment by googleygoggles** [comment]
Similar issue here, Intel AC 8260 WiFi and Bluetooth chip here... Seems to affect this series in particular. I just get Host Address <Error> instead and 4 flashing lights on my genuine PS3 Controller. My laptop's Bluetooth chip:

VID: 8087 PID: 0A2B

I have to constantly uninstall and reinstall the Drivers everytime I need to use it :(
