### ISSUE TITLE
Pressure sensitive patch not being applied correctly/faulty XInput1_3.dll file

### ISSUE THREAD

**Issue by prataczak** [nefarius/ScpToolkit#499]
I spent hours trying to figure this out. But if you specify a directory to patch with the ScpToolkit Settings Manager (using ScpToolkit v1.7.277.16103-BETA) to patch, pressure sensitivity is non functional, and it will break pressure sensitive functionality if it worked with a previous version.

The culprit is the XInput1_3.dll file. I know this, because I applied the patch with a previous version of the SCPToolkit to an alternate folder where PCSX2 had been installed, and it worked fine. I then moved the XInput1_3.dll file to overwrite the one that the the latest SCPToolkit installed, and everything worked.

Here is a screenshot of the kind of errors I was getting.

![57b55df0-9ee6-11e6-8b96-aff79b9e10ba](https://cloud.githubusercontent.com/assets/12243933/19866355/36be8762-9f76-11e6-9af4-d9f75c79123c.png)

**Comment by NomadGSF** [comment]
Mind uploading the working XInput1_3 file you used? I'm running into the same issue and Nefarious seems to have dropped support for this.

**Comment by prataczak** [comment]
Rename the file to XInput1_3.dll, had to do it this way to upload it.

[XInput1_3 - Copy.txt](https://github.com/nefarius/ScpToolkit/files/815723/XInput1_3.-.Copy.txt)
