### ISSUE TITLE
BT 000000 none

### ISSUE THREAD

**Issue by Abbieben** [nefarius/ScpToolkit#500]
I keep getting BT 000000 none error when i try to pair my gamepad with my PC, but it works well in USB mode, please can you release an update to correct this issue

**Comment by charlesmilette** [comment]
Not giving enough information and asking for a fix will lead you
nowhere. What's your Bluetooth dongle? Can we have a debug package?

2016-11-02 0:37 UTC, Abraham Ben-Obaje <notifications@github.com>:
> I keep getting BT 000000 none error when i try to pair my gamepad with my
> PC, but it works well in USB mode, please can you release an update to
> correct this issue
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nefarius/ScpToolkit/issues/500


-- 
Envoyé de mon Gmail

**Comment by Abbieben** [comment]
[ScpToolkit_Log-Package_Abbie_1478077550.zip](https://github.com/nefarius/ScpToolkit/files/566094/ScpToolkit_Log-Package_Abbie_1478077550.zip)
The attahed is a copy of my SCP debug log, 
I read somehwere that  a "modded SCPControl.dll" will allow Bluetooth communication with the fake DS3 pad, i tried it using it with the SCPdriver i got from here "http://emulation-general.wikia.com/wiki/SCP_Driver_Package" and it worked, but when i tried the same method with the SCPtoolkit, the SCPtoolkit driver instaler did not run, i guess due to the different version of the scpcontroll.dll. 
i hope you find this info useful for my problem

**Comment by Abbieben** [comment]
@charlesmilette i was hoping you will reply me

**Comment by charlesmilette** [comment]
Sorry.

Try installing the driver, then put the modded dll instead.

**Comment by Abbieben** [comment]
@charlesmilette it tells me to consult log for errors, with still no luck
[ScpDsxInstaller_Abbie.log.zip](https://github.com/nefarius/ScpToolkit/files/567078/ScpDsxInstaller_Abbie.log.zip)

is this project going to come with an update in the near future?

**Comment by charlesmilette** [comment]
After inpecting the log, I determined you have a Broadcom BCM2070 Bluetooth chip, which is totally compatible with Scp. The problem is, by logic, the modded DLL or the way Bluetooth works with your fake controller. Contacting the modder will provide you better help.
