### ISSUE TITLE
Change Host Address

### ISSUE THREAD

**Issue by TechnoDaft** [nefarius/ScpToolkit#506]
So I got 2 Bluetooth CSR dongles {for using mouth and keyboard on ps3 originally} but I got 1 hooked up to my PC and 1 hooked up to my kids pc and 2 ps3 controller but SCP shows the same host address on both pc's and most of the time both controllers want to connect to the same pc and i'm wondering if there is a way to change the host address so there isn't 2 difrent hosts the controllers can connect to with the same address....thanks
![image](https://cloud.githubusercontent.com/assets/20615768/20190877/2fc6f38a-a751-11e6-8867-6c851daee97c.png)

**Comment by charlesmilette** [comment]
Host address is tied to hardware. Generally, it is impossible to change it.
The best way to change it is to get a new dongle.

**Comment by TechnoDaft** [comment]
That's what I thought kinda retarded the dongles have the same mac -_- thanks tho

**Comment by TechnoDaft** [comment]
I bought the CSR8510 since it was compatible with Gimx and they said had the ability to change the mac address {which is why i guess they all had the same mac address} and figured out how to change it.
Had to uninstall the SCPtoolkit drivers then was able to use this tool **https://macaddresschanger.com** to change the mac address then reinstalled the drivers and everything is working fine now. Thank alot tho
![image](https://cloud.githubusercontent.com/assets/20615768/20195783/e737d930-a765-11e6-8156-b3f743b0927e.png)
