### ISSUE TITLE
Scptookit update check popup to hidden/background update

### ISSUE THREAD

**Issue by wudustan** [nefarius/ScpToolkit#509]
Would it be possible to move the update popup to a silent / background process that only alerts you if there is indeed an update, or give you the option to remove the pop-up altogether? Maybe add a Windows message instead? 
I feel like a pop up that takes me out of whatever I'm doing isn't the best way to tell me that there is, indeed, no update. I searched the issues and a similar question was closed on Jul 16th but the pop up is still very much there every time I turn my PC on.

**Comment by charlesmilette** [comment]
It ain't there anymore on the latest beta.
