### ISSUE TITLE
NEED ANSWER QUICK!!! Bluetooth Broken

### ISSUE THREAD

**Issue by MrBreadWater** [nefarius/ScpToolkit#513]
I figured out my problem, but I can't figure out how to delete this Issue.... so disregard.

**Comment by charlesmilette** [comment]
Did you installed Bluetooth on SCP also?

It's expected behavior.

[Do a clean wipe](https://github.com/nefarius/ScpToolkit/wiki/Manual-driver-removal) and install it without the Bluetooth drivers.

**Comment by charlesmilette** [comment]
Just press on the close button under the comment box to close it.

**Comment by MrBreadWater** [comment]
There is no close button.

**Comment by charlesmilette** [comment]
![image](https://cloud.githubusercontent.com/assets/6440374/20452589/7c4917c0-addb-11e6-8285-f133956aa4b3.png)

**Comment by MrBreadWater** [comment]
Oh.
