### ISSUE TITLE
Can't connect DS3 to Broadcom bluetooth 3.0

### ISSUE THREAD

**Issue by Fartson** [nefarius/ScpToolkit#519]
VID: 0A5C, PID: 2198

[ScpToolkit_Log-Package_Andrew_1479963994.zip](https://github.com/nefarius/ScpToolkit/files/610524/ScpToolkit_Log-Package_Andrew_1479963994.zip)

**Comment by DanHolli123** [comment]
try installing the custom driver for the bluetooth, keep in mind you will not be able to use it for anything but genuine ds3 and ds4 controllers
