### ISSUE TITLE
PS3 Controller joysticks are too sensitive // Move by themselves // Deadzone to remove Drift

### ISSUE THREAD

**Issue by EleBathory** [nefarius/ScpToolkit#522]
Hi,

PS3 Joysticks are too sensitive. Characters in games where joysticks are supported move by themselves.
When looking at Xinput Tester, LX/LY and RX/RY are moving a little back and forth.

Is there a different way to calibrate joysticks than through XBOX 360 Controller for Windows? If not, can these joysticks be disabled?

I am using original PS3 Controllers. These controllers are in good shape.

Here is the toolkit information that I am using:
![image](https://cloud.githubusercontent.com/assets/24213572/20652675/ad16a4ac-b4cb-11e6-9115-e04bd1879e97.png)

Thank you,

**Comment by Ybalrid** [comment]
Have you looked into the "deadzone" settings on the games you want to play? That's generally you can eliminate the problem this way.

**Comment by EleBathory** [comment]
Hi,

Thanks for your answer. However, I should have specified that I play fighting games like Melty Blood Actress Again: Current Code and Under Night In-Birth Exe: Late. They're similar to  Street Fighter in many ways. The first 2 games I mentioned do not have deadzone settings nor can I disable joysticks in them.

Thank you,

**Comment by EleBathory** [comment]
I found my answer with another GitHub app. See below

For Nefarious app, that would be amazing if Deadzone settings would be available through Xinput Tester or somewhere within the app SCPMonitor or SCPToolkit itself.

Thank you!!

(Answer to my issue)
https://github.com/KrossX/Durazno
Download: http://tiny.cc/magicaltools

On DL page, get this: 
![image](https://cloud.githubusercontent.com/assets/24213572/20735118/f281a748-b66b-11e6-84ba-8836c36a9dfa.png)

Follow readme file on first link, and you're good to go.
