### ISSUE TITLE
Wireless still working?

### ISSUE THREAD

**Issue by cherrytree98** [nefarius/ScpToolkit#524]
My controllers work fine, I have two of them connected, and I can turn them on and off without a problem, my issue is that the Bluetooth disappears and I cant use it with my wireless headset.

**Comment by DanHolli123** [comment]
if you don't already you need another bluetooth dongle/card for the head set as the bluetooth driver takes control of the selected dongle/card
it is expected behavior if you only have one bluetooth dongle/card but someone is working on allowing for both on one dongle/card
