### ISSUE TITLE
Working on USB not Bluetooth

### ISSUE THREAD

**Issue by DavoedM** [nefarius/ScpToolkit#525]
Hello, I have an official DS3 which is working via USB but not via bluetooth.

When on USB I have a playstation 3 controller and an xbox 360 controller showing in devices. On bluetooth none appear. I do get a message saying Genuine Sony Dual Shock 3 found but the controller does not work.

Can you help?

Cheers,
David
![usb](https://cloud.githubusercontent.com/assets/23000858/20814826/30047836-b813-11e6-86a8-47a791b2f05b.png)
![bluetooth](https://cloud.githubusercontent.com/assets/23000858/20814827/3009c1ba-b813-11e6-910f-0f64cf438abd.png)

[ScpToolkit_Log-Package_McColmsPC_1480630003.zip](https://github.com/nefarius/ScpToolkit/files/625856/ScpToolkit_Log-Package_McColmsPC_1480630003.zip)

**Comment by DanHolli123** [comment]
you need to install the custom bluetooth driver from the driver installer

**Comment by DanHolli123** [comment]
you may also need to reset the controller

**Comment by DavoedM** [comment]
Hi,

Thanks for the reply. I've tried a controller reset but it hasn't solved it. 

Where in the driver installer do I find the custom bluetooth driver? Ive been through all the steps, i.e initialising the controller, installing bluetooth hosts, installing the virtual 360 controller driver and the windows service.

There seems to be some bluetooth communication as when I unplug the controller and press the playstation button i get the "Genuine Sony Dual Shock 3 found" message but no controller appears in the devices menu.

Ive just notced another error that appears after installing the drivers and unplugging the controller "SCP Toolkit Warning --HCI_Connection_Complete_EV failed with status 10. Connection handle:0x000D"

Does that mean anything to you?

Cheers,
Dave

**Comment by binarycore79** [comment]
Having same issue with DS4. Help, please?
