### ISSUE TITLE
PS3 Controller not working.

### ISSUE THREAD

**Issue by Jazz218** [nefarius/ScpToolkit#526]
[ScpToolkit_Log-Package_Kostas2_1480679756.zip](https://github.com/nefarius/ScpToolkit/files/627078/ScpToolkit_Log-Package_Kostas2_1480679756.zip)
![image](https://cloud.githubusercontent.com/assets/24315822/20833264/7e03db38-b897-11e6-8cc3-bb4f11d0acce.png)
I have 2 ps3 dualshock sixaxis controllers and the one is working properly while the other can't.

**Comment by DanHolli123** [comment]
Did it work?

**Comment by Jazz218** [comment]
Νο, I tried today what you told me but still the one dualshock shows these errors...

**Comment by Jazz218** [comment]
So I changed the pcb of the one controller with the pcb of the other and both work now so problem solved!

**Comment by DanHolli123** [comment]
Great!
maybe close the issue since you solved your problem
hope you have no more problems either
