### ISSUE TITLE
Profile Manager Behaviour

### ISSUE THREAD

**Issue by PINCHO93** [nefarius/ScpToolkit#529]
So I tried to make R1 be Circle and Circle to be R1 (just swap around). But when R1 is Circle, then Circle will use the "new" mapping of R1, so it becomes Circle again. 

Tested this by mapping R1 to start, then Circle to R1, and it resulted in both R1 and Circle being Start. Weird behaviour.

**Comment by nefarius** [comment]
Please stop reporting issues about the Profile Manager; I shouldn't even have released it in the first place...

**Comment by DanHolli123** [comment]
It's the only reason I am using this is the hope that someone gets it working

**Comment by nefarius** [comment]
I'm not stopping anyone to contribute 😉
