### ISSUE TITLE
Change Pad ID

### ISSUE THREAD

**Issue by MacGyver1997** [nefarius/ScpToolkit#530]
Hello,

I have 2 Genuine Sony PS3 Controllers (1 Dualshock 3 and one just Sixaxis) connected via Bluetooth on my Computer.
Currently the Sixaxis is assigned to player 1, and the DS3 controller to player 2.
I've experiencing problems with Grand Theft Auto V, to recognize the Player 2 Controller. It don't react to any input. (This is not the Issue). In other Games it works normally!
So I wanted to switch the Pad ID of the DS3 Controller. In order to use the DS3 Controller as Player 1.
Is there any possibility available within the Toolkit, or do I have to uninstall everything an install it again?

(Sorry for the bad English!)
Appreciating your dedicated work!
Love this Toolkit!
Greetings

**Comment by Sorator** [comment]
Open SCPMonitor.exe (you may need to launch the .exe and then find the icon in your toolbar and click it to pull up the actual window) while you have both controllers on and connected (wired or via Bluetooth, doesn't matter). You should see both controllers listed, with an arrow next to pad 2. Click the arrow to move pad 2 to pad 1 and vice versa.
