### ISSUE TITLE
DS4 controllers won't connect

### ISSUE THREAD

**Issue by MasonBergstrom** [nefarius/ScpToolkit#535]
Been using this driver since before you even took it over and it's always been amazing. I used to stick to 1.5.5724 because I found it to be the most stable version with all the features I needed. After deciding to give the Steam drivers a shot I decided they weren't complete enough so decided to come back to SCPToolKit. Now I can't get any version of it to work. Tried my original version, tried the newest stable build and the newest beta and none of them are working correctly for me. 

I do clean installs each time, running the clean wipe utility and going through device manager and uninstalling all of the drivers for X360, Wireless Controller and my bluetooth adapter. I've even gone into C:/Windows/System32/drivers to delete the libusbK.sys driver and the ScpVBus.sys driver since they started causing my computer to blue screen and the wipe tool didn't seem to be removing them. 

It says it installs correctly each time but when I check in scpmonitor it just says charged or charging on the controllers that I have plugged in. The controller light flashes the charging yellow color once when first plugged in then it just goes dark. It doesn't appear to be repairing with the controller either since one of mine keeps trying to repair with my steam link if I turn it on when it's not plugged in.

Any support would be greatly appreciated, here's my debug files. 

[ScpToolkit_Log-Package_Mason_1481246688.zip](https://github.com/nefarius/ScpToolkit/files/640982/ScpToolkit_Log-Package_Mason_1481246688.zip)

Thanks.

**Comment by Revilo62** [comment]
Ignore me. The problem had to do with my setup. I run all of my peripherals through the USB hub on my monitor. That includes my micro usb cable and bluetooth adapter. As soon as I switched the adapter and cable to plug directly into my PC it started working again. I used to have it working through the monitors, not sure what happened. As long as it works now I suppose.
