### ISSUE TITLE
Mouse freeze after installing PS4 driver

### ISSUE THREAD

**Issue by i6alal** [nefarius/ScpToolkit#537]
my mouse freeze aftr i install the driver for ps4 controller via usb

![111111111111111111111111111111111111111111111](https://cloud.githubusercontent.com/assets/24474723/21046736/270ee2ca-be17-11e6-9a84-461e558b3572.png)

**Comment by BobBobbyBobbiny** [comment]
Try uninstalling the drivers, it worked for me

**Comment by Fred1rst** [comment]
Not for me :'(
Post solution if  [HERE](https://github.com/nefarius/ScpToolkit/issues/656) not related to backups and reinstalling windows please!
