### ISSUE TITLE
BSOD when installing bluetooth drivers

### ISSUE THREAD

**Issue by Cosile** [nefarius/ScpToolkit#539]
When I try to install drivers I get BSOD. 
I am trying to install them on Latop's Bluetooth.
Log is attached.

[ScpDsxInstaller_MyFirstUser.log.xml.txt](https://github.com/nefarius/ScpToolkit/files/643828/ScpDsxInstaller_MyFirstUser.log.xml.txt)

**Comment by curtiola** [comment]
I couldn't get controllers to connect with bluetooth using the SCPToolkit driver so my issue was a bit different but this is how i fixeed it lol I'm not sure if this will yield any different results for you, but it's not the same driver so you might get lucky, try this at your own risk though:

download the SCP-DS-Driver-package-1.2.0.160 from this website:
http://forums.pcsx2.net/Thread-XInput-Wrapper-for-DS3-and-Play-com-USB-Dual-DS2-Controller

once downloaded go into the ../bin/Zadig directory
opened the Zadig program, click device>load preset, load the "bluetooth" preset
then click options>list all devices, select your bluetooth adapter from the list and click "replace driver"
afterwards load the DualShock4/DualShock3 preset (whichever you want to use), go to options>list all devices, choose the controller and click "replace driver"
