### ISSUE TITLE
How to configure Profile Manager?

### ISSUE THREAD

**Issue by carlosrcjunior** [nefarius/ScpToolkit#540]
Hi, i just started to use this program. How i do to configure for example when i press triangle in my DS3 controller it should be ESC button(keyboard).
And i can`t access others menus like Axis Mappings & Settings, DS3 LED behaviour and others

**Comment by DanHolli123** [comment]
for the mapping:
1. Highly unstable profile manager included in the installer
   - No support
   - Free
   - Limited (if you can get it open)
2. JoyToKey
   - Free
   - messy UI
   - Highly customizable
3. Controller Companion
   - Paid (2.99 USD steam)
   - Friendly UI
   - Medium customization
with the lighting though you are limited to the setting manager
