### ISSUE TITLE
Impossible to start SCP DSx Service

### ISSUE THREAD

**Issue by TSlion** [nefarius/ScpToolkit#543]
Hi there ! 

I am using your excellent software for a while now and since I have my new PC, there is a problem with it.
I was able to install the driver to my controller and play with it. But yesterday, I took my controller and connect it to the PS3 of my brother. When I came back home, I tried to use it but it shows me some errors.

So I decided to install the driver again to the controller but I hade the "Oh Sh... A fatal error occured. Consult the log for details" message. I HATE THIS MESSAGE ^^

I tried some old versions, cleared my PC of all scp stuff (Revo uninstaller, registry...) installed the last version with ScpCleanWipe but still the same problem.

Now, I can see after some long hours of searching that the Scp DSx Service never starting. 
Tried Automatic (delayed), tried everything I saw on different topics in this site but never found a fix. 

I am desesparate man, please help me or I am gonna be crazy !

**Comment by TSlion** [comment]
OMG I've found it ! 
The problem came from a stupid thing... 

Right click on "ScpToolkit Driver Installer" **Properties** -> **Compatibility**
Then check "_**Execute this program as compatibility for**_" and then Select "**Vista (Service Pack 2)**"

That's it, all works fine !

**Comment by DanHolli123** [comment]
maybe close the issue then?

**Comment by TSlion** [comment]
Oh yeah you're right... Thanks !

**Comment by jxv16** [comment]
not works T_T
