### ISSUE TITLE
Programs don't detect PS3 controller after driver installation

### ISSUE THREAD

**Issue by jfredi** [nefarius/ScpToolkit#544]
I'm not the most tech savvy guy in the world so bear with me...

I installed the drivers for my PS3 controller at first with a bluetooth dongle, one built into my computer. It only seemed to work over a wired connection so I was disappointed and tried tinkering with uninstalling and reinstalling the drivers. Now when I connect my controller, it is detected (indicated by the scp notifications and custom LED setup on the controller) but when I try to enter steam Big Picture, it doesn't detect the gamepad. At this point I tried uninstalling and reinstalling the scptoolkit entirely via the setup.exe but when I reinstall, it loads up my previous configuration (not functional) and it's as if I never uninstalled. Any clues as to what I should do? At this point I'd just like to have the controller working via USB.

Any help would be greatly appreciated.

PS: I can find it in input tester and it detects inputs correctly, it's just that dolphin and steam don't detect the controller

**Comment by fjverhoek** [comment]
I have the same problem

**Comment by jfredi** [comment]
I found a solution!

What you need to do is first uninstall everything. This includes through the setup program, manually uninstalling the drivers via device manager (ps3 controller, virtual bus, etc.), and manually uninstalling the program itself by going through program files and deleting the Scarlet Crush Productions folder. After this I rebooted my computer, redownloaded the entire program/reinstalled and everything works now. 

I hope this helps you.
