### ISSUE TITLE
[feature request] disable service autostart, disable notifications

### ISSUE THREAD

**Issue by BlackDizel** [nefarius/ScpToolkit#551]
Need to add checkboxes to SCP Toolkit Settings Manager to implement features to disable service auto start on system boot and disable tray notifications.

**Comment by DanHolli123** [comment]
you can disable the auto start for the notifications, thus disabling them
Windows 10: open task manager, More Details (if in the simple view), startup, click on "scptoolkit tray notifications", then disable
Windows 7 and before: open the run dialogue (win+r), type in msconfig, click startup, select "scptoolkit tray notifications" and disable
8/8.1: one of the two above, I haven't used much of 8/8.1
