### ISSUE TITLE
Software breaks webcam/imaging driver

### ISSUE THREAD

**Issue by TheFresh16** [nefarius/ScpToolkit#554]
As mentioned in the title, installing the drivers actually removes the "imaging driver" from my device manager. When pulling up my webcam's camera, it says that it could not be found until after I uninstall the driver. Not a huge deal, but it would be nice to not have to swap back and forth! Thanks!

**Comment by DanHolli123** [comment]
have you tried only installing your controller and Bluetooth?

**Comment by TheFresh16** [comment]
Yeah I've tried that and various other combinations and the controller only seems to work when I install all of the drivers. Do you think "Force Install" would provide any different results? Thanks for your input!

**Comment by DanHolli123** [comment]
I don't think it would, but you can try

**Comment by DanHolli123** [comment]
another idea is to uninstall the camera from the scptoolkit in the device manager
