### ISSUE TITLE
Installation deletes my wireless driver + stops working after reboot

### ISSUE THREAD

**Issue by ToxicPotato** [nefarius/ScpToolkit#555]
The Toolkit is completely busted, I've tried both pre-release and the latest stable release, but it's causing way more trouble than it's worth. Overwrites/deletes my wireless card driver for no apparent reason and the whole tool simply just stops working completely after reboot, forcing another reinstall. If you need any other info to fix this, please just ask.

Going to go back to the deprecated SCP drivers for now, this is a major pain to try and use.

**Comment by DanHolli123** [comment]
use an external Bluetooth dongle, I had the same problem until I used an external dongle
