### ISSUE TITLE
Wired ds3 not working

### ISSUE THREAD

**Issue by Herminium** [nefarius/ScpToolkit#556]
After I using the beta installer, my ds3 worked for about a minute then it won't work anymore.
[ScpToolkit_Log-Package_Usuario_1482706151.zip](https://github.com/nefarius/ScpToolkit/files/672329/ScpToolkit_Log-Package_Usuario_1482706151.zip)

**Comment by Herminium** [comment]
Did not work, although, I'm having trouble with a wired controller

**Comment by DanHolli123** [comment]
you will need @nefarious's attention for this then, hope he checks
