### ISSUE TITLE
Scp Mapping Problem

### ISSUE THREAD

**Issue by MichaelTheKitten** [nefarius/ScpToolkit#557]
I have noticed im only able to access the buttons, i try to open another tab and it does nothing, i tried to reinstall it, it didnt fix, whats the problem here?

**Comment by MichaelTheKitten** [comment]
The area thats circled is the tabs that wont open 
![image](https://cloud.githubusercontent.com/assets/22221129/21499173/839bcd60-cc2b-11e6-9be4-080b8ba0b9d3.png)

**Comment by MichaelTheKitten** [comment]
if this is just because its unstable, just tell me and i will understand

**Comment by Hilleskog** [comment]
How did you get to that window you screenshotted?

**Comment by MichaelTheKitten** [comment]
![image](https://cloud.githubusercontent.com/assets/22221129/21543562/86077096-cdbf-11e6-9c2f-64438a3704d0.png)
