### ISSUE TITLE
New DS4 controller is not supported; Installer doesn't detect it

### ISSUE THREAD

**Issue by DryRoastedLemon** [nefarius/ScpToolkit#558]
The new Dualshock 4 controller (from the PS4 Pro) is not supported. If there's any info you want me to provide regarding the controller I'll be glad to help.

**Comment by pantra64** [comment]
duplicate of #493

**Comment by DryRoastedLemon** [comment]
Huh, a rather old issue then. Let's hope support gets added soon!

**Comment by dsrdakota** [comment]
I believe there's a new device id: USB\VID_054C&PID_09CC

**Comment by Genesis-Legion** [comment]
Any idea if this is something we can fix manually? or would a fix need to be added and recompiled?

**Comment by fklfkl** [comment]
I'd also like to report that a DualShock 4 with the above mentioned ID USB\VID_054C&PID_09CC is not detected by the latest installer.
