### ISSUE TITLE
Input delay on DS4 wired+bluetooth

### ISSUE THREAD

**Issue by timelf123** [nefarius/ScpToolkit#56]
There is a noticeable input delay when using my DS4 controllers and a clean install of SCP Server. ~~This does not seem to happen with DS4Tool wired.~~

Edit: I sometimes have this issue with Ds4Tool too, so it may be more generic.

**Comment by nefarius** [comment]
What version are you using? Is the delay measurable? I myself own and use a DS4 and I can't really tell a difference so I'd need more information.

**Comment by timelf123** [comment]
I'm not sure how you would go about measuring it precisely, but I'd estimate ~200-300ms at the worst, which translates to over/under-compensating with the joystick

**Comment by nefarius** [comment]
Ok that's awful; input updates occur *at least* every 10 milliseconds. I'm afraid I can't really help here since I'm not really convinced it's a software issue.

**Comment by nefarius** [comment]
This has long been fixed; there was a problem with the initialization of the DS4 setting the input update rate too low. Now it's set to a 1000 Hz by default.
