### ISSUE TITLE
Controller still not working even after the drivers were successfully installed

### ISSUE THREAD

**Issue by TheScorp** [nefarius/ScpToolkit#562]
I installed my ps3 controller using the ScpToolkit Driver Installer,  but after I tried using the controller (while it was still plugged in) it still didn't work. Do you have to use another 3rd party program for the controller to actually work or is something not working properly? 

Any help on this issue would greatly be appreciated.  
Thank you in advance!

**Comment by TyronePierce** [comment]
having same problem

**Comment by Kryshta** [comment]
Me too, on a fresh install of Windows 10 Enterprise.
