### ISSUE TITLE
Mouse and keyboard not working after restarting computer

### ISSUE THREAD

**Issue by GreekSomebody** [nefarius/ScpToolkit#565]
I downloaded this and tried to get my ps3 controller to work by restarting my computer, but when I restarted it, my keyboard, mouse, and wireless wifi aren't working... please help, I don't know what to do.

**Comment by VINOZZ** [comment]
Same Problem if you thound the issue please tell me i will be very thankfull if you do (please tell me fast)

**Comment by Wazbat** [comment]
When you install it it comes with a tool to clear up up the last remaining bits of the driver. Can you boot in safe mode and uninstall it? Or use a different keyboard? PS/2 or USB if it's a laptop?

**Comment by SterreStarGames** [comment]
how do you uninstall them in safe mode?
