### ISSUE TITLE
I have to install the drivers everytime I restart the computer

### ISSUE THREAD

**Issue by falselysentient** [nefarius/ScpToolkit#568]
It seems like the drivers reset everytime I restart my computer, because after the restarts if I try to connect the controller it doesn't work, and I have to install them again. How can I solve this? My PS3 controller is a bootleg, if that helps in any way. Thanks in advance.

**Comment by charlesmilette** [comment]
#51

**Comment by falselysentient** [comment]
What should i follow from there @charlesmilette ?
