### ISSUE TITLE
Installing PS4 Controller error

### ISSUE THREAD

**Issue by RapidEU** [nefarius/ScpToolkit#572]
Hi guys,

I follow each and every step that is indicated in the main section here,
Since I have PS4 Controller and I want to use it with through USB cable.
After installing the program, I go into the driver install program, and I choose Wireless Controller (VID: 054C, PID: 05C4), after installing that I open the ScpToolkit Monitor to see if it's connected and the Host Address shows an Error like in the picture

http://i.imgur.com/RjsPXuN.png

So I have no clue what I can do to get it working... any help?

Do I have HAVE TO use bluetooth for PS4 controller? I cant use a USB cable from my computer?

**Comment by marclundgren** [comment]
@RapidEU if you ever figure out how to use it as USB, please update this. I'm having the same problem as you
