### ISSUE TITLE
Problem during driver installation

### ISSUE THREAD

**Issue by Quetavian** [nefarius/ScpToolkit#578]
Hi everyone

When I'm installing the drivers, in the bluetooth initialize step, when I click on Initialize all connected devices as Bluetooth hosts, the setup shows this to me: 
![image](https://cloud.githubusercontent.com/assets/25041690/21824315/2ec58a4c-d77f-11e6-871b-e6f3d6849508.png)
I tried several times, uninstalling scp, skipping the initializing step for bluetooth (but, it doesn't work) and I don't know how to solve this problem.

**Comment by Quetavian** [comment]
I cannot upload the log... cause: 
![image](https://cloud.githubusercontent.com/assets/25041690/21824467/db65765e-d77f-11e6-8a39-7b3242ee95e7.png)
But I'm trying to upload the zip that the debug creates... I don't know what I'm doing wrong.

PD.- I apologize for my English skills, it's not my first language.

**Comment by charlesmilette** [comment]
@nefarius How funny. The error is "The operation completed successfully"

It seems that the installation actually worked, but the error catching in the installer needs improvements

**Comment by Quetavian** [comment]
The installation doesn't worked... I can't use the gamepad...
