### ISSUE TITLE
ScpToolkit Profile Manager: the problem with tabs.

### ISSUE THREAD

**Issue by NightW1nd** [nefarius/ScpToolkit#579]
Hi all, have a problem with Profile Manager. When the utility is started the "Button mapping" tab is opening by default. All another tabs cant be oppened. Looks like the utility absolutley doesnt care i m trying to open those tabs. Is there any idea how to fix it? I rly need to take access to axis settings tab.
P.S. Sry 4 my english. I know its terrible =)

**Comment by charlesmilette** [comment]
#429 perhaps

**Comment by nefarius** [comment]
It's intended behavior; the other tabs aren't implemented.
