### ISSUE TITLE
can't connect ds3 via bluetooth

### ISSUE THREAD

**Issue by sxd1140** [nefarius/ScpToolkit#58]
`Intel(R) Wireless Bluetooth(R)`
`USB\VID_8087&PID_07DC`

intel chip on board

thanks.

**Comment by alfredox123** [comment]
integrated bluetooth doesnt seems to work well with scp toolkit :S

**Comment by alfredox123** [comment]
try this https://www.youtube.com/watch?v=RuxXUKN1vz8

**Comment by Kamui-Solo** [comment]
For me it is worked until v1.5.5749.18036, next release already not work via bluetooth.

**Comment by alfredox123** [comment]
are you using fake controller?

**Comment by Kamui-Solo** [comment]
I use Defender GameExpert bt1 or it's original version "Warhorse zm390"

**Comment by sxd1140** [comment]
yes, i use controller not made by sony.
