### ISSUE TITLE
Led status Pad ID: 2 controllers stuck on Led 1

### ISSUE THREAD

**Issue by jacobmix** [nefarius/ScpToolkit#584]
I got 2 controllers, and they both show up in SCPMonitor.
But they're both on Led 1. I would like Pad 2 to have Led 2 light up.

Basic PC information: http://prnt.sc/dvzce2
Using: ScpToolkit v1.7.277.16103-BETA
Didn't see this issue posted anywhere else.
If any other info is needed i'm happy to provide it.

**Comment by axbmcuser** [comment]
Same here. Everything works fine with 2 DS3 via BT. But both are lighting up LED1. :-) Did you find a solution?
