### ISSUE TITLE
Drivers installed sucessfully, ps3 controller shows LED status but no inputs on Xinput tester/games.

### ISSUE THREAD

**Issue by squeakyrino** [nefarius/ScpToolkit#585]
I have a genuine PS3 controller, using usb (No BT).

I installed the drivers of the latest version (v1.7.277.16103-BETA), followed the instructions and everything said it worked fine. I restarted and my PS3 controller worked. After restarting again, it no longer recieves any input from the controller, however it still detects that a controller is plugged in and I can even change the LED status of the controller.

![image](https://cloud.githubusercontent.com/assets/25160630/21999213/da0dd7e6-dc30-11e6-9610-bb0ec65aefaa.png)

I do have to note that the battery of my controller is dead.

Xinput tester
![image](https://cloud.githubusercontent.com/assets/25160630/21999283/216e7eb0-dc31-11e6-9a75-5293b7a49c2a.png)

And the logs:
[ScpToolkit_Log-Package_squeakyrino_1484601518.zip](https://github.com/nefarius/ScpToolkit/files/709413/ScpToolkit_Log-Package_squeakyrino_1484601518.zip)

**Comment by Pav7300** [comment]
I have the same issue, except I was able to play for about 3 days before this happened...

**Comment by squeakyrino** [comment]
Today it worked again. I had the controller unplugged and I hear a pop out of nowhere. It said that the Scarlet Production Service was running. After that I tested and it worked. I have no idea what caused that service to start working now but it seemed to be the issue. Any ideas?

**Comment by squeakyrino** [comment]
It seems I have found a fix for this. 

1st. Check your services for the SCP DSx Service, like so:
![image](https://cloud.githubusercontent.com/assets/25160630/22174552/5307cd54-dfd9-11e6-8e1f-d865fc9fc7fd.png)

2nd. Go to properties and open this tab. 
![image](https://cloud.githubusercontent.com/assets/25160630/22174555/706f5bf0-dfd9-11e6-9216-ed08e0cc03fc.png)

3rd. Select "Restart this service" on first failed attempt.

It seems that the first launch of the service is failing and this forces it to restart after it fails. It fixed it for now but it might be worth knowing what's causing the service to fail in the first place.

**Comment by squeakyrino** [comment]
Now I have this error:

![image](https://cloud.githubusercontent.com/assets/25160630/22178110/631e5648-e026-11e6-8f83-f707a023c7e7.png)
