### ISSUE TITLE
Bluetooth Connection issue

### ISSUE THREAD

**Issue by nzejoe** [nefarius/ScpToolkit#587]
This method was best i have ever tried, but i have a little problem when ever i shutdown my PC. 
Each time  i shutdown and power on my PC it will not connect wirelessly and the SCP monitor shows error on the host address  unless i have to install the Bluetooth drivers again before it can connect  but it does connect with cable. Does it mean i have to install the Bluetooth drivers each time i power on my PC or it's my PC missing something? please help! 
THANK YOU

**Comment by charlesmilette** [comment]
#51

**Comment by nzejoe** [comment]
thanks man
