### ISSUE TITLE
Program worked fine yesterday, now my whole PC crashes (blue screen of death) on start up?!?

### ISSUE THREAD

**Issue by Rendabomb** [nefarius/ScpToolkit#589]
Hi,

I downloaded ScpToolkit yesterday to use my Dualshock 3 controller on my Windows 7 (64-bit) pc, and it worked fine. I installed all the drivers, and then chose to have the DS3 installed. As expected it showed up as an X360 controller under devices, got recognized by the emulator I'm using, and I played for a bit using the controller.

Today however, I connected the controller but immediately when the Scp Service booted up and 'connected' with the DS3 my whole PC crashed and I got a blue screen of death. What's going on? I rebooted my pc, now starting the program first before connecting the controller. Same result: crash & blue screen of death.

Then I decided to go for a clean install: I followed the guidelines here on the github and deleted everything, and downloaded the toolkit again. Installing the drivers went fine, but when I chose to install the specific DS3 again my whole pc crashed once more the second it was done.

What's going on here? A program like this crashing my whole fucking PC is weird enough, but the fact that it actually already did work yesterday is even weirder. Thanks in advance for any help.

EDIT: I installed the new ScpVBus as described here (https://github.com/nefarius/ScpToolkit/issues/239) since my problem looks a bit similar (on the blue screens of death I see something mentioned about a SysVBus or something), but it did not help. After installation the second I start the ScpService again my pc crashes within a second. I quickly managed to spot a notification from the service in the bottom right corner of my screen that said ''Fake controller detected'' in that one second though, maybe that's a hint to what's wrong? Just to make sure: I am using a normal official Dualshock 3. 

EDIT: I checked the BSoD more carefully and it is indeed the same thing as mentioned in the other thread above: ''DRIVER_IRQL_NOT_LESS_OR_EQUAL (ScpVBus.sys)''.

**Comment by gerciolisz** [comment]
Hi i have similar problem but in my case first thing is mouse is laggy and when i moving it, it make weird beeping sound. Few times when installing scp drivers again i had BSOD with this : driver verifier detected violation ScpVBus.sys...


[012617-5984-01.dmp.txt](https://github.com/nefarius/ScpToolkit/files/733940/012617-5984-01.dmp.txt)

minidump added just delete .txt

**Comment by LazorLord** [comment]
Have the same exact problem.

**Comment by gerciolisz** [comment]
If I remember right I made clean install on win 10 and everything was working again.. seems sth broken as I have ds3 using as Xbox pad via bt
