### ISSUE TITLE
Dualshock 3 controller not all buttons showing up in control panel controller map

### ISSUE THREAD

**Issue by Zyrixion** [nefarius/ScpToolkit#591]
The PS button on my Dualshock 3, while showing up in the input tester (which also seems to think my Dualshock 3 is a Dualshock 4?) and causing steam to pop up every time I press it, is not actually mapped as a gamepad button according either to control panel or XPadder.

**Comment by deadair3210** [comment]
New feature of steam, it will pop open if its running when you push the xbox guide button, which is what the PS button is mapped to. Its not a mapping issue, the steam controller grabs it when it sees the button and does its thing
