### ISSUE TITLE
Phantom Button Presses

### ISSUE THREAD

**Issue by persephone-labs** [nefarius/ScpToolkit#593]
Have used SCP to play Dark Souls: Prepare to Die in the past with my PS3 controller.  Recently re-installed everything to replay it and now I get phantom button presses in game all the time.  Like during the game my items or left/right hand items will change as if I were pressing a direction on the D-Pad that I am definitely NOT pressing.  This is on an updated Windows 10 machine.  Doesn't matter if it is over BlueTooth or USB it happens during both.  Un-modded Dark Souls.  Can't seem to figure out what the heck is going on.  Figured I'd report it, though.  Thanks for the project!

**Comment by georg1411** [comment]
I have the same problem, how to fix?
