### ISSUE TITLE
How to turn off vibration?

### ISSUE THREAD

**Issue by ArtuHxD** [nefarius/ScpToolkit#598]

**Comment by charlesmilette** [comment]
Most games have a setting for that. I don't recall it being disabled with
Scp

**Comment by Wazbat** [comment]
You can turn it off in the scp settings thing. I can't remember the exact name but the description says it will "ignore all rumble requests"

**Comment by mikegonzalez2k** [comment]
Open the Application: SCP Toolkit Settings Manager
Under Global Settings there is a checkbox to DISABLE RUMBLE.
