### ISSUE TITLE
Games/Emulators don't detect the controller

### ISSUE THREAD

**Issue by isoepic** [nefarius/ScpToolkit#602]
All my games/emulators aren't detecting the controller as a option for controls.
[ScpToolkit_Log-Package_1485365423.zip](https://github.com/nefarius/ScpToolkit/files/730480/ScpToolkit_Log-Package_1485365423.zip)

**Comment by Wazbat** [comment]
Is windows detecting it properly? In the "set up usb game controllers" thing. It should show as an xbox controller, then it should show inputs when you try to use it.
