### ISSUE TITLE
Could you just tell me what to do? Wrong Id?

### ISSUE THREAD

**Issue by lovetheories** [nefarius/ScpToolkit#603]
Short story:

If i have this? **USB\VID_25F0&PID_83C4&REV_0100** . Can't I use it even in wired mode? Why? Can someone which way I could make this fake controller compatible?

I have a DS3 BT controller [http://www.gioteck.com/wp/wp-content/themes/gioteck/images/products/vx2wireless-03.jpg](url) that I would like to use. It has no usb dongle, so it's full ps3. Amazon sent me wrong.

After install devices keeps changing all the time from ps3 to gioteck (endessly...). 

PS: If isnt so hard, tell me how to make it compatible? :/

**Comment by lovetheories** [comment]
Nobody?

**Comment by Wazbat** [comment]
Did you install a bluetooth dongle with it too?

**Comment by lovetheories** [comment]
Hello. Pleaseeeeeeeeeeeeeeeeeee.
Yes I did install it.
