### ISSUE TITLE
Afterglow controller 

### ISSUE THREAD

**Issue by BrassCat** [nefarius/ScpToolkit#610]
Hi my afterglow controller is a wireless usb type for the ps3 and it works perfectly on the pc other then the square and triangle buttons are switched and whenever it connects to the dongle and the pc it vibrates nonstop the switched buttons are simple enough for me to work around but does anyone know how to preferably get the rumble function to work or just to turn it off?

**Comment by Wazbat** [comment]
There's an option in the toolkit settings to ignore rumble requests
