### ISSUE TITLE
Keyboard disabled when I install a Dualshock 3 driver

### ISSUE THREAD

**Issue by Krysonox** [nefarius/ScpToolkit#612]
SCP has been working for me for ages but recently I tried to install some PS3 controller drivers and my keyboard got disabled, every damn time

**Comment by Verll** [comment]
Same thing is happening for me, I've done it right, only marked the playstation controller option when choosing where to install. It still disables my keyboard everytime, and then soon after the mouse. it's a wireless mouse+keyboard on the same usb. have to reboot into safe mode, and change port for keyboard to work again, and then clean wipe.
