### ISSUE TITLE
PS Button not detected

### ISSUE THREAD

**Issue by Random490** [nefarius/ScpToolkit#617]
I've been trying to get the ps button to work to open up steam while I'm not by my keyboard and mouse but the button isn't working. I've already disabled all the Xbox DVR stuff and when I go to the input detector nothing shows up for the PS button. 
![image](https://cloud.githubusercontent.com/assets/25576166/22634683/589c50d2-ebfa-11e6-9349-46bbb3389d28.png)

**Comment by Wazbat** [comment]
This is a Microsoft issue, not scptoolkit.
Windows DVR still uses it even when DVR is off. You need to turn it on again, open the game bar, click the setting cog, then untick the "use the Xbox button to open..." box.
Then you can also re-disable dvr

**Comment by Random490** [comment]
Didn't realize that you actually had to go into the game bar to turn it off, thank you.
