### ISSUE TITLE
DS3 is plugged in but not detected in the SCPinstaller.

### ISSUE THREAD

**Issue by vhosta** [nefarius/ScpToolkit#623]
Hello,

I had my dualshhock 3 controller working before. I then uninstalled the scptoolkit.

I then tried to reinstall everything and now nothing is working. I connected my DS3 to my pc, but the installer does not seem to recognize that it is connected because it won't show the option to install the drivers for the DS3.

Is there a way to fix this?

**Comment by thaleslipk** [comment]
run clean wipe utility uninstall and reinstall everything if you had problem with bluetooth try my modded ScpControl for 1.7.277 version if you need for some other just let me know but try mine below first.

**[Download the file Click Here!!](viid.me/qvnCas)**

If you want instructions just see my tutorial here #652
Bye, im glad if i can help.
