### ISSUE TITLE
OSX Version of ScpToolkit

### ISSUE THREAD

**Issue by Zero3K** [nefarius/ScpToolkit#629]
It would be nice if one were made so that way people with Macbooks, etc. can play games with a DS3/DS4 controller.

**Comment by charlesmilette** [comment]
[Only thing I like about macOS is that those controllers works natively](http://theultralinx.com/2014/02/connect-playstation-3-controller-mac-os-mavericks/)

**Comment by Zero3K** [comment]
Well, the one I have (a PowerA Pro Elite Wireless Controller), is detected by the OS but the LEDs on its center button keep flashing until it shuts off a few seconds later.

**Comment by Zero3K** [comment]
So, is it possible to get that controller to work properly when connected to Macs or not?
