### ISSUE TITLE
Controller recognized as player 2 controller on rocket league

### ISSUE THREAD

**Issue by Rerbun** [nefarius/ScpToolkit#632]
Controller works okay with pretty much every game but when I try rocket league it only wants to connect it as player 2. This didn't happen on first installation, just afterwards. All I do is run the SCPServer file when I connect the controller btw if that gives any clue.

**Comment by curz46** [comment]
Did you find a solution for this?

**Comment by Rerbun** [comment]
I am not sure, reinstalling might have helped or a complete clean install/update. I don't use it too often anymore so I don't even remember if it works now. I still see threads with the same problem popping up.
