### ISSUE TITLE
HEUR/QVM10.1.Malware.Gen in exe file ScpToolkit v1.7.277.16103-BETA

### ISSUE THREAD

**Issue by MauricioLucas** [nefarius/ScpToolkit#633]
https://www.virustotal.com/pt/file/da7b1aab547cac97047f705381d244bb53a8bac45581e0a897ab965cccecf538/analysis/1487483203/

**Comment by charlesmilette** [comment]
I've used the file myself and it's totally harmless. That is probably a false positive.

**Comment by nefarius** [comment]
![image](https://cloud.githubusercontent.com/assets/286631/23227854/ab9ddf1a-f93a-11e6-8d0c-e80caf4212e4.png)
