### ISSUE TITLE
DS3 detected as USB device, not game controller.

### ISSUE THREAD

**Issue by Razgriz01** [nefarius/ScpToolkit#635]
As the title says, the device manager has the controller in the Universal Serial Bus Device category, not as a game controller.  It's also listed as a "PLAYSTATION(R)3 Controller", not an Xbox controller.  When I look at the game controller window, nothing is shown.  I tried the fix for a similar issue, where somebody "updated" the driver software by pointing it to the Nefarius Software Solutions folder, however this didn't work for me, it just said it was already updated.  When I look at the driver info for it, it shows the Scp driver.    I'm on Windows 10 64bit, so I don't need to install the xbox controller drivers manually.  Any ideas?

**Comment by charlesmilette** [comment]
This is because that's how Scp works.

Something else prevents it from spawning a virtual Xbox 360
controller. Is the virtual bus and Xbox controller driver installed?
Is the server/service running?

-- 
Envoyé de mon Gmail

**Comment by Razgriz01** [comment]
Yes, the service/server is running.  Running as admin doesn't help the issue.  Windows 10 has the controller driver installed by default.

**Comment by Razgriz01** [comment]
I went and checked about the virtual bus driver.  I'm fairly certain that installed fine as well.  No errors came up during installation that I can recall.
