### ISSUE TITLE
Drivers not functioning on Windows 10 without disabling signature verification

### ISSUE THREAD

**Issue by kasanari** [nefarius/ScpToolkit#638]
Using the latest release (v1.7.277.16103-BETA) and an updated version of Windows 10 the program does not function (i.e. controllers not syncing) unless windows is booted with driver signature enforcement disabled.

**Comment by charlesmilette** [comment]
#266 DIsabling secureboot also fixes the issue. This is due to new requirements in the AU https://blogs.msdn.microsoft.com/windows_hardware_certification/2016/07/26/driver-signing-changes-in-windows-10-version-1607/

**Comment by Dienfive** [comment]
Hi @charlesmilette : Im using windows 7 64bit, already disabled secure boot, but driver still error code 52.
Please help me to check
