### ISSUE TITLE
ScpService.exe isn't starting (correctly)

### ISSUE THREAD

**Issue by JakeTheAvenger** [nefarius/ScpToolkit#641]
The "SCP DSx Service" that is (i think) supposed to start the "ScpService.exe" seems to not start after booting so I tried to start the Service manually and I just got the error message "Error 1053: The Service isn't responding to the start or control requirements in time" (starting the .exe doesn't work either). I figured out after using the repair tool the service starts and my bluetooth adapter works again. 
I hope someone can help me because it is slowly getting annoying :/

**Comment by silicator** [comment]
i have the same issue with starting scpservice! i got the path correct and service on auto. can i change the service-path maybe? would the "scpcleanwipe" help? dont want to destroy more...
