### ISSUE TITLE
Driver installer stuck

### ISSUE THREAD

**Issue by mtfck** [nefarius/ScpToolkit#643]
My issue seems to be a lot like Keefaetana's [issue](https://github.com/nefarius/ScpToolkit/issues/177). The driver installer simply gets stuck on the "Starting driver installation, this might take up to five minutes..." step. Reinstalling and rebooting did not help. Any way to solve this?

I'm also running Windows 10 x64.

Thanks

**Comment by mtfck** [comment]
Nvm I just needed to install without driver signature verification and it worked perfectly thank you.

**Comment by dill0wn** [comment]
Gah! I'm having the same issue, it persists even if I disable driver signature verification :(

**Comment by shahzaibjamal** [comment]
@dill0wn any luck with this issue. I also tried disabling driver sig verification but it is stuck there
