### ISSUE TITLE
Invalid Digital Signature Error

### ISSUE THREAD

**Issue by icykingler** [nefarius/ScpToolkit#647]
In the middle of installing the ScpToolkit v1.7.276.16101-BETA program, I get this error: 
http://imgur.com/nApu70P 

I'm running Vista SP2 64 bit

**Comment by curtiola** [comment]
you could disable digital signature requirements/integrity checks, if you're not tech savvy the easiest/safest way is to use this program: http://www.ngohq.com/?page=dseo

just read the page and download it at the bottom, and of course follow the instructions

**Comment by Geyup** [comment]
I got the same problem with trying to install ScpToolkit v1.7.277.16103-BETA on Windows 7 SP1 x64 Home Edition.

Can we please get this fixed?
