### ISSUE TITLE
cant play wireless

### ISSUE THREAD

**Issue by alfredox123** [nefarius/ScpToolkit#65]
i have a fake ps3 controller, on windows shows as "PS(R) Ga`epad"

i have a generic bluetooth dongle to but it installs drivers correctly and i can see mac address and i think is on the supported list

i can make it to work wired but not wireless

on scp monitor says it is reserved when is unplugged and in scpserver seems to connect but it says something about hic connection failed or something like that

i have ScpToolkit v1.6.133.15324 and in scptoolkit settings i enable the option of counterfeit controller, stills doesnt work wireless
![scpserver](https://cloud.githubusercontent.com/assets/13760359/11519393/07bd746c-986c-11e5-9815-c75eb0302290.jpg)

**Comment by alfredox123** [comment]
how do i look if my bluetooth dongle is compatible?

**Comment by Kalet** [comment]
Hi! I have the same issue here! Whenever I try to pair the Controller (DS3) the LEDs shut off and to the SCP Server shows the controller connected, but Windows 10 doesn't not recognize any button
PD:My controller is also a fake copy

**Comment by alfredox123** [comment]
i think scptoolkit doesnt support fake ps3 controllers wireless as for now :(

**Comment by Kalet** [comment]
The funny thing is that with an older versión it did work, but I was using Windows 7. I couldn't make any version work in windows 10 with my controller though

**Comment by alfredox123** [comment]
what version exactly did you use?

**Comment by nefarius** [comment]
1.2.x is Scarlett's version, not mine. Since it works entirely different I don't support it.

**Comment by Kalet** [comment]
Oh I didn't know! Anyways I can't make the controller work on the latest version here in GitHub, it looks connected to SCP Server its shows Bluetooth full but the LED in the controller shut off and windows doesn't recognize any button, only the PS Button is recognized! (It's odd because with cable it works just fine!)

**Comment by alfredox123** [comment]
i have windows 7 gonna test that version and see if it works wireless, are sure is that version?

**Comment by Kalet** [comment]
https://mega.nz/#!2Z9UQRiL!PKL5iS0aJj6dEvqyDhYDmkFx8fQgXY4rtVnbABRx49s I downloaded it from here!
