### ISSUE TITLE
Dualshock3 disconnecting while playing

### ISSUE THREAD

**Issue by Cooluser10** [nefarius/ScpToolkit#650]
Hello!

I have a super weird issue. I'll be playing Dark Souls for a bit and then the driver will tell me the controller is unplugged, then it takes awhile before it detects it again. The weirder thing is, if I play For Honor, the controller will disconnect on every input. Leaving it idle now, it hasn't disconnected itself at all. All this time I can confirm that my USBs are securely connected. 

Please help me, thank you very much.

EDIT: Managed to reproduce the For Honor bug in Dark Souls. Each time I enter combat, any button input will disconnect the controller.

EDIT #2: Here's a screenshot of the logs for the disconnection. Highlighted is when it occurs. It will disconnect then reconnect then it will loop in some disconnect and reconnect loop.
![ss](https://cloud.githubusercontent.com/assets/26023675/23340895/361a2e3c-fc79-11e6-804d-20038b702911.png)

**Comment by GrimOakheart** [comment]
I have the exact same problem. Can you reply to this thread if you find a solution? 

Ty in advance.

**Comment by Aya094** [comment]
By chance, when it disconnects does the control rumble? If so, try turning it off
