### ISSUE TITLE
USB logitech mic no longer working after installing ScpToolkit.

### ISSUE THREAD

**Issue by napwhile** [nefarius/ScpToolkit#658]
Went all the way back in the logs and didn't see anything about this issue. I'm using a Logitech USB mic, and it's no longer working anywhere after installing ScpToolkit (what I assume was correctly, as it was for my ps3 controller which now works flawlessly). Before SCP it was plug and play, no issues, installed its own drivers and etc.

This is the error that pops up when I plug the mic in;

<img src="https://i.gyazo.com/863881eb66e7dbc9015546391a9cf1d8.png">

**Comment by Fred1rst** [comment]
You probably unknowingly forced a ds3 driver install for that device.
I'm sorry for you i'm still waiting help for that issue.
