### ISSUE TITLE
Vac safe?

### ISSUE THREAD

**Issue by MakkaraMasa** [nefarius/ScpToolkit#664]
So I installed your program and now I'm curious that is it Valve Anti Cheat safe? Like if I use it I will not get banned from games that have Valve Anti Cheat? Thank you from answering!

**Comment by Zero3K** [comment]
You shouldn't since all it does is replace the default gamepad driver with its own.

**Comment by MakkaraMasa** [comment]
So basicly I'm safe? :D

**Comment by MakkaraMasa** [comment]
(sorry for bad english, drunk af atm)

**Comment by Zero3K** [comment]
Yes, you are safe.

**Comment by MakkaraMasa** [comment]
Cool to hear! Thanks for the answer!
