### ISSUE TITLE
cant install Driver on 3rd party DS3 Genuine controller

### ISSUE THREAD

**Issue by LucaSoranota** [nefarius/ScpToolkit#666]
im using hori gem pad 3 DS3 (http://www.play-asia.com/the-idolmster-cinderella-girls-controller-for-playstation-3-love/13/708sg5)controller. and after i plug in my controller the driver installer cannot detect my DS3 and when im using the old ones(the one that can choose which controller you want to install) it detect as a genuine DS3 controller but cannot register any key except when i press square the input register are going crazy..

i need help :(

**Comment by LucaSoranota** [comment]
[PAD A_hid-report.dump.txt](https://github.com/nefarius/ScpToolkit/files/836253/PAD.A_hid-report.dump.txt)

that is the report from the gamepad analyzer..

**Comment by Zero3K** [comment]
Oh, it seems like you're having the same issue as me. Except I had to manually add the MAC address and Hardware ID to ScpControl.ini in order for it to be detected as a Genuine DS3 controller.

**Comment by LucaSoranota** [comment]
the thing is i even cant install the driver because on 1,7 my devices wont show.. i tried to find a fix and alternative about 4 hrs ago until now
