### ISSUE TITLE
Ps3 controller, motion sensor issue

### ISSUE THREAD

**Issue by On1ck** [nefarius/ScpToolkit#672]
Hi there, 
the issue is, while using my ps3 controller for a fighting game, whenever I shake the controller too much it makes random inputs in the game and it ruins the whole experience for me. 
Has anyone fixed this issue before? 
Need help. Thanks!

**Comment by Kinsoku** [comment]
I had the same problem with one of my controller and the cause may be the same. I solved it thanks to this video since it seems a common problem of ps3 controllers : [Video](https://www.youtube.com/watch?v=FXdSvUkkN58)
