### ISSUE TITLE
Keyboard + Mouse As Player 1 (Controller As Player 2)

### ISSUE THREAD

**Issue by olivercool103** [nefarius/ScpToolkit#673]
I have a few games in my steam that are party games, games that have multiplayer local in them. My friends are controller over mouse but I am the exact opposite. So I use the keyboard and my friends use the controllers just fine (PS3 Gamepad). The problem is that mouse is player one and one of the gamepads is player one so we have to do a little fiddling with swapping in and out to get the player order right. If I can assign my controllers to be 2, 3, 4, my keyboard and mouse will automatically be assigned to player 1. In the SCP Monitor, you can only swap gamepad numbers between gamepads, you cannot have a player one controller. If there is a way to accomplish what I am explaining, it would lessen the time it takes to set up a game with my friends.

**Comment by ArtuHxD** [comment]
i need this too
