### ISSUE TITLE
Controller never stops vibrating

### ISSUE THREAD

**Issue by Xero99** [nefarius/ScpToolkit#681]
Help me. Every time I install drivers with ScpToolkit my joystick never stops vibrating. How can I fix it?

**Comment by First-NameBasis-TT** [comment]
Same with me but only when i try to install it as a ps3 controller. 
I wanted my controller to move like an analog stick but maybe there's another program i can use that's a bit more...friendly to third party controllers?
i just uninstalled everything after diddling around for like 3 hours.
