### ISSUE TITLE
Can't Use Mouse or Keyboafd

### ISSUE THREAD

**Issue by owenbick** [nefarius/ScpToolkit#687]
I've done the manual fix, the clean fix, uninstalled the program, reinstalled, uninstalled again, removed the drivers, rebooted, and it's managed to disable 2 keyboards and 2 mice.

**Comment by Fred1rst** [comment]
Plug in all of your corrupted devices, go to device manager, uninstall everything that is in "libsubk"
Did all you did but the HIDs need to be plugged in.
Tell me if it worked please!
#656

**Comment by owenbick** [comment]
Tried that. Did nothing even after the software is uninstalled.
