### ISSUE TITLE
SCP Disabling Keyboard and Not Showing Controller

### ISSUE THREAD

**Issue by KregoryHaus** [nefarius/ScpToolkit#688]
Whenever I try to install the drivers it doesn't show where my controller is plugged in and if I don;t select anything it just disables my keyboard and I can only use the controller if I plug it directly into the usb port on the keyboard itself. (I have a razer black widow ultimate) These drivers worked before on other computers, I don;t understand why I'm having all these issues now.

**Comment by Fred1rst** [comment]
Plug in all of your corrupted devices, go to device manager, uninstall everything that is in "libsubk"
Did all you did but the HIDs need to be plugged in.
Tell me if it worked please!
#656
