### ISSUE TITLE
Problem with switching Controllers (2x DS3 recharging circle)

### ISSUE THREAD

**Issue by skite2001** [nefarius/ScpToolkit#69]
Hello, i got some controller issues and maybe it could be improved in some way.

I own 2 PS3 DS3 Controllers. 
I set 1 controller on my PC for recharging and use the other DS3 for my PS3 until it's almost empty. After that, i change the controllers (fully loaded from my pc to ps3 and changewise). After changing the ds3s i had to open the "ScpToolkit Monitor (legacy)" and had to switch the controller configuration.

Isn't there an easier way for doing this? like using some disconnect button for the active controller -> replug the other one -> set automatically as contoller 1?

**Comment by nefarius** [comment]
This is resolved in the upcoming release.
