### ISSUE TITLE
Scp installing extra drivers

### ISSUE THREAD

**Issue by I-Need-A-Username** [nefarius/ScpToolkit#690]
I had the issue many people have had where Scp overwrites the keyboard and mouse, but I got past that. However, after the clean wipe I did, I had to reinstall the driver for my PS3 controller. When I have the driver installer open, I uncheck everything except "Install DualShock 3 driver," and under that, I uncheck everything except "PLAYSTATION(R)3 CONTROLLER." However, when I run the installation, my keyboard stops working. That's because in device manager, I see that it installs "USB Keyboard (Interface 0)" in addition to the Driver for my PS3 controller even though I clearly have that unchecked in the installation. Then, when I use the Driver Installer to uninstall the Keyboard Driver, it works, but it also removes the driver for my PS3 controller. I have done a clean wipe, uninstalled ScPToolkit, reinstalled it, and the same issue keeps happening.
Update: I have also tried running the driver installation with my keyboard unplugged. Then it just decides to install the driver that makes my mouse stop working instead. And I can't unplug them both and run the install, since I would have no method of input to my computer.
Update: I grabbed a second mouse, unplugged my mouse and keyboard, and ran the installation the same way. This time, the "802.11 WLAN Adapter" driver installed, essentialy overwriting my Wi-Fi adapter and cutting off my internet access entirely.
Update: You can guess where this is going. Unplugged mouse, keyboard, and Wi-Fi adapter. This time, there were no secondary installations that I expressly did not ask for. Which is nice and all, but my controller still doesn't work.

**Comment by Tabledude** [comment]
Same thing. Keeps overwriting my NETGEAR wifi adapter and cutting me off the web before I even go into the driver installer. It seems to mess with drivers before you even select anything, which is messed up. 

Its a shame.
