### ISSUE TITLE
Does not let the controller be used even thought its connected

### ISSUE THREAD

**Issue by Megaxron** [nefarius/ScpToolkit#692]
The controller never shows up in the monitor, the Scp Server shows that a controller has connected but nothing happens as a result of that.

[ScpToolkit_Log-Package_Troy_1491437018.zip](https://github.com/nefarius/ScpToolkit/files/902275/ScpToolkit_Log-Package_Troy_1491437018.zip)

**Comment by silicator** [comment]
same here, neither with client nor service in monitor.  i assume the biggest problem in all of the issues seems to be the scpvbus.sys driver (tried it with cleanwipe and cmd disabled violation check and testsign on)
