### ISSUE TITLE
Urgent, keyboard and mouse not working

### ISSUE THREAD

**Issue by arcadra123** [nefarius/ScpToolkit#696]
I installed the drivers and installed them over my keyboard and mouse and other USBs, managed to navigate to services for the clean wipe but I didn't see any SCP program there. Please help. I've tried uninstalling and reinstalling my keyboard driver but it did nothing except make my mouse unusable too. I literally cannot do anything except turn my PC on...

**Comment by Just4lol** [comment]
Hi.

Just plug in another mouse and do a clean uninstall all with the ScpToolkit installer. After that you will need to unplug them afther another instalation.
