### ISSUE TITLE
Everything worked, should be an easy fix.

### ISSUE THREAD

**Issue by ps3controllerhelp** [nefarius/ScpToolkit#711]
I have installed all the drivers and set everything up with all the correct messages working, but how do I start using the controller?

**Comment by DarkMatterMatt** [comment]
Have you followed the instructions here: https://github.com/nefarius/ScpToolkit/blob/master/README.md#installation-how-to

Make sure you have paid attention to Step 1, 

> Connect your Dongle (only needed if you want to use it wirelessly) and controllers (yes, all of them) via USB and let Windows install its default drivers. Leave them plugged in during the entire installation process

After that you should be able to
 - Connect your controller via USB and use it
 - If you installed the bluetooth dongle, press the PS button on the controller to connect it. You will need to connect it via USB at least once (it should have already paired during the driver installation, but try it again anyway)

You can test if your controller is working by running `SCP Toolkit Monitor (legacy)`. An icon will popup in your system tray. Right-click it then "test input"
