### ISSUE TITLE
Recent windows 10 update has made my ps4 controller not work

### ISSUE THREAD

**Issue by SuperGreggJr** [nefarius/ScpToolkit#712]
In games other than games with controller support, my ps4 controller has had no input whats so ever. Pls help

**Comment by rolanie3** [comment]
The same thing happened to me. I got it to work by following these steps:

1. Run ScpInstaller.exe, and uninstall everything
2. Restart PC
3. Plug in all devices (DS3/4 + BT Dongle), let Win10 install it's own drivers.
4. Run ScpInstaller.exe and install the appropriate drivers
5. If a DS3 connects but a DS4 won't, open SCPSettings.exe and go to DualShock4 Specific and ensure "Always re-pair controller on Usb connection" is checked. Then plug in the DS4 via USB, allow it to connect and try wirelessly again.
