### ISSUE TITLE
bluetooth address turns into "ERROR" after shutting down

### ISSUE THREAD

**Issue by g819072586** [nefarius/ScpToolkit#718]
Eeveytime I shutdown my computer,the BT address will be ERROR. So It's impossible for me to connect my DS3 gamepad via  BT to my computer.
However,If I restart my computer without shutting it  down,the address is still correct.

**Comment by natuan814** [comment]
Hi @g819072586 

I encountered the same as yours. Have you fixed this issue ?
By the way, which version scptoolkit/OS are you using ?

**Comment by g819072586** [comment]
@natuan814
NO,I have give all it up
