### ISSUE TITLE
windows 1703 problems.

### ISSUE THREAD

**Issue by TristisOris** [nefarius/ScpToolkit#719]
![default](https://cloud.githubusercontent.com/assets/1270117/25098132/1551de8a-23b0-11e7-805b-69ef78d85e3c.png)
![default](https://cloud.githubusercontent.com/assets/1270117/25098139/1e80b26a-23b0-11e7-87e0-6711ade336e4.png)
![default](https://cloud.githubusercontent.com/assets/1270117/25098229/7244b5e0-23b0-11e7-8440-929792b9a482.png)

**Comment by DarkMatterMatt** [comment]
I don't think the drivers will ever be signed. You can avoid this error by following the steps linked below.

https://www.drivereasy.com/knowledge/solved-windows-requires-a-digitally-signed-driver/

Simply Google `a digitally signed driver is required` and the first result is the solution.

**Comment by TristisOris** [comment]
yep, it helps, partially.

Another trouble with SCP service registration - it doesn't start. I reinstall program in safe mode with disabled driver signature verification - it works.

But it doesn't work without safe mode. 2-3rd screenshots.

**Comment by TristisOris** [comment]
disabled secure boot, usual windows start.

ScpToolkit Settings Manager begin work - before, not.
SCP service don't started automaticaly, but manualy i finaly run it.

![default](https://cloud.githubusercontent.com/assets/1270117/25112252/c8b309d4-23f8-11e7-8325-1f369f95be6d.png)

Looks like problem is solved.
So, 1st trouble - secure boot. 2nd - driver signature.
