### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by dogtorque** [nefarius/ScpToolkit#727]
I noticed that rarely scptoolkit will have a memory leak. and the only way to stop the memory leak is by shuting down the program through task manager. this has only happened twice now in the span of 2-3 months and I don't know exactly what causes it but I thought I would let the devs know.
I'm using scp driver installer 1.6.238.16010 and I'm using windows 10 (10.0.14393.0).
the second memory leak was actually bad enough to cause the pc to stop sending signals to the second monitor and not recognise it and I had to restart the computer because I couldn't acces task manager because it was on the second screen. everything is working fine now but it is still really concerning.

**Comment by dogtorque** [comment]
I just found out that if you put the computer into sleep mode enough then the program will eventualy have a memory leak.

**Comment by prkiso** [comment]
I have a similar issue - posting here in the belief that the two are interconnected.
I have noticed that when I leave my computer running for quite a while (~24 hours), SCPToolkit ends up consuming 4GB of memory. The CPU usage is similar for some reason also.
