### ISSUE TITLE
Playstation Button Not Working Steam

### ISSUE THREAD

**Issue by benjaminhallock** [nefarius/ScpToolkit#731]
MotionJoy had no problem pulling up steam overlay with ps3 controller. SCP just attempts to activate some xbox overlay feature with windows... not sure how to remap.

**Comment by deadair3210** [comment]
Has to do with differences in how MotionJoy works compared to ScpToolkit, just disable the Game bar and the playstation button should go back to acting like it should

**Comment by benjaminhallock** [comment]
NOpe didnt work,.
