### ISSUE TITLE
I really messed up and need immediate help! All USB ports are broken

### ISSUE THREAD

**Issue by Bastianvk10** [nefarius/ScpToolkit#734]
as i downloaded it and was ready to set up my driver, it asks what USB ports i want it to download it on. So i was an idiot and clicked them all. And after the download of the drivers, it seems that it had deleted every other devise driver too. I can't use my mouse or keyboard. Doesn't matter where i plug my keyboard and mouse, they don't work now. Please help.

**Comment by Arcterion** [comment]
I experienced the same problem yesterday, going through the manual driver removal fixed the problem for me.

https://github.com/nefarius/ScpToolkit/wiki/Manual-driver-removal
