### ISSUE TITLE
installation result: WDI_ERROR_OTHER

### ISSUE THREAD

**Issue by benja1747** [nefarius/ScpToolkit#758]
hi, im trying to use my ps3 controller(original) on my pc but i get the above message during the driver installation, and also my controller is turned off, and you cant see it if you go check the scptoolkit monitor.my os is w10 pro 64bits, and under the devices and printers section i have confirmed that my controller is using some microsoft drivers and after running the scptoolkit driver those microsoft drivers remain unchanged, despite the fact that eve already disabled the enforcement of signed drivers, i also noticed that when i connect the controller 4 lights flash for a while and then they turn off and wont light up again. please help my fix this problem, ahead there will be some screenshots of the installation log and my ps3 drivers.
![image](https://cloud.githubusercontent.com/assets/28695564/26039983/f3a39b4e-38ee-11e7-98cf-bdf959add6bf.png)
![image](https://cloud.githubusercontent.com/assets/28695564/26039996/1afb1352-38ef-11e7-8043-de4e2c799cf6.png)
![image](https://cloud.githubusercontent.com/assets/28695564/26040002/2bf5dd72-38ef-11e7-8786-00cb5a12b914.png)
![image](https://cloud.githubusercontent.com/assets/28695564/26040008/3da3f734-38ef-11e7-8a8e-6df9cfa1cebd.png)

**Comment by benja1747** [comment]
update: at the end i could´t find a solution to this problem, what i can tell though is that it had to do with drivers, the root of all this begun when my pc started recognizing the ps3 controller as an unspecified device and the drivers were some "libusbK" ones that apparently come with the toolkit but for some reason were working bad, i was able to update drivers from the ones my pc had and use microsoft ones, this made my pc recognize the controller again as such, and even games would recognize the controller was plugged in, but there was a problem lingering in the background that i could not identify that didnt allow the controller to send any inputs , rendering it useless, in the end i did a fresh install of windows 10 on my pc, formating the old partition in the process and set everything up from scratch and now it works just as it used to do before all this, hopefully the devs will look at this issue so nobody has to go to the same lenghts as i did to fix it.

**Comment by Geowil** [comment]
Having the same problem with Vista 32-bit (fresh install).  Started vista in disabled driver-signing mode, everything loads correctly until it starts installing the driver.  It churns for a while and then spits out the above WDI_ERROR_OTHER error.
