### ISSUE TITLE
ScpVBus: Driver signing no longer valid according to W10

### ISSUE THREAD

**Issue by JoshWobbles** [nefarius/ScpToolkit#759]
Driver certs need to be updated

**Comment by Dienfive** [comment]
@nefarius please take a look!

**Comment by Dienfive** [comment]
Hello @JoshWobbles @nefarius follow steps in this link, disable signature requirements, then no issue on signature!!!

https://www.wintips.org/how-to-fix-windows-cannot-verify-the-digital-signature-for-this-file-error-in-windows-8-7-vista/

**Comment by sollano** [comment]
I share this same problem, and I really don't want to disable secure boot to install this. I wish there was another way to solve it!

**Comment by nefarius** [comment]
@Dienfive No
@sollano there will be.

**Comment by sollano** [comment]
@nefarius Thanks Man, glad to know. For the time being, if I restart with the special option to disable digital signature option, everything works fine with the latest release. So I'll just hang on until the next update.

**Comment by cloud1250000** [comment]
is the update coming any time soon? I'm about to reinstall scptoolkit because it stopped working after the creator update.. should i wait for it? :D

**Comment by Dienfive** [comment]
hello All, do you guys have any news?

**Comment by JoshWobbles** [comment]
@cloud1250000 Your issue was unrelated, this issue is regarding expired signing.

**Comment by Dienfive** [comment]
Hello All,

Still not had good news...

**Comment by Dienfive** [comment]
has been waiting.... i can not disable secure booth pernamently, so everytime starting windows, i need to disable it and reinstall SCPtoolkit, nightmare!

**Comment by WilliamFeely** [comment]
If you have an earlier licensed version of Windows install that then upgrade to 10.  This will put your OS in a "grandfathered" status authorized to load the driver.
As another mitigation if you can disable Secure Boot in the BIOS this will also ease the restrictions.  Just make sure if you use Bitlocker with a TPM chip that you pause protection before changing any BIOS settings or you will be forced to enter your recovery key.
