### ISSUE TITLE
Please Help!!!!

### ISSUE THREAD

**Issue by TalonXfirePC** [nefarius/ScpToolkit#762]
I've just installed the driver and done everything to my knowledge,
but when choosing the drivers to install, I don't see my dual shock 3 anywhere for selection!
I have it connected to the front panel of my PC going into a USB 3.0 port,
But I don't know why it won't read the Controller anywhere!

Please help!!!!

**Comment by UtkuCQ** [comment]
Yo did you already get this fixed? ( I hope so, since it was 16 days ago ) or do you still need help?
