### ISSUE TITLE
How do you... start the service after you reboot?

### ISSUE THREAD

**Issue by Markeron** [nefarius/ScpToolkit#767]
Tray notifications is sitting there, isn't that supposed to start the service? do I have to install the driver every time I want to start up?

**Comment by nefarius** [comment]
No and no, it's supposed to auto-start. That's why it's a service...

**Comment by jacobmix** [comment]
Even tho i've made sure that the service "services.msc SCP DSx" is to automatically start.
It doesn't seem to sometimes. Or maybe just crashes?
![SCP Service.msc](https://cloud.githubusercontent.com/assets/5995327/26456357/160e9996-416d-11e7-85db-838add95dc3e.png)
I have a [shortcut](https://docs.google.com/document/d/116LwfIM6evk4Dy89N1EQjGYVbcgdIX3cHE8CIR1pflk/edit?usp=sharing) to start it easy, and quickly manually tho.
Hope this helps you start the service easier after boot.
