### ISSUE TITLE
Problem Installing DS3 Driver 

### ISSUE THREAD

**Issue by ace3df** [nefarius/ScpToolkit#77]
Problem:
http://puu.sh/lN2PV/d819738bad.png
http://puu.sh/lN2SD/0c5044ba30.png

Tried a bunch of things (Force install, booting with USB creds off, etc.)
Kinda at a loss...
Any idea?

Log:
http://puu.sh/lN2wj/305e1aa04c.ZIP

**Comment by NexxusDrako** [comment]
My ticket #76 is doing the exact same thing!

**Comment by NexxusDrako** [comment]
Possibly related, when installing through the links on desktop, it creates a Drivers folder on the desktop, which I don't think belongs there.

**Comment by nefarius** [comment]
[Please try this release](../releases/tag/v1.6.186.15342-BETA) and tell me if it's fixed for you, thanks!

**Comment by ace3df** [comment]
It installed this time! But nothing seems to be able to find it now. 

ppsspp, psx2, dolphin, etc.

I had this problem (didn't show in the Log section):
http://puu.sh/lOhJL/7363c475b8.png

I then tried the SCP Server legacy to just try and got:
http://puu.sh/lOhOL/c4f93022b4.png

**Comment by nefarius** [comment]
There's a tool called `ScpToolkit Debug Info Collector` you can find via start menu, please run it, follow it's instructions and forward me the result.

**Comment by ace3df** [comment]
I uninstalled the USB hub through device manager (Clean Wipe Utility didn't seem to go for reinstalling the PS3 controller like before) - and now it finds the Playstation 3 controller (Dolphin) but no buttons seem to work.

Log:
http://puu.sh/lOiPo/e43b246fc5.zip

**Comment by nefarius** [comment]
Don't run the debug collector after clean wipe, you'll distort the results. Make a clean installation, connect the controller(s), shut down the service via `services.msc` and run the debug collector again.

**Comment by nefarius** [comment]
Could you also please try [this special build](http://www.xup.in/dl,16542130/ScpControl_1.6.188.15342.ZIP/), just overwrite the existing DLL and restart the service. Submit the logs afterwards.

**Comment by NexxusDrako** [comment]
https://dl.dropboxusercontent.com/u/62181279/ScpToolkit_Log-Package_James_1449667611.zip

**Comment by nefarius** [comment]
Could you explain in more detail what' exactly happening on your end? All logs look perfectly fine so I'm a little lost what to recommend now...

**Comment by NexxusDrako** [comment]
Well, I am plugging in the controller,and when the service is on, it will recognise it. However, the lights on the controller are flashing as if the controller is still syncing. When I go into the controller setup screen where it has the buttons and axis input checker, nothing is working. I press a button and nothing will light up. I move an analog stick and the axes don't move. Meanwhile, my x360 wheel and x360 controller work fine.

**Comment by nefarius** [comment]
Could you provide a screenshot of your "Devices & Printers" section along with your device manager, expanding the USB and HID categories?

**Comment by NexxusDrako** [comment]
https://gyazo.com/f9c5d2417eb6968763b4869713d69a7f < Devices and Printers

https://gyazo.com/4bf35eddd7bb2f0174a2c395367a6f63 < Device Manager

**Comment by nefarius** [comment]
Ok, screenshot of `ScpMonitor` please.

**Comment by NexxusDrako** [comment]
https://gyazo.com/e7bc3406232ed20afc3f5e697b537c4c

**Comment by nefarius** [comment]
Thanks, getting more and more mysterious... @_@

**Comment by NexxusDrako** [comment]
I just plugged in my brother's PS3 controller and it worked fine. I'm not sure what's going on anymore.

**Comment by nefarius** [comment]
Give me a few secs, have and idea...

**Comment by NexxusDrako** [comment]
If it involves using the reset button, I just thought of it. heh

**Comment by nefarius** [comment]
Nah, code-based idea =D

**Comment by NexxusDrako** [comment]
Haha, excellent.

**Comment by nefarius** [comment]
Please test again with [this one](http://www.xup.in/dl,15293666/ScpControl_v1.6.189.15343.7z/), should pop up an additional error message in your case (hopefully).

**Comment by NexxusDrako** [comment]
https://gyazo.com/190920034256699c22f6c775f7855283

**Comment by nefarius** [comment]
Ok that's not good. This is a very low level error I can not fix by coding. Can you maybe try a different USB cable? Is the USB port on the controller somehow wiggly or visibly damaged?

**Comment by NexxusDrako** [comment]
The port is very wiggly and indeed damaged. Looks like I've gotta get a new one. heh

I didn't even notice it before. :(

**Comment by nefarius** [comment]
Are you skilled with a soldering iron? Re-flowing solder can be magic :)

**Comment by NexxusDrako** [comment]
Unfortunately not. I can program, but that's about it. haha
Thanks for your help, anyway.

**Comment by nefarius** [comment]
You're welcome :)

**Comment by nefarius** [comment]
Any news from ace3df since we hijacked your thread? :)
