### ISSUE TITLE
Controller won't work sometimes without a restart

### ISSUE THREAD

**Issue by LBPPlayer7** [nefarius/ScpToolkit#776]
the title is self explanatory. no matter what I do I can't get my controller to work without a restart if that happens

**Comment by jacobmix** [comment]
if "that happens"?
Have you tried starting the SCP Service again through services.msc ?
You could also make a [shortcut](https://docs.google.com/document/d/116LwfIM6evk4Dy89N1EQjGYVbcgdIX3cHE8CIR1pflk/edit?usp=sharing) to start the service quickly if you keep having problems.

**Comment by LBPPlayer7** [comment]
I have tried that

**Comment by LBPPlayer7** [comment]
and it didn't work

**Comment by LBPPlayer7** [comment]
the PS3 controller also appears in the unspecified section when that happens and the emulated xbox 360 controller doesn't show up at all
