### ISSUE TITLE
[SOLVED] Software no longer works after recent Windows 10 update

### ISSUE THREAD

**Issue by VitoMolas** [nefarius/ScpToolkit#777]
after the update I can no longer open the driver installer but the controller that I have the driver installed still works, however, I tried reinstalling the software once then now I have no controller to use, please help.

SOLVED: I found out the crash is caused by using softwares that monitors hardware temperature after the Windows 10 creator update. Everything works again after disabling the on-screen display.

**Comment by ArtuHxD** [comment]
Creators ruined it.
