### ISSUE TITLE
Controller keeps disconnecting

### ISSUE THREAD

**Issue by UtkuCQ** [nefarius/ScpToolkit#782]
I had a few problems installing first ( unknown error, driver didn't open or something like that ) I fixed those, HAPPY THAT I WAS, I still couldn't use the controller.. I use it for Fifa, and Either A: It shows that it's working in Monitor but just doesn't work in game, or B it just disconnects after a few seconds, few minutes or just when I open the game.. How do I fix this?

**Comment by phamminh1998** [comment]
same here @@ i have the same problem after update to window 10 creative.
Only solution for me is wipe all driver with clean wipe utility, and reinstall it.
