### ISSUE TITLE
[Windows 10 Pro (Version 1703/Build 15063.296] ScpToolkit suddenly not working. 

### ISSUE THREAD

**Issue by coachl4d2** [nefarius/ScpToolkit#783]
I am unable to open any of the apps from ScpToolkit, when I double click it does nothing. When I try to open Tray Notifications it just crashes every time. This is after the creator update for Windows 10 Pro [Version 1703 - Build 15063.296].

**Comment by VitoMolas** [comment]
same thing happen to me after the update, just wonna say "Great job Microsoft".

**Comment by ArtuHxD** [comment]
Same here, creators update fucked it in the ass with a broom. Hard.

**Comment by batmanlovesuperman** [comment]
Wow i am too late

**Comment by ArtuHxD** [comment]
And no, there is not anything you can do. (EXCEPT ROLL BACK AND LOSE THE FEATURES)

**Comment by VitoMolas** [comment]
guys, I found out how to fix this. I have been using MSI afterburner and enabled the on-screen display, this is what's been making it crash, so disable it.

**Comment by phamminh1998** [comment]
anyone try the solution @VitoMolas used, i have not been using MSI afterburner or any alternate but SCP still crash after Creator update

**Comment by VitoMolas** [comment]
@phamminh1998 the solution I got is from Deamon Tools support https://www.facebook.com/notes/daemon-tools-software-community/daemon-tools-creators-update/10155019526560049 , apparently the update changed how WPF runs, you might want to look at anything that would modify/add to the interface application.

**Comment by luyong20121221** [comment]
ok for me.
![2222](https://user-images.githubusercontent.com/29355804/27012380-20c83c38-4f01-11e7-801f-5dab2615a745.jpg)

**Comment by malwilson** [comment]
Any update on when this will be fixed? its pretty anoying to have to uninstall and reinstall scp driver every time turn on my computer.

**Comment by iVarco** [comment]
Is there alternative Software which runs on windows 10 until this problem is fixed?
