### ISSUE TITLE
Works perfectly for one controller, not for all 4.

### ISSUE THREAD

**Issue by LucidFir** [nefarius/ScpToolkit#788]
First; thanks for making this amazing piece of software. I've got myself 4 @play PS3 controllers as they're on a very good deal at the moment. I have until Saturday to return them for a refund if I can't get them to work.

I got one controller to work in Steam, PCSX2, Dolphin, and Castle Crashers (using XboxCE). However I cannot get all 4 to work at the same time. I've completely uninstalled all the drivers and the installation software and started from scratch a few times, I've made sure the controllers are all plugged in for the duration.

Not sure what else I can do, I hope you can help.

**Comment by Sonickyle27** [comment]
How are you trying to connect them? Bluetooth or cable?

**Comment by LucidFir** [comment]
They are all cable.

It seems that they have some form of conflict. Either any controller after
number 1 doesn't connect or if it does it goes weird.
