### ISSUE TITLE
Creators Update broke ScpToolkit

### ISSUE THREAD

**Issue by Blelle** [nefarius/ScpToolkit#789]
I tried the solutions i found here but nothing worked for me, i don't have RTSS installed or MSI Afterburner.  (Windows 10 Pro x64, 1703, 15063.332)

**Comment by Jelster79** [comment]
Only solution for me so far....reset windows and disable certificates check. It's horrible, dut it's something.

**Comment by Arcterion** [comment]
Yeah, I've been unable to use my PS3 controller for weeks now because whenever I install it it kills my mouse (as seen in #736)
