### ISSUE TITLE
windows 10 problems with recognizing device as xbox controller

### ISSUE THREAD

**Issue by darthblumer** [nefarius/ScpToolkit#791]
I'm a new user and installed the latest version of scp in order to use a ps3 controller for games. I had problems with windows and steam recognizing the controller. scp monitor shows the controller as disconnected. I crawled forums and found that some users have used a beta build to fix their problems, so I downloaded and installed that to see if it worked. Went through a somewhat different installation procedure and now monitor shows my controller as connected and charging. However, I cannot test inputs in either the windows game controllers screen (controller doesn't show up-- it's just a blank list) or in the scp tray (which won't open entirely). This leads me to believe that the xbox controller emulation isn't working. In device manager, there is a section saying libusbK usb devices and under that Playstation(R)3 controller when the controller is plugged in. Anybody else having similar problems? Might be that the program is outdated with newer windows 10 updates...

**Comment by luyong20121221** [comment]
I just tell you what I did :
1.	Install scptoolkit normally,
2.	Run scpdriverinstaller
3.	check all the options on the left except the DS4 driver, then click install.
4.	After a while , windows said “an xbox 360 controller is plugged in”
