### ISSUE TITLE
Very long error message

### ISSUE THREAD

**Issue by ghoul10p** [nefarius/ScpToolkit#794]
I was using SCPToolKit for a few days with no issues. Then I decided to try DS4Windows but had issues with it when using multiple controllers, so I went back to SCPToolKit. Today I got this error and my PS4 controllers no longer connect when plugged in. I need to reinstall the DS4 drivers every time I plug a controller in for then to be recognized. I am on Windows 10. Any way to fix this? Help is greatly appreciated.

![error](https://user-images.githubusercontent.com/29390978/27063182-20d80a42-4fbe-11e7-917a-218da8d15903.jpg)

**Comment by luyong20121221** [comment]
Open
“C:\Program Files\Nefarius Software Solutions\ScpToolkit\ ScpSettings.exe”
Goto “Service settings” and uncheck “Force DS4 driver installation”.

**Comment by ghoul10p** [comment]
I did what you suggested, but the controller still doesn't work unless I reinstall the DS4 driver every time I plug it in. If i unplug it and plug it back in it is recognized as a DS4 controller but doesn't function until the drivers are reinstalled.

**Comment by ghoul10p** [comment]
Maybe the messages will help:

These are the messages that come up when I plug a controller in.
![plug in](https://user-images.githubusercontent.com/29390978/27064244-651ccd18-4fc4-11e7-9857-71e257206540.jpg)

These are the messages that come up when I install the driver.
![install driver](https://user-images.githubusercontent.com/29390978/27064252-7377c390-4fc4-11e7-85ee-00fa6ba499d0.png)

And these are the messages that come up when I unplug the controller.
![unplug](https://user-images.githubusercontent.com/29390978/27064266-81f5f590-4fc4-11e7-9c85-b7ee3a74d858.png)

**Comment by luyong20121221** [comment]
if i were you, i will uninstall all above and do this:
1.plug in DS4 via USB .
2.install scptoolkit normally, then run scpdriverinstaller and check all of them on the left.
that should work.

**Comment by luyong20121221** [comment]
keep in mind dude you cant use DS3 and DS4 via bluetooth at the same time。
