### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by CptTommo** [nefarius/ScpToolkit#799]
I do a complete uninstall, but my bluetooth adapter dont appear on devices manager

**Comment by Sonickyle27** [comment]
Have you restarted yet?

**Comment by CptTommo** [comment]
Yes, specifically, i uninstalled scp, rebooted, re-installed intel bluetooth drivers and reboot again, and controll panel still not showing any bluetooth configs, nor the tray icon.
So i thinked, "better with control and without bluetooth than without both", and tryed install scp again, but it dont locate my bluetooth adapter, so i ended without bluetooth and using a cable in the ds4
Should i have re-install the windows? Will this happen everytime that i need use bluetooth adapter?
