### ISSUE TITLE
Controls blocked when playing a game

### ISSUE THREAD

**Issue by Kelarang** [nefarius/ScpToolkit#80]
I was trying to play Rocket League after the installation of this new program. All fine, i see the n°1 led blinking thinking it was all fine. I launched the game, used my directional arrows to choose what i was gonna do, then i presser R2, and Circle to start playing then the controller froze, and my car was keep going forward. What can i do? I've not a single idea on how i can fix this

My OS is Win10 Enterprise
MB: MSI x99
Vga: GTX 970 
Dunno if those are needed, but i guess it's better for ya

**Comment by nefarius** [comment]
The Log Pack would be even better ;)

**Comment by Kelarang** [comment]
Where do i check it?

**Comment by nefarius** [comment]
Search for `ScpToolkit Debug Info Collector` in your start menu, run it and follow its instructions.

**Comment by Kelarang** [comment]
Ok, found it! There ya go! Hope it's fixable, Xbox's controllers are just so uncomfortable :/

**Comment by Kelarang** [comment]
What kind of file do you need? The all the pack?

**Comment by nefarius** [comment]
The created ZIP.

**Comment by Kelarang** [comment]
Got winrar which is not supported, gimme a sec :P

**Comment by nefarius** [comment]
Just use any of the 2 million one-click upload sites :D

**Comment by Kelarang** [comment]
Got no idea on how to do it :/ I'll try to create a zipped one as soon as i come back. Im sorry, but i really need this to be fixed :/

**Comment by nefarius** [comment]
The tool creates a ZIP file. Take this file and upload it to e.g. http://xup.in and paste the link here.

**Comment by copain9** [comment]
Hi. I'm having the exact same problem and also in Rocket League. I was using an older version of SCP server and at some point I had issues with some input not registered or some bad input registered (I had dpad registerd when I pressed too much button at the same time). So I installed the last version (very nice one btw) and I started having the same problem as OP. 

Buttons get stuck when pressing after a while; they get released ~20 seconds later. and this process repeats just after.

My debug file : http://www.xup.in/dl,96566262/ScpToolkit_Log-Package_Greg_1449777297.zip/

**Comment by copain9** [comment]
The problem also happen with Dishonored. I did some experiments. The stuckness/rumble is a sequence. I timed 9-10 seconds between the moment the controls get stuck and the moment the rumbles activate (controls still stuck). 10seconds after the rumbles stop and the controls unstuck. After that, the time before is gets stuck again varies, it can get from only 1 input to a few ones.

**Comment by Kelarang** [comment]
Op is back:

This is my Log Pack http://www.xup.in/dl,16853221/ScpToolkit_Log-Package_Dani_1449767170.zip/
copain9 added a quite accurate description of the problem. 
Your name isn't new tho, i think i've already played with ya

**Comment by nekogami** [comment]
I think it is may be linked to #39

**Comment by copain9** [comment]
As mentionned in the other report, installing ScpToolkit v1.6.186.15342-BETA seems to fix my issue (tried 2 minutes).

**Comment by Kelarang** [comment]
Hm where can i download it?

**Comment by nefarius** [comment]
[Seriously?](../releases) =P

**Comment by Kelarang** [comment]
Sorry for my ignorance, im not used to this things :/

**Comment by Kelarang** [comment]
(Ty for the link tho)

**Comment by nefarius** [comment]
Np ;)

**Comment by nekogami** [comment]
Got some problem yesterday with the latest beta (cf: last post in #39 for description and available fallback)

**Comment by Kelarang** [comment]
Haven't had the time to thank you for continuing this project, creating an easy way to let us play with our controllers. Thank you!
