### ISSUE TITLE
SCP DSX Service and Virtual Bus not working.

### ISSUE THREAD

**Issue by ExplosiveIsamu00** [nefarius/ScpToolkit#806]
The service is not running; when trying to run it an error message appears that says:

Windows couldn't start the service Scp DSx Service on local computer.
Error 1608: Service or dependency group failed to start.

And the Virtual Bus thing has a yellow exclamation sign over it, so I'm guessing both of those don't work.

I installed everything it asked me to. My controller (DualShock 3) is recognized and the input tester shows that everything works, but I cannot make it work neither with Steam nor with any other games.

Please help.

**Comment by frederico0102** [comment]
The same problem here.
