### ISSUE TITLE
No Devices Show Up In The Beta Version

### ISSUE THREAD

**Issue by TheOnlyYandere** [nefarius/ScpToolkit#810]
I have a Dualshock 3 and 4 controller. I also have a bluetooth dongle. None of them show up when I use the beta version, any solutions?

**Comment by iMaxles** [comment]
Have you uninstalled the drivers from past SCPtoolkit versions? If so, uninstall the drivers from your controller in "Devices and Printers" (right click your controller and uninstall drivers) and reconnect your controller to reinstall the drivers. If they still don't show up after all of this, you might as well reinstall your bluetooth drivers.
