### ISSUE TITLE
Update Nag

### ISSUE THREAD

**Issue by Nopey** [nefarius/ScpToolkit#811]
Upon logging in, I am greeted with a dialog box telling me that SCPToolkit is up to date. 
I think that the auto-run update check should be told to not message when it doesn't find anything, probably using a commandline argument to tell it that it is the auto-run update, and not the user running an update themselves.

**Comment by 15wileyr** [comment]
Yup yup, it is very annoying. like a lot. Also! if you ever get around to adding the ds4 mouse feature like ds4 windows has you would be the shit!

**Comment by 15wileyr** [comment]
there is an Scpupdater.ini file      set the update frequency to 0

**Comment by Nopey** [comment]
That's not really a solution, because I want to know when there is a new version, just not be pestered when there's not.

**Comment by 15wileyr** [comment]
I'm with ya, but id rather just manually check that deal with THAT STOOPID DIALOUNGE BOX. ITS THE END OF THE WORLD

**Comment by Deide** [comment]
What I don't get is how this is running in the first place. I've disabled the "scpToolkit Tray Notifications" in the Start-up list. I've deleted any remaining start-up entries in the registry that wouldn't show in the Start-up List (at least all I could reasonably find). I've stopped the ds3 and updater services from auto running and then even flat-out disabled them.

What is causing this to run?
