### ISSUE TITLE
Game not recognizing any input from controller but monitor picks up input no problem.

### ISSUE THREAD

**Issue by JustinBenz** [nefarius/ScpToolkit#814]
I've completely installed the SCPtoolkit and everything else as shown and have been searching on the internet for hours for solutions to my problem, but have unfortunately come up blank. 

I currently have a Dualshock 3 Controller wired to my computer via USB, I've started up my computer went to the "SCP Driver Installer" selected my controller from the dropdown and continued to install the drivers with no interruptions/mishaps. 
![image](https://user-images.githubusercontent.com/17480901/27526017-cb9dc1f4-5a10-11e7-9cfe-1978ec6a3ff7.png)

I then go to my SCP monitor and open it to find that it says it is working completely fine (USB Charged and all that) 
![image](https://user-images.githubusercontent.com/17480901/27526046-ffc32ed8-5a10-11e7-8dbc-c9a9717d8180.png)
So I open the input tester next, just to see if my computer is picking up what im putting down with my controller and sure enough, it recognizes me smashing buttons all day. (sorry for bad representation of buttons being pressed but I couldn't use both hands and take a screenshot at the same time) 
![image](https://user-images.githubusercontent.com/17480901/27526114-925ef5a6-5a11-11e7-8fd0-fc65e2d7e4d3.png) 

Now this is where the problem begins, so I say hell, everything seems to be working fine right? lets hop into a game like Hollow Knight for example. 
![image](https://user-images.githubusercontent.com/17480901/27526159-fc29367c-5a11-11e7-912a-51d0650780a5.png) I promise you I was mashing every button known to man on this controller as I was taking this screenshot, nothing is happening, the game is not recognizing the controller in the slightest.
So now I go back to the input tester just to see if it can still recognize me pressing things. No. It cant. Not until I completely close out of Hollow Knight will it notice any sort of input from the controller. 

Now as I said before I searched up on the internet for awhile and have come across this little category in my Device Manager, 
![image](https://user-images.githubusercontent.com/17480901/27526247-8bd62992-5a12-11e7-9d25-b159c394a7a0.png) I've seen a solution to where it said I needed to select the controller from that category and make sure the drivers are being updated from the C:/Program Files/Nefarius Solutions/ so I did just that and nothing happened whatsoever. Anyway, moral of the story, game's don't recognize any input from my controller while opened, I dont know what is happening. Any help is appreciated.

**Comment by NLmitchieNL** [comment]
Oh darn, I was hoping there would be a lot of troubleshooting tips here. I'm currently having the same with a DS4.
