### ISSUE TITLE
Playing with Keyboard as Player 1 and DS3 as Player 2

### ISSUE THREAD

**Issue by loofychan** [nefarius/ScpToolkit#817]
As a few other people have mentioned, it doesn't appear to be possible to map my Playstation controller (DS3) as Player 2.  I'm trying to play Overcooked with Player 1 using the keyboard and Player 2 using the Playstation controller.  I only have one controller.  Is there any work around for this? Many thanks for your help!

**Comment by erickrod2003** [comment]
@loofychan same issue here before my pc got factory reset i was using an older version that allowed me to use keyboard as p1 and control as p2 but now i cant find that version and i cant set my control to player 2 when i go to scp monitor its grey'd out so i cant make it p2 :(

**Comment by erickrod2003** [comment]
@nefarius please help

**Comment by Elibrone** [comment]
same issue here please help
