### ISSUE TITLE
Xbox driver install grayed out

### ISSUE THREAD

**Issue by ang3ry** [nefarius/ScpToolkit#824]
I'm trying to stream my Xbox to my PC and use it as an emulator and I was looking for something to download to use my keyboard and mouse with it and I found "XboxKeyboardMouse" but you needed SCPToolKit drivers for it so I downloaded the driver setup. But I saw that the Xbox 360 controller driver checkbox was grayed out. Is there any reason as to why this is occuring?

**Comment by jacobmix** [comment]
You might already have the Xbox 360 controller driver  installed?
On Windows 8, and 10 you don't need to download the driver:
http://support.xbox.com/en-US/xbox-on-windows/accessories/xbox-controller-for-windows-setup
