### ISSUE TITLE
VcRuntime140.dll missing?

### ISSUE THREAD

**Issue by LemonPigOfficial** [nefarius/ScpToolkit#829]
Hello all.
I recently installed ScpToolkit and an error says i am missing "VCNRUNTIME140.DLL".Then the fatal error screen appears.I would appreciate help.
Thanks.

**Comment by keyvankr** [comment]
a simple google search would have showed you that you need the latest .NET framework 4.7 & visual c++ redist 2017 package. please search first before posting.
