### ISSUE TITLE
Please let me turn off the popup messages and update check message

### ISSUE THREAD

**Issue by mtvee** [nefarius/ScpToolkit#832]
The popup messages are not necessary and I don't need to interact with a 'check for update' window that tells me there is nothing to do. Please let me shut all that off. Cheers!

**Comment by bowers12** [comment]
Yes, an option to disable this would be much appreciated, or at least a configuration to have the update checker automatically close on finish.

**Comment by h3mPi** [comment]
Just remove SCP notification from autostart
