### ISSUE TITLE
fake ps3 controller detected ? i don't understand 

### ISSUE THREAD

**Issue by trilippo** [nefarius/ScpToolkit#833]
Hi, i looked for a solution in this forum and on the internet but i don't understand!
i have 3 ps3 controllers. one is original and other two are bought on web. they are all dualshock 3. their are wireless too. the original one works perfectly on my pc with scp toolkit installed. other two controllers won't work, nor wired nor by bluetooth (not avalaible on my pc).
leds flash in all 2 controllers and never stop. i tried to understand reading some topics on this problem ... but i am not able to resolve this problem .. can anyone help me please !????
thanks to all ...

**Comment by Elibrone** [comment]
You should reset the gamepad.

**Comment by DiamondGames204** [comment]
I have the same problem.
