### ISSUE TITLE
Dualshock 3 right analog stick moving by itself.

### ISSUE THREAD

**Issue by PsychoBanda** [nefarius/ScpToolkit#835]
My dualshock 3 right analog stick moves anti clockwise by itself whenever i move the left analog stick forwards. I checked everywhere online and have tried almost everything, Changing the dead-zone threshold and checked and unchecked asynchronous HID report processing. Nothing worked. I don't have a bluetooth dongle so i'm using a usb cable.

**Comment by DiamondGames204** [comment]
Same problem :(

**Comment by RobbinGraves** [comment]
Me too!
