### ISSUE TITLE
I can't use the configuration options

### ISSUE THREAD

**Issue by BraianNR** [nefarius/ScpToolkit#848]
I can't open any of this options pls someone help me ![captura de pantalla 2017-07-19 15 55 58](https://user-images.githubusercontent.com/30299605/28384404-01d550ba-6c9b-11e7-9923-2282105ea82d.png)

**Comment by jacobmix** [comment]
Because they're not implemented.

**Comment by BraianNR** [comment]
and there is no way of implementing it?

**Comment by jacobmix** [comment]
If you wanna work on ScpToolKit go ahead. Make a Pull Request or something.
