### ISSUE TITLE
Unable to install PS4 Controller using latest ScpToolkit v1.7.277.16103-BETA

### ISSUE THREAD

**Issue by sheldon25** [nefarius/ScpToolkit#857]
Hi all, I searched around and was unable to find any information about ps4 controllers and issues with this version. For background, I am on windows 10. 
Using the last full release version ScpToolkit v1.6.238.16010 I am able to install my PS4 controller using the scpdriver installer and use it without issue. Using the beta version though, when you get to the point to show uninitialized/initialized controllers, my PS4 controller will not show up even after plugging it in and unplugging it several times. Windows keep trying to initially set it up as a wireless controller. When I check my control panel on the computer, it shows that windows installed the PS4 controller as "wireless controller. Can anyone point me in the right direction? 

Thanks in advance for your help.

**Comment by Sykaas** [comment]
Hey just writing to say I had the same problem and your solution worked. Uninstalled the 1.7 build and went back to 1.6. Works just fine now.
