### ISSUE TITLE
Fake PS3 controller doesn't work AFTER installing SCP drivers

### ISSUE THREAD

**Issue by lul1234** [nefarius/ScpToolkit#866]
Basically it works when I plug it in and I can play games with it but layout is messed up. After installing scp drivers it stops working.

**Comment by LoLlYdE** [comment]
Is the controller youre using in the [compatible controllers](https://github.com/nefarius/ScpToolkit#compatible-controllers) list?

**Comment by lul1234** [comment]
No I guess. I don't even know how  controller is  called tbh , literally just bought cheapest wired one from Argos to use on my ps3 or laptop

**Comment by LoLlYdE** [comment]
Then theres a good chance it wont work with scp drivers. You said it worked before, so try uninstalling the drivers, reboot your PC and see if it works again

**Comment by lul1234** [comment]
I meant it that it does work without SCP drivers , but layout is messed up. for example in FIFA triangle become square(And the RS doesn't even work in game) And it doesn't work at all after installing SCP drivers
Is there any other program like SCP for controller on pc?

**Comment by LoLlYdE** [comment]
I dont know about a program that does what youre looking for. Maybe you can rebind keys in the options somewhere? I cant help you further than that.
