### ISSUE TITLE
High CPU usage : 1 core at 100%

### ISSUE THREAD

**Issue by LaPomme57** [nefarius/ScpToolkit#875]
Hi,
I just made a fresh install of Windows 10 x64 on my PC and SCP Toolkit is now constantly using ~15% of my CPU (i7 4770K @3.5Ghz) only when my controller is plugged with SCP service started.
EDIT : by _just_ I actually mean it's been a month and it persists since then

Here is a screenshot with global CPU usage,
![scp](https://user-images.githubusercontent.com/30773233/29003600-10b8bee6-7aba-11e7-9ec1-3fe966003e35.png)
and here one with detailed core usage.
![scp 2](https://user-images.githubusercontent.com/30773233/29003613-53b97686-7aba-11e7-9ee2-eb22cf79e209.png)

Here is also the debug information as requested on the official thread.
[ScpToolkit_Log-Package_Pierre_1502024314.zip](https://github.com/nefarius/ScpToolkit/files/1203091/ScpToolkit_Log-Package_Pierre_1502024314.zip)

I hope this issue can be fixed

**Comment by Zcehtro** [comment]
I too am having this issue.

**Comment by Sonickyle27** [comment]
What controller are you using? How is the controller connected?

**Comment by Zcehtro** [comment]
Genuine DS3 controller, by means of bluetooth.

**Comment by LaPomme57** [comment]
DS4 Controller, using a cable (also tried with other cables)

**Comment by Sonickyle27** [comment]
If you rotate one of the sticks constantly and move the mouse, does the cursor stutter?

**Comment by LaPomme57** [comment]
No it doesn't
