### ISSUE TITLE
How to properly remove the PS3 controler once I'm done with gaming?

### ISSUE THREAD

**Issue by zackultimate** [nefarius/ScpToolkit#878]
I have this issue: Every time I take out the controller to use it on my PS3 again, scptoolkit basically breaks.

Once I'm done with the PS3 and I re-connected the controller it basically dies. I'm forced to reinstall and everything and restart my PC.

What am I doing wrong?

**Comment by sheldon25** [comment]
To remove the controller hold r1 l1 and the ps3 button for a few seconds. If on bluetooth, the controller with turn off. If plugged in, it will start flashing all 4 lights. But when disconnecting the usb cable it will then turn off.
