### ISSUE TITLE
PS3 Controller doesn't work on my windows 10

### ISSUE THREAD

**Issue by Daxny97** [nefarius/ScpToolkit#880]
Hi guys and sorry for my english :D.
Today I tried to use PS3 controller on my new Windows 10 with SCPToolKit. I follow the guide but at the end of the drivers' installation the pc still recognise the controller as PS3 controller and not as an XBOX 360 controller as it should be. I tried to find a solution on google and, with the beta of SPCToolKit, I managed to  turn on the led of the controller. If i use SPC Server i can also test the vibration of my controller but i still can't use it in the game. I hope some of you can give me a solution. 
if it could be useful i use an original PS3 controller and i want to use it with USB.

**Comment by ShadixAced** [comment]
Please see #888 , I am also on Windows 10 Creators Preview, and I gave a solution that worked for 2 people ATM.
