### ISSUE TITLE
Stoped working after KB4034674 Windows 10 update.

### ISSUE THREAD

**Issue by Tolentino19** [nefarius/ScpToolkit#881]
After my last Windows 10 update - KB4034674 (2017-8-8), my ps3 controller stoped working. I mean, the controller works for about 15 seconds then it stop working (even the led turn off).
I tried uninstalling (clean wipe) and resintalling all the drivers, services and bus in the stable version and the same thing with the pre-release version, but with the same results.
Edit: I use it with the USB cable, not bluetooth.

**Comment by Zcehtro** [comment]
I use it with Bluetooth and have the same problem.

**Comment by dellaValle31** [comment]
Same here. The only workaround which worked for me was to boot with drivers checking deactivated (advanced reboot)
