### ISSUE TITLE
When installing keyboard stops working

### ISSUE THREAD

**Issue by Matsminer** [nefarius/ScpToolkit#891]
When I install the program I choose wireless controller under the ds 4 driver drop down menu, but then the controller doesnt work. If i choose something called CSR8510 A10, then the controller starts working, but my keyboard stops working. I dont know of a fix. Please help. I want to be able to use controller and keyboard at the same time

Edit: The CSR8510 is my bluetooth usb thing,

**Comment by ShadixAced** [comment]
Might be a conflict between your keyboard and Bluetooth. Try by uninstalling the DS4 BT controller and put it via USB. If it works, you can stay like that. Or else, try by reinstalling the BT driver and see if it works again.
