### ISSUE TITLE
BSOD caused by ScpVBus.sys

### ISSUE THREAD

**Issue by pilouk** [nefarius/ScpToolkit#893]
As soon as i start my ps4 controller i receive a BSOD error : driver_verifier_iomanager_violation caused by scpVBus.

I joined 3 dmp which are all related

Note : i tried with input mapper and services .. both result in BSOD

[minidump.zip](https://github.com/nefarius/ScpToolkit/files/1240038/minidump.zip)

**Comment by ShadixAced** [comment]
ntoskrnl.exe crashed with SCPVBus.sysn might come with 0x07 : The driver called IoCompleteRequest while its cancel routine was still set.

**Comment by ShadixAced** [comment]
Which version of Windows are you using ?

**Comment by pilouk** [comment]
Win 10 last version

**Comment by ShadixAced** [comment]
Insider Preview or normal versions ?

**Comment by pilouk** [comment]
Normal

**Comment by ShadixAced** [comment]
That's odd... Try by using the SCPToolkit Clean Wipe utility and then reinstall the drivers. Might be a slight issue.
