### ISSUE TITLE
Controller being stupid. pls hlp.

### ISSUE THREAD

**Issue by Ritikkhilnani** [nefarius/ScpToolkit#894]
When I plug in my controller the lights blink but nothing happens. I tried everything on YouTube and nothing works. A few months ago I tried it and got frustrated so I formatted my computer. I forgot about it until now. I tried to do everything calmly now and luck isn't on my side. Help would be greatly appreciated.

**Comment by Ritikkhilnani** [comment]
When I plug in my controller the lights blink but nothing happens. I tried everything on YouTube and nothing works. A few months ago I tried it and got frustrated so I formatted my computer. I forgot about it until now. I tried to do everything calmly now and luck isn't on my side. Help would be greatly appreciated.

**Comment by ShadixAced** [comment]
Which version of Windows are you using ?
