### ISSUE TITLE
Problems with ScpToolkit Profile Manager (English)

### ISSUE THREAD

**Issue by Rarkdreik** [nefarius/ScpToolkit#913]
In Profile Manager, the following problems happens:

- Create a profile with a name, "example", put it on "Pad"
You add it, but it comes out as "New Profile". You create another one, scroll it down and the previous one gets named "example". The new one returns to be New Profile, and if you keep trying it it gives of error. (See image, I add the logs that I found, I do not know if they will be these).

Then we have that it is not possible to access the other options below. (View image).

- It is also difficult to select exactly what key you want from the keyboard (Keystrokes), and this is complicated sometimes for online games (tested in AION MMORPG).

- If the name of profile dont matter you, you can create the profile with some effort, but for bluetooth, maybe it works at first, more later fails or it does not work (It may be because the profile is not the first one, or because it has several active profiles, but also if it is the first one and the only asset).

tested versions:

- Latest version, beta (ScpToolkit v1.7.277.16103-BETA). [Attachments of this version].
- Latest version (ScpToolkit v1.6.238.16010)

![captura](https://user-images.githubusercontent.com/31737943/30172999-9649a8b8-93f6-11e7-9dda-4009d9246972.PNG)
[ScpDsxInstaller_Rarkdreik.log.zip](https://github.com/nefarius/ScpToolkit/files/1285324/ScpDsxInstaller_Rarkdreik.log.zip)

**Comment by yohaskan** [comment]
confirmed
Same problem.
I only succeed if I do not close the Profile Manager. but keystroke is always in turbo mode (Turbo mode is not enabled yet)
