### ISSUE TITLE
DS3's pressure sensitive didn't work with Unity

### ISSUE THREAD

**Issue by phields** [nefarius/ScpToolkit#919]
Unity3D(v.2017.1) cannot detect any pressure-sensitive buttons.
Is there any way to let Unity3D detect these pressure's data?

**Comment by Formedras** [comment]
You'd need to use the same API as the lilypad-SCP plugin. Basically, you'd need to program an interface to SCPControl. If you're lucky, Unity will let you set up the 14 axes you'd need and map the interface to those Unity controls. If not, you'd need to handle them yourself in their entirety.
(14 axes: 4 for shoulders, 4 for face buttons, 4 for the sticks - 2 per stick, and 2 for the D-pad - technically 4, but you might as well combine the opposite directions into single axes.)
