### ISSUE TITLE
Strange error message

### ISSUE THREAD

**Issue by grayfoxn312** [nefarius/ScpToolkit#923]
(UPDATE: I HAVE INCLUDED THE DEBUG COLLECTOR INFO) Controller was working for a year and then I get this message. What happened? Tried a clean wipe and deleting the PS3 controller from device manager, reinstalling the 360 driver and the service to redo it but it didn't work. Help please. 
![image](https://user-images.githubusercontent.com/32320510/30897082-32ece20e-a309-11e7-812d-a7351d0d2f98.png)
[ScpToolkit_Log-Package_mitch_000_1507494660.zip](https://github.com/nefarius/ScpToolkit/files/1367186/ScpToolkit_Log-Package_mitch_000_1507494660.zip)

**Comment by jackmawas** [comment]
hi , can u plz help me with this error msg
![image](https://user-images.githubusercontent.com/33337425/32358719-abab6df8-c048-11e7-9bdb-debe78badf47.png)
thanks
