### ISSUE TITLE
ScpToolkit Updater keeps popping up even though I'm on the latest version

### ISSUE THREAD

**Issue by nitorita** [nefarius/ScpToolkit#928]
My ScpToolkit is already at the latest version. An older thread from last year said this was fixed already, but it's still happening. It keeps popping up after a restart or wake up from sleep.

Is there any way to just stop it from updating altogether? I don't really care about updating anymore because after all, "Don't fix what isn't broken." I'm surprised that ScpToolkit wouldn't have this option in the settings even after so long after release.

I already tried disabling the updater in services. Didn't work.

Thank you.

**Comment by Rudelic** [comment]
go to your start up preferences and try to toggle the updater off so it won't open by itself.
