### ISSUE TITLE
First Controller connected to pc doesnt work ( via bluetooth )

### ISSUE THREAD

**Issue by deku55** [nefarius/ScpToolkit#929]
so basically the problem is that the first controller (DS3) connected to my pc doesnt work like it connects the lights turn on but no buttons work.  and when i connect my other controllers ( i have 4  all ds3)  they work completly fine. i tried connecting another controller first after a reboot and the same problem occurs. so the controllers work just fine 
i need help  wanna play 4 player games :(

and another question would be if i can change the function of the controller so they dont work like a keyboard or a mouse for example the right stick is moving the cursor

**Comment by deku55** [comment]
and btw the 2nd controller connected works as the first controller

**Comment by Rudelic** [comment]
Have you checked if it receives an input from the remote?

**Comment by kr4ft** [comment]
I think I've got the same bug here. I've got two DS3 controllers paired (via bluetooth). Also use a xbox one controller and a steam controller on the same PC.
Of the DS3 controllers, _only_ the second one works. Doesn't matter which of the two DS3 controllers is set to 2. 

Both DS3 controllers produce inputs which are detected in the Input Tester. However only the DS3 controller set to 2. Furthermore there is only one Xbox 360 controller installed in device manager.

**Comment by deku55** [comment]
ok i fixed the problem all 4 controllers work now.

the problem was that under device manager there were 2 xbox 360 driver.
i deinstalled the one under "usb-devices" and then the controller started working.
the one that should remain is under "xbox 360  peripherals".
hope i could help some ppl with the same problem :)
