### ISSUE TITLE
Windows 10 won't detect DS3 Controller (Device Descriptor Request Failed)

### ISSUE THREAD

**Issue by Danilux** [nefarius/ScpToolkit#930]
Hi, I have been going crazy, Windows 10 does not recognize my DS3 controller as a Playstation 3 controller, it shows "Unknown USB Device (Device Descriptor Request Failed)" every time I plugg it in, so I can't install any of the softwares that make PS3 controllers work like MotionInJoy or SCPToolkit because these software can't see my controller in order to apply the custom drivers on, has anyone run into this?

**Comment by Danilux** [comment]
Ok, I have been making progress, I used for the first time the latest ScpToolkit v1.7.277.16103-BETA and the first controller now works, even wireless with BT dongle, but the second keeps giving me the device descriptor error, If I rerun the installer, it only shows the controller already working, not sure what to do to try en fix this, any ideas?

**Comment by Danilux** [comment]
Here's some screenshot of the problem with the second controller, non of them is original though, maybe they both have the same hardware id? so they al clashing on windows and only one is being recognized?
![error en aministrador de dispositivos](https://user-images.githubusercontent.com/414068/31473748-cebfc466-aecc-11e7-8600-64321076dd45.png)
![one working](https://user-images.githubusercontent.com/414068/31473753-d43474aa-aecc-11e7-997d-b4feac84f113.png)
<img width="505" alt="control 2 id hardware" src="https://user-images.githubusercontent.com/414068/31473772-f38c04e4-aecc-11e7-943b-87ece1596052.png">

**Comment by Rudelic** [comment]
Seems like windows doesn't like your USB cable or the port you're connecting to, try to change to a different port, or change the cable.

**Comment by Danilux** [comment]
One joystick works, the other one doesn't, I believe that joystick is simply bad, they are new but not original so, I'm pretty much hopeless at this point
