### ISSUE TITLE
Disables Bluetooth and can't turn it back on???

### ISSUE THREAD

**Issue by Zortothan** [nefarius/ScpToolkit#932]
I can connect my ps3 controller perfectly through usb to my laptop and it works fine. But for some reason the toolkit disables my bluetooth and there is no option to turn it back on. There's no button to turn my bluetooth back on where there should be. This is a problem because I use wireless headphones since my audio jack is broken. Is there any way to change the app's permissions so that it can't access my bluetooth?

**Comment by Rudelic** [comment]
Once you install the DS3 Bluetooth driver to your laptop bluetooth, it becomes a dedicated bluetooth adapter for the remote, and won't work as a bluetooth adapter for anything else but PS3 remotes. You won't be able to connect your headphones through bluetooth as long as the adapter is changed to work with PS3 controllers.
