### ISSUE TITLE
No Bluetooth - Couldn't get connection handle [48, 20]

### ISSUE THREAD

**Issue by shua586** [nefarius/ScpToolkit#935]
Thank you for this project. It was working great for a little while but then all of a sudden the wireless capability stopped functioning. Whenever I disconnect my genuine PS3 controller from USB, it attempts to connect to Bluetooth but SCPMonitor pops an error that states "Couldn't get connection handle [48, 20]". 

I've tried 3 different dongles, and uninstalled/installed the drivers many times. Any help would be greatly appreciated! Thank you!

**Comment by amcsi** [comment]
I'm getting the same issue and would also like to know how to fix this.

**Comment by shua586** [comment]
I have no idea how I resolved this but eventually did. It started working
after uninstalling the Bluetooth drivers and reinstalling - all through the
SCPToolkit app
