### ISSUE TITLE
PCSX2 plugin issue

### ISSUE THREAD

**Issue by LBPPlayer7** [nefarius/ScpToolkit#936]
I can't map anything except the rumble with the DualShock 3 native mode mod for PCSX2. Why is that?

**Comment by Formedras** [comment]
#888 seems to have your answer. For the workaround, uninstall and downgrade to the latest stable (non-preview) release.

**Comment by LBPPlayer7** [comment]
I am on a stable version though

**Comment by Formedras** [comment]
v1.6.238.16010?

**Comment by LBPPlayer7** [comment]
I think I updated to a preview build to check if that would fix it, and it didn't, and I'm on Windows 7

**Comment by Formedras** [comment]
Not a clue, then. Sorry. I haven't used Windows 7 on a private computer since Windows 8 came out.

**Comment by LBPPlayer7** [comment]
ok
