### ISSUE TITLE
The service (DS3Service) doesn't start 

### ISSUE THREAD

**Issue by SheyKiZz** [nefarius/ScpToolkit#937]
Hello,when I want to use my controller I need to restart and disable driver signature enforcement and I can use my controller but I need to do  this every time I need to use my controller and that's annoying

Sorry for the english,Im french so I do how i can *

Goodbye

**Comment by Rudelic** [comment]
Go to Device Manager, and find your XBOX 360 Controller, right click and select update drivers.
