### ISSUE TITLE
Apparently caused my graphics card to go nuts?

### ISSUE THREAD

**Issue by crysthala** [nefarius/ScpToolkit#938]
I installed the toolkit recently just to try it out with a Dualshock 3, and just now, I encountered a rather alarming issue. I had Firefox, Unity / MonoDevelop, OneNote 2010, Photoshop CS5, and Iron Pig (a free game from Steam) open, and was looking at a website.

Abruptly, Windows switched the color scheme to the "basic" version, the PC slowed down a bit, and my graphics card started producing coil whine. It's done that before, but never when essentially idle, and the pitch was varying wildly. That coupled with the slowdown had me pretty alarmed. I started closing programs very quickly and checked a diagnostic tool (Speccy). My graphics card's temperature was fluctuating, but hanging out around 70 degrees C.

I ended a few background processes (mostly leftovers from the other programs I had open) with no effect. When I ended the background processes for ScpToolkit, the coil whine immediately stopped, and my graphics card cooled down considerably -- almost 10 degrees in under a minute, and it's now hanging out around 43.

I am assuming this was a freak accident, but given the nature of the issue, I thought it'd be worth reporting anyway. DxDiag and the toolkit's log:

[DxDiag.txt](https://github.com/nefarius/ScpToolkit/files/1366660/DxDiag.txt)
[ScpDsxService_MONSTER$.log](https://github.com/nefarius/ScpToolkit/files/1366668/ScpDsxService_MONSTER.log)

**Comment by Rudelic** [comment]
Looks like your remote kept plugging and unplugging really quickly, maybe try and check your wire?
