### ISSUE TITLE
Constant input from R1/R2 and Triangle/Circle/Cross/Square

### ISSUE THREAD

**Issue by Arkann07** [nefarius/ScpToolkit#942]
Hello,

As the title says, my DualShock 3 controller is acting like I'm constantly pressing R1/R2 and Triangle/Circle/Cross/Square, even though I'm not. Here is what the Input tester looks like:
![capture d ecran 1](https://user-images.githubusercontent.com/32742904/31504273-3bc06e9e-af72-11e7-9f20-a5a4262582c0.png)
My controller works fine on PS3, and used to work just fine on my previous computer. I tried using an older version of the wrapper and used other USB ports, without success. I am on Windows 10.

Any ideas whay may cause this ?

**Comment by Rudelic** [comment]
Have you tried pressing the reset button on your remote? or replacing the cable which runs to your PC from the remote? Both of those have caused similar issues for me.

**Comment by Arkann07** [comment]
Thank you very much Rudelic ! Luckily I had another cable so I tried both your suggestions, and now my controller works like a charm. Case closed !
