### ISSUE TITLE
What does the Clean Wipe Utility do?

### ISSUE THREAD

**Issue by kd56** [nefarius/ScpToolkit#943]
I was having problems with my DS3 not working sometimes so I decided to try reinstalling the drivers, I used the Clean Wipe Utility to remove everything. Before the wipe my controller would work most of the time but after using it and reinstalling the drivers/SCP I haven't been able to get it to work. I've tried removing everything related to SCP and reinstalling but nothing has helped. When I plug in my DS3 it shows in devices and the 4 red lights flash but then stop flashing after a couple seconds. Anyone know what the Clean Wipe Utility did?

**Comment by Rudelic** [comment]
Go to Device Manager, and uninstall the drivers for PLAYSTATION3(R) Controller, XBOX 360 Controller, and make sure to select the delete check mark while uninstalling. afterwards, try to install it all again.
