### ISSUE TITLE
Hi! Please include Atheros QCA61x4 Bluetooth 4.1

### ISSUE THREAD

**Issue by Tulkis** [nefarius/ScpToolkit#946]
First thank you for your work! 
Do you think possible include this device compatibility?
Regards,
Eduard.

**Comment by dunderdotten** [comment]
second this, please add <3

**Comment by jcweaver997** [comment]
I third this

**Comment by Rudelic** [comment]
Have you tried running Zadig to brute force the Bluetooth driver onto it?
