### ISSUE TITLE
All versions of this software do not work, please help!

### ISSUE THREAD

**Issue by krstoserofil** [nefarius/ScpToolkit#948]
The latest stable release of this doesn't work for my friend. The latest stable release does connect the ds3 to pc, but most of controls do not WORK. Both analog sticks and all the buttons on the right side. The newest beta ver. just gives a fatal error when we try to start the driver setup. We have watched and read x9999 guides and tutorials, uninstalled-reinstalled, rebooted a bunch of times but nothing helps!

The controller is functional, it works normally on ps3.

**Comment by HudsonGraeme** [comment]
Have you tried using the wipe utility, then trying to reinstall?
