### ISSUE TITLE
Bluetooth stopped connecting pad

### ISSUE THREAD

**Issue by Uiasdnmb** [nefarius/ScpToolkit#950]
I had no issues running (latest non beta) version for last 6 months, but today Bluetooth just stopped working (fine over cable). Tried reinstalling this like 5 times (even beta version) to no avail

Anyone had a similar problem?
From what I see it connects but doesn't setup as a gamepad properly (screenshot taken after clearing logs and pressing ps button).

![scperror](https://user-images.githubusercontent.com/6961003/31640583-9d4f9c82-b2df-11e7-886c-4b16c6e5ae4a.PNG)

**Comment by kosmic0** [comment]
same here sometimes when i disconnect the bluetooth the joypad connects and works fine but if i retsart pc same problem again the controller does not get detected an dkeeps flahsing

**Comment by SilentPrayeCG** [comment]
You tried reinstall it through Clean Wipe + Driver install utility?

**Comment by Uiasdnmb** [comment]
Multiple times but it didn't solve the problem (and caused some BSODs actually).
Ended up reconnecting dongle to another usb port and reinstalling, though it still doesn't work on "broken" port, so there's hoping it doesn't happen (again) enough times for me to run out of ports.

**Comment by SilentPrayeCG** [comment]
You tried uninstall hub which contain this port?
I'm don't think some soft can break port physically.

**Comment by Uiasdnmb** [comment]
Well it's not broken per se (hence the quotation marks), and bluetooth device did report pad being discovered, just never turned it into a viable controller.

I didn't want to uninstall the usb hub, since it's an internal hub and it's a pain to get into (my cables are a mess) and I have cpu pump connected there so I don't want to take risks of it having problems with reinstalling those.

**Comment by SilentPrayeCG** [comment]
I meant just through device manager, to reinstall driver. But scp did not touch usb hubs drivers, as i know. It only overwrite default bluetooth driver.
