### ISSUE TITLE
Mouse stops working when I install Scptoolkit

### ISSUE THREAD

**Issue by saleri** [nefarius/ScpToolkit#951]
When I first installed it, I accidentally choose the Mouse USB port instead of the PS3 one, so the mouse stopped working, I managed to follow that mini-guide to uninstall the drivers, but forgot to check the box to delete the drivers from the PC. 

Then I installed them correctly the second time, and it worked perfectly for, like, 1 day. I came home and I think that the driver that I didn't delete installed itself again through an automatic update or something.

I uninstalled it again and deleted it this time, the problem I'm having now is that even if I select the correct boxes on the installer, my mouse always stops working after installing the Drivers. Anyone knows what's the problem?

**Comment by SilentPrayeCG** [comment]
You can try Clean Wipe utility first, then delete mouse from PC through device manager (completely, with driver) and then let Windows to install it back, then install SCP back  again.
