### ISSUE TITLE
Pressure sensitivity can't working on PCSX2

### ISSUE THREAD

**Issue by michaelxfung** [nefarius/ScpToolkit#955]
I was setup pcsx2 1.2.1, scptoolkit v1.7.277.16103-BETA, a dualshock 2 controller plugged into usb adapter on windows 10.
I have a Blue DS4 controller plugged into usb cable, but scptoolkit can't detect it.
![000](https://user-images.githubusercontent.com/32967743/31842117-28a766ba-b61f-11e7-891a-37236992c82c.jpg)

is holding on this configuration
![001](https://user-images.githubusercontent.com/32967743/31839994-0278677c-b616-11e7-9443-983e28b03f6c.jpg)
so... I renamed padPokopom.dll to padPokopom.bak skip the process.
![002](https://user-images.githubusercontent.com/32967743/31842141-3f968252-b61f-11e7-9dc4-aac33f1cbf28.jpg)
just I setup a controller plugin, that keep looping show the error msg.
so...I closed "ScpToolkit Tray Notifications", setup a controller plugin and go to "Test Device"
![003](https://user-images.githubusercontent.com/32967743/31842390-89d9703a-b620-11e7-80f1-bebd07d19378.jpg)
in PCSX2 my DS2 controller is no reaction.....
I try to setup on pcsx2 1.4.0, that is same result.

Ref 1: [https://github.com/nefarius/ScpToolkit/wiki/Pressure-sensitivity-in-PCSX2](https://github.com/nefarius/ScpToolkit/wiki/Pressure-sensitivity-in-PCSX2)
Ref 2: [https://github.com/nefarius/ScpToolkit/issues/927](https://github.com/nefarius/ScpToolkit/issues/927)

**Comment by michaelxfung** [comment]
[https://github.com/nefarius/ScpToolkit/releases/tag/v1.6.238.16010](url)
New Version Fixed for this Problem, Thank you.
![004](https://user-images.githubusercontent.com/32967743/32978217-9ee82c14-cc78-11e7-84c1-3e2aa28c8009.jpg)
![006](https://user-images.githubusercontent.com/32967743/32978245-2547d994-cc79-11e7-9b22-cb5117325b91.jpg)
![005](https://user-images.githubusercontent.com/32967743/32978218-9f10ba4e-cc78-11e7-8385-9617a68b767a.jpg)

**Comment by daygr** [comment]
Hmm, I'm not so sure. I get the same error when plugging in my controller, now. With ScpToolkit v1.7.277.16103-BETA.
![error_scptoolkit](https://user-images.githubusercontent.com/8953579/34699723-f581e48c-f4ac-11e7-92ab-b3346cb0f881.JPG)
