### ISSUE TITLE
Is there a way to permanently link DS4 v2 already?

### ISSUE THREAD

**Issue by rhynoceros** [nefarius/ScpToolkit#958]
Hi guys as far as I know Nefarius has stopped working on this project so I'm not expecting a new release. 

However, has someone found a fix/workaround to link the DS4 v2 permanently yet on W10? Right now if I want to install the driver through the installer I get 2 different interfaces (0 and 3). Installing interface 3 then runs fine but after every reboot, I need to reinstall the driver again going through the installer, yet again...

A fix would be very much appreciated and maybe we could just brainstorm a little.

Also I'm 99,9% sure this issue is DS4 v2 related because until last week I was using a 1st gen DS4 and it worked fine for over a year. Also I've tried doing complete reinstalls of ScpToolkit, I even formatted PC for this.

Note: I haven't tried the v1.7 BETA yet because I've read that it has some bugs. I've been using the latest 1.6 release until now.

**Comment by malxenos** [comment]
I've always had to install to interface 0 and i dont install drivers to interface 3. Sadly if i unplug it or restart the computer... have to reinstall it every time. DS4 v1 works flaws though. Best I have atm.
Sorry I can't be of any other help
