### ISSUE TITLE
Scp Virtual Bus Error, Device Manager can't verify signature

### ISSUE THREAD

**Issue by Harunoki** [nefarius/ScpToolkit#959]
The device manager shows this message: **Windows cannot verify the digital signature for the drivers required for this device. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source. (Code 52)**
Because of this the service can't start, It stopped working after I updated to Windows 10 FCU 1709

**Comment by vpontin** [comment]
Sadly until @nefarius be able to fix the driver signature you'll need to disable Secure Boot (if enabled) and then [disable driver signature enforcement](https://winaero.com/blog/disable-driver-signature-enforcement-permanently-in-windows-10/).
