### ISSUE TITLE
Please make option to disable popups

### ISSUE THREAD

**Issue by mikegonzalez2k** [nefarius/ScpToolkit#961]
My PS3 controller has a loose cable and as a result I have to unplug and replug it in every once in a while.
When I do lots of SCPToolkit popups appear which are distracting.
Please create a way to disable these popup notifications.
A better way might be to send them to a logfile so the user can read the errors.

**Comment by ClintEstwood** [comment]
I have the same problem: a billion of Scp's messages.  
Please, add "Disable notifications" option.

Thanks!

**Comment by phaylo** [comment]
The culprit here is "ScpTrayApp" process since it's the responsible for showing such notifications.
Killing "ScpTrayApp" process from Task Manager will get rid of the popups.

**Comment by mikegonzalez2k** [comment]
Is the Tray app at all required for SCP to run properly though?  Does it do any sort of reinitialization of the app or maintain it's connectivity?

**Comment by phaylo** [comment]
To be honest, I didn't take a look at the code base at all and only skimmed it. But I can tell you I've been using the controllers perfectly fine without the tray app for weeks.
