### ISSUE TITLE
How do you get the PS3 controller to unplug on its own

### ISSUE THREAD

**Issue by metrize** [nefarius/ScpToolkit#962]
When I unplug it, games like PUBG still think I have a controller connected so how do I make sure the controller drivers are turned offw hen the controller is unplugged

**Comment by HudsonGraeme** [comment]
Open Task Manager, find "ScpService" in the list of running programs (Windows 7) and Exit it.
Do the same for win 7, but "ScpService" may be under the Processes tab.

**Comment by NLmitchieNL** [comment]
You can also press the R1 + L1 + PS button to disconnect a controller.
