### ISSUE TITLE
Vibration issue on win 10

### ISSUE THREAD

**Issue by Nani86** [nefarius/ScpToolkit#963]
Hello,
I've been using SCPtoolkit for my DS3 since I had win 7. I now have win 10. At first it was working fine even after the upgrade but a few months ago, my vibration function seemed to not be able to change amplitude. It still does seem like it can do different kinds of vibrations but it cannot do lower amplitudes anymore which kind of makes it pointless and difficult to use. I would greatly appreciate it if someone can provide a solution to this. Thank you.

**Comment by axbmcuser** [comment]
Maybe try a clean install? I switched from win7 to win10 (clean install/no upgrade) recently, both systems got a fresh SCPtoolkit install and could not tell any difference while extensively testing original DS3 with vibration in many games/programs.

**Comment by Nani86** [comment]
First of all, thanks a ton for the reply. 
By clean install,are you talking about the windows or SCPtoolkit? If you meant the first, that's near impossible for me at this point without investing 2 entire days and atleast an extra for backing up stuff and not to mention all the intricate customization I've done to my install. everything from codecs to registry edits etc. There are also plenty of software from various schools that I will loose the license for if I were to delete them XD. I will try reinstalling the SCP toolkit when I get a bit of time though :)
