### ISSUE TITLE
ScpService high cpu usage (permanently) after wake from sleep

### ISSUE THREAD

**Issue by h3llrais3r** [nefarius/ScpToolkit#970]
ScpService works great, but it seems to constantly use up to 65% of cpu usage (even without connection of ps3 controller) after wake from sleep.
Restarting the service solves the problem, but I don't think it's the purpose of restarting the service after each wake from sleep.

EDIT: I'm using the latest version from github. (beta)

**Comment by BMFG666** [comment]
I have the same problem. CPU usage on ScpService.exe hits about 90-100%.
i7-965x Windows 10 Pro 64bit here. I managed to limit this by perma assigning it to only one thread and lowering the priority, still it's burning one thread out of eight, up to 100%.
Please HELP!!! I tried to run as admin and different compatibility modes with scpservice none helped.
