### ISSUE TITLE
"Windows could not start the SCP DSx Service service on Local Computer"

### ISSUE THREAD

**Issue by Ryan1473** [nefarius/ScpToolkit#979]
Been using ScpToolkit on my laptop for quite a few months with no problems whatsoever. Recently just replaced my HDD and tried to install ScpToolkit to play some games but I can't get the SCP DSx Service to start up.

Every time I try to open the ScpToolkit settings manager I get this message.

![scpcantopen](https://user-images.githubusercontent.com/33757310/32955252-6060799a-cbad-11e7-87ae-53c3afdbc865.PNG)

I go into services to start up SCP DSx Service and I get this each time I try to start it up

![servicesproblem](https://user-images.githubusercontent.com/33757310/32955370-a9f563ae-cbad-11e7-9563-0b4a1e3d008d.PNG)

I've never ever had this problem when I've used it before. I've tried disabling my firewall, disabling secure boot but that doesn't seem to work.

![scptooldriver](https://user-images.githubusercontent.com/33757310/32955419-d25dc4da-cbad-11e7-8448-6350a65f137b.PNG)
![usb](https://user-images.githubusercontent.com/33757310/32955426-d475227c-cbad-11e7-8d28-574a74978319.PNG)

I can't find any SCP driver or whatever you call it under system devices :/. Any ideas?

**Comment by HudsonGraeme** [comment]
Have you tried running the Scp Driver Installer again? I just had this problem and going through the installer solved it for me.
