### ISSUE TITLE
its 2017, and there's still this error

### ISSUE THREAD

**Issue by jxv16** [nefarius/ScpToolkit#981]
'Oh Sh... A fatal error occured. Consult the logs for details.'

how i fix this? T_T

**Comment by rkubes** [comment]
Look through the logs and see if there's anything that stands out as an error.

They are usually located at: C:\Program Files\Nefarius Software Solutions\ScpToolkit\Logs

**Comment by jxv16** [comment]
"<log4j:event logger="ScpDriverInstaller.MainWindow" timestamp="1511537227700" level="INFO" thread="1"><log4j:message>SCP Driver Installer 1.6.238.16010 [Built: 01/10/2016 09:52:11]</log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="CIB8AEED00CEA9" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="CIB8AEED00CEA9\alumno" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="CIB8AEED00CEA9" /></log4j:properties><log4j:locationInfo class="ScpDriverInstaller.MainWindow" method="Window_Initialized" file="" line="0" /></log4j:event>
<log4j:event logger="ScpControl.Driver.NativeLibraryWrapper`1" timestamp="1511537227774" level="DEBUG" thread="1"><log4j:message>Preparing to load DIFxAPI</log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="CIB8AEED00CEA9" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="CIB8AEED00CEA9\alumno" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="CIB8AEED00CEA9" /></log4j:properties><log4j:locationInfo class="ScpControl.Driver.NativeLibraryWrapper`1" method="LoadNativeLibrary" file="" line="0" /></log4j:event>
<log4j:event logger="ScpControl.Driver.NativeLibraryWrapper`1" timestamp="1511537227774" level="DEBUG" thread="1"><log4j:message>Called from 64-Bit process</log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="CIB8AEED00CEA9" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="CIB8AEED00CEA9\alumno" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="CIB8AEED00CEA9" /></log4j:properties><log4j:locationInfo class="ScpControl.Driver.NativeLibraryWrapper`1" method="LoadNativeLibrary" file="" line="0" /></log4j:event>
<log4j:event logger="ScpControl.Driver.NativeLibraryWrapper`1" timestamp="1511537227774" level="DEBUG" thread="1"><log4j:message>DIFxAPI path: F:\ScpToolKit\DIFxApi\amd64\DIFxAPI.dll</log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="CIB8AEED00CEA9" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="CIB8AEED00CEA9\alumno" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="CIB8AEED00CEA9" /></log4j:properties><log4j:locationInfo class="ScpControl.Driver.NativeLibraryWrapper`1" method="LoadNativeLibrary" file="" line="0" /></log4j:event>
<log4j:event logger="ScpControl.Driver.NativeLibraryWrapper`1" timestamp="1511537228010" level="DEBUG" thread="1"><log4j:message>Loaded library: F:\ScpToolKit\DIFxApi\amd64\DIFxAPI.dll</log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="CIB8AEED00CEA9" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="CIB8AEED00CEA9\alumno" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="CIB8AEED00CEA9" /></log4j:properties><log4j:locationInfo class="ScpControl.Driver.NativeLibraryWrapper`1" method="LoadNativeLibrary" file="" line="0" /></log4j:event>
<log4j:event logger="ScpDriverInstaller.MainWindow" timestamp="1511537228013" level="INFO" thread="1"><log4j:message>Microsoft Windows 8.1 Professional (6.3.9600.0 AMD64) detected</log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="CIB8AEED00CEA9" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="CIB8AEED00CEA9\alumno" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="CIB8AEED00CEA9" /></log4j:properties><log4j:locationInfo class="ScpDriverInstaller.MainWindow" method="Window_Initialized" file="" line="0" /></log4j:event>
<log4j:event logger="ScpControl.Driver.NativeLibraryWrapper`1" timestamp="1511537228016" level="DEBUG" thread="1"><log4j:message>Preparing to load libwdi</log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="CIB8AEED00CEA9" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="CIB8AEED00CEA9\alumno" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="CIB8AEED00CEA9" /></log4j:properties><log4j:locationInfo class="ScpControl.Driver.NativeLibraryWrapper`1" method="LoadNativeLibrary" file="" line="0" /></log4j:event>
<log4j:event logger="ScpControl.Driver.NativeLibraryWrapper`1" timestamp="1511537228041" level="DEBUG" thread="1"><log4j:message>Called from 64-Bit process</log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="CIB8AEED00CEA9" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="CIB8AEED00CEA9\alumno" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="CIB8AEED00CEA9" /></log4j:properties><log4j:locationInfo class="ScpControl.Driver.NativeLibraryWrapper`1" method="LoadNativeLibrary" file="" line="0" /></log4j:event>
<log4j:event logger="ScpControl.Driver.NativeLibraryWrapper`1" timestamp="1511537228043" level="DEBUG" thread="1"><log4j:message>libwdi path: F:\ScpToolKit\libwdi\amd64\libwdi.dll</log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="CIB8AEED00CEA9" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="CIB8AEED00CEA9\alumno" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="CIB8AEED00CEA9" /></log4j:properties><log4j:locationInfo class="ScpControl.Driver.NativeLibraryWrapper`1" method="LoadNativeLibrary" file="" line="0" /></log4j:event>
<log4j:event logger="ScpControl.Driver.NativeLibraryWrapper`1" timestamp="1511537228269" level="FATAL" thread="1"><log4j:message>Couldn't load library F:\ScpToolKit\libwdi\amd64\libwdi.dll: System.ComponentModel.Win32Exception (0x80004005): %1 no es una aplicación Win32 válida</log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="CIB8AEED00CEA9" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="CIB8AEED00CEA9\alumno" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="CIB8AEED00CEA9" /></log4j:properties><log4j:locationInfo class="ScpControl.Driver.NativeLibraryWrapper`1" method="LoadNativeLibrary" file="" line="0" /></log4j:event>
<log4j:event logger="ScpDriverInstaller.App" timestamp="1511537228347" level="FATAL" thread="1"><log4j:message><![CDATA[An unexpected error occured on application startup: System.Windows.Markup.XamlParseException: La inicialización de 'ScpDriverInstaller.MainWindow' produjo una excepción. ---> System.Reflection.TargetInvocationException: Se produjo una excepción en el destino de la invocación. ---> System.DllNotFoundException: No se puede cargar el archivo DLL 'libwdi.dll': No se puede encontrar el módulo especificado. (Excepción de HRESULT: 0x8007007E)
   en ScpControl.Driver.WdiWrapper.wdi_set_log_level(WdiLogLevel level)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   en System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   en System.Activator.CreateInstance(Type type, Boolean nonPublic)
   en ScpControl.Driver.NativeLibraryWrapper`1.CreateInstanceOfT()
   en System.Lazy`1.CreateValue()
   en System.Lazy`1.LazyInitValue()
   en ScpDriverInstaller.MainWindow.Window_Initialized(Object sender, EventArgs e)
   en System.Windows.FrameworkElement.RaiseInitialized(EventPrivateKey key, EventArgs e)
   en System.Windows.FrameworkElement.TryFireInitialized()
   en MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   en System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   en System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   en System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   en System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   en System.Windows.Application.DoStartup()
   en System.Windows.Application.<.ctor>b__1_0(Object unused)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   en System.Windows.Threading.DispatcherOperation.InvokeImpl()
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   en MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   en System.Windows.Threading.DispatcherOperation.Invoke()
   en System.Windows.Threading.Dispatcher.ProcessQueue()
   en System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   en System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   en MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   en MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   en System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   en System.Windows.Application.RunDispatcher(Object ignore)
   en System.Windows.Application.RunInternal(Window window)
   en ScpDriverInstaller.App.Main()]]></log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="CIB8AEED00CEA9" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="CIB8AEED00CEA9\alumno" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="CIB8AEED00CEA9" /></log4j:properties><log4j:locationInfo class="ScpDriverInstaller.App" method="&lt;OnStartup&gt;b__0" file="" line="0" /></log4j:event>"

i dont understand this T_T

**Comment by Syst3mSh0ck** [comment]
It shows ScpDriverInstaller.exe crashed due to System.DllNotFoundException which is a dependency issue, possibly due to UAC. Logs show "Couldn't load library F:\ScpToolKit\libwdi\amd64\libwdi.dll" and looking up libwdi.dll confirms it to be a Windows Driver Installer library for USB devices which ScpDriverInstaller.exe uses to install the usb miniport class drivers for dualshock support. Make sure you right click on ScpDriverInstaller.exe and Run as Administrator otherwise it won't work properly.

**Comment by jxv16** [comment]
i do that, and still not working T_T
