### ISSUE TITLE
Unsigned Driver

### ISSUE THREAD

**Issue by danmakuz** [nefarius/ScpToolkit#982]
Using Windows 10, fresh install. I can't start the service because the driver is unsigned. 

In device manager it says for Scp Virtual Bus Driver: 
"Windows cannot verify the digital signature for the drivers required for this device. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source. (Code 52)"

Disabling driver signature enforcement will work, but I have to do it every time my computer starts up, which is very inconvenient. Is there another viable workaround or a planned fix for this? 

EDIT: I just ended up, after reading other threads, turning off secure boot and used 
"bcdedit.exe /set nointegritychecks on." in command prompt.

**Comment by JamieeLee** [comment]
Or you can leave secure boot enabled and just reset the keys in the uefi / efi bios and reboot fixes the problem.
