### ISSUE TITLE
Bluetooth dongle not working after reboot

### ISSUE THREAD

**Issue by IdiosApps** [nefarius/ScpToolkit#983]
Installed drivers fine for the bluetooth dongle, and can install them after a reboot - but until I reinstall them, the bluetooth dongle neither flashes nor connects to my PS3 controller

Not sure what I did (guess I just did another install of the setup) but things have stuck for a while now.

**Comment by cery92** [comment]
I have the same problem, but I've found someting strange, maybe useful..

![ps3bluetoothport](https://user-images.githubusercontent.com/14994652/34392315-b54d325a-eb4b-11e7-87d1-0806ed3bb713.PNG)
This is after I've installed the drivers(bluetooth and ps3 joypad), it's all working perfectly, and the HCI and LMP version are 6.***.
If I only restart the computer, the versions don't change, and the controller connect via bluetooth without problem.

But if I shutdown and restart the pc, the versions change as seen in the image below, and the controller doesn't connect via bluetooth anymore..
![ps3bluetoothportafterreboot](https://user-images.githubusercontent.com/14994652/34392352-ef1c04c0-eb4b-11e7-9633-6c16af490715.PNG)

I've tried also to uncheck the "force bluetooth driven installation" and "force dualshock 3 driver installation" options in the setting manager, but checked or not it doesn't change anything..

Well, I hope this is useful to developers to fix the bluetooth problem XD
