### ISSUE TITLE
Wrong controller number DS3

### ISSUE THREAD

**Issue by HButlex** [nefarius/ScpToolkit#985]
Everytime i leave my controller and it goes to sleep the controller number changes to slot 2 and i can't change it without restarting my pc

**Comment by danmakuz** [comment]
I'm also having this issue. Controller sleeps, I reconnect and it is assigned port 2

**Comment by ryanssealey** [comment]
I'm having the same issue. I've tried switching around the "Always unplug virtual controller" and "Reserve controller slot" options in Service settings, but no luck. If the computer goes to sleep (I think that's when it happens), the controller gets assigned to Slot 2. The only way I've managed to get it back to Slot 1 is to restart the computer.

**Comment by jayyyin** [comment]
I'm also getting this issue @nefarius , any workarounds you know of? it seems to think that a new controller is connecting when the previous connected one goes to sleep.

**Comment by Master-Squishy** [comment]
I also get this, very annoying. Happens every time PC goes to sleep, can't seem to find an option anywhere to set controller to port 1 which makes no sense at all.
