### ISSUE TITLE
ScpToolkit stops working after Sleep, Hibernate, and/or Signout.

### ISSUE THREAD

**Issue by doomrider7** [nefarius/ScpToolkit#989]
Exactly what it says on the topic header. Every time I put the computer on sleep, hibernate, or sign-out, I need to shut down and start my PC again to get to work. Any fixes for this issue?

**Comment by danmakuz** [comment]
Make sure SCP service is running at boot up
Make sure there isn't a yellow warning in device manager

If it's the "unsigned driver" error that shows in device manager, it's because the driver for SCP is unsigned. There is a workaround for that.

**Comment by Master-Squishy** [comment]
Hi I have this same issue, every single time it stops working I have to do a restart it gets really annoying, I leave the room to make a cup of tea come back and I have to shut down my PC start it up again and restart whatever game I was playing (witcher...) any way to get it to stop weirdly breaking on sleep

**Comment by ToastyMisbehaviour** [comment]
Hello there, I have the exact same issue! I play Redout a lot and every time my computer goes to sleep, my game won't recognise any buttons anymore. I use a Ps3 controller. I tried everything from reinstalling the scp software to restarting the scp service in the service manager (which boots up with windows) and also restarting the game but none of this works. device manager says it works fine. Outside of the game, the controller works for some reason. It is so annoying to be forced to restart your computer every single time. Please help.
