### ISSUE TITLE
Dpad random inputs

### ISSUE THREAD

**Issue by jross86** [nefarius/ScpToolkit#99]
While playing, every once in a while I get a short flurry of spurious Dpad inputs.  Using original ds3.

Possibly related to this issue?
https://github.com/nefarius/ScpServer/issues/94

**Comment by Jan200101** [comment]
Have you tried the newest solution in #94 ?

**Comment by jross86** [comment]
Enhanced Pointer precision was not checked, so that can't be the problem.  The link to 94 was speculative, starting to think what I'm experiencing is unrelated.

**Comment by Jan200101** [comment]
okay a log would be nice

**Comment by jross86** [comment]
Here it is:
[ScpToolkit_Log-Package_jross_1450907883.zip](https://github.com/nefarius/ScpServer/files/71301/ScpToolkit_Log-Package_jross_1450907883.zip)

**Comment by jross86** [comment]
Update: problem has fixed itself.  I didn't change anything, no idea what happened.
