### ISSUE TITLE
I'd like to get back to my regular bluetooth driver. 

### ISSUE THREAD

**Issue by Rolandocmr** [nefarius/ScpToolkit#990]
i know if i use this tool i wont get to use bluetooth, so i needed to use the tool once, now i want to uninstall and go back to regular bluetooth.

Thankyou for an amazing work!

**Comment by cruizerdog** [comment]
I could be wrong but I think for windows you just go to device manager and uninstall the libusbk driver and it will auto install the old driver, or you may have to manual install the old driver
