### ISSUE TITLE
Request: support for gioteck wired controller

### ISSUE THREAD

**Issue by Jshah01** [nefarius/ScpToolkit#992]
I would like to use a gioteck wired ps3 controller using scp toolkit please. I think  part of the issue is that when plugged in it chooses to install it's own drivers (instead of the standard PS gamepad ones). So the drivers are not successfully installing.

product page - http://www.argos.co.uk/product/6319489

**Comment by kbro420** [comment]
if you cant figure it out and want a quick fix till they update i used joytokey with my gioteck controller... before my dogs ate it :(
