### ISSUE TITLE
controller won't connect to bluetooth

### ISSUE THREAD

**Issue by cruizerdog** [nefarius/ScpToolkit#994]
So there has probably been a ton of these comments made but i couldn't find a solution so submitting my own issue.

As title says i can get controller to work with cable but won't connect if i disconnect the cable as shown in the below pictures
![cable](https://user-images.githubusercontent.com/33596178/33652527-84a375fc-dab5-11e7-976a-f3db068a54fc.PNG)
![disconnected](https://user-images.githubusercontent.com/33596178/33652531-884f68aa-dab5-11e7-8dcc-73ab19189a24.PNG)

Installed using scptoolkit setup.exe, installed the bluetooth driver and ps3 controller driver with genuine controller.
![drivers](https://user-images.githubusercontent.com/33596178/33652577-b9774272-dab5-11e7-9a89-7491addd3009.png)
Assuming the bluetooth dongle was setup correcting as it is displayed as working with scptoolkit
![bluetooth](https://user-images.githubusercontent.com/33596178/33652657-f3d1381a-dab5-11e7-9838-5fe196ec77d5.png)

i've done a few uninstalls and reinstalls of scptoolkit and the drivers and tried using SCP Pair tool suggested in a previously posted issue (however remote is already set as the host address and pressing set didn't seem to change anything anyway).

cheers for the replies in advance and sorry but i wasn't sure what debugging logs etc. i should have posted.

**Comment by cruizerdog** [comment]
i also tried running SCPserver but it was doing the same as SCPmonitor/SCPservice and the pair button was greyed out

**Comment by cruizerdog** [comment]
https://github.com/nefarius/ScpToolkit/wiki/Compatible-Bluetooth-Devices

So is this the only bluetooth adapters that work?

**Comment by molitar** [comment]
The new version is total garbage!  The old version could force install on any Bluetooth device and it would work.  This new version is a total downgrade!  I am trying to figure out what version worked correctly as this 1.6 is crap!
